<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>23 Fraction Data | A Course in Exploratory Data Analysis</title>
  <meta name="description" content="23 Fraction Data | A Course in Exploratory Data Analysis" />
  <meta name="generator" content="bookdown 0.25 and GitBook 2.6.7" />

  <meta property="og:title" content="23 Fraction Data | A Course in Exploratory Data Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="23 Fraction Data | A Course in Exploratory Data Analysis" />
  
  
  

<meta name="author" content="Jim Albert" />


<meta name="date" content="2022-04-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="binned-data-ii.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Course in Exploratory Data Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface<span></span></a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#an-eda-course"><i class="fa fa-check"></i><b>1.1</b> An EDA Course<span></span></a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#organization"><i class="fa fa-check"></i><b>1.2</b> Organization<span></span></a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#preface-excerpt-from-eda-by-john-w.-tukey-addison-wesley-1977"><i class="fa fa-check"></i><b>1.3</b> Preface Excerpt from <em>EDA</em> by John W. Tukey (Addison-Wesley, 1977)<span></span></a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#examples-not-case-histories"><i class="fa fa-check"></i><b>1.3.1</b> Examples, NOT case histories<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>2</b> Introduction<span></span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction.html"><a href="introduction.html#what-is-data-analysis"><i class="fa fa-check"></i><b>2.1</b> What is data analysis?<span></span></a></li>
<li class="chapter" data-level="2.2" data-path="introduction.html"><a href="introduction.html#what-is-data-and-where-do-we-find-it"><i class="fa fa-check"></i><b>2.2</b> What is data and where do we find it?<span></span></a></li>
<li class="chapter" data-level="2.3" data-path="introduction.html"><a href="introduction.html#meet-our-first-data"><i class="fa fa-check"></i><b>2.3</b> Meet our first data<span></span></a></li>
<li class="chapter" data-level="2.4" data-path="introduction.html"><a href="introduction.html#how-does-exploratory-data-analysis-eda-differ-from-confirmatory-data-analysis-cda"><i class="fa fa-check"></i><b>2.4</b> How does exploratory data analysis (EDA) differ from confirmatory data analysis (CDA)?<span></span></a></li>
<li class="chapter" data-level="2.5" data-path="introduction.html"><a href="introduction.html#how-is-eda-different-from-cda"><i class="fa fa-check"></i><b>2.5</b> How is EDA different from CDA?<span></span></a></li>
<li class="chapter" data-level="2.6" data-path="introduction.html"><a href="introduction.html#john-tukeys-contribution"><i class="fa fa-check"></i><b>2.6</b> John Tukey’s contribution<span></span></a></li>
<li class="chapter" data-level="2.7" data-path="introduction.html"><a href="introduction.html#four-principles-of-eda-the-four-rs"><i class="fa fa-check"></i><b>2.7</b> Four principles of EDA (the four R’s)}<span></span></a></li>
<li class="chapter" data-level="2.8" data-path="introduction.html"><a href="introduction.html#an-exploratory-look-at-our-data"><i class="fa fa-check"></i><b>2.8</b> An exploratory look at our data<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="working-with-a-single-batch-displays.html"><a href="working-with-a-single-batch-displays.html"><i class="fa fa-check"></i><b>3</b> Working with a Single Batch – Displays<span></span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="working-with-a-single-batch-displays.html"><a href="working-with-a-single-batch-displays.html#meet-the-data"><i class="fa fa-check"></i><b>3.1</b> Meet the Data<span></span></a></li>
<li class="chapter" data-level="3.2" data-path="working-with-a-single-batch-displays.html"><a href="working-with-a-single-batch-displays.html#the-basic-stemplot"><i class="fa fa-check"></i><b>3.2</b> The Basic Stemplot<span></span></a></li>
<li class="chapter" data-level="3.3" data-path="working-with-a-single-batch-displays.html"><a href="working-with-a-single-batch-displays.html#looking-at-a-data-distribution"><i class="fa fa-check"></i><b>3.3</b> Looking at a Data Distribution<span></span></a></li>
<li class="chapter" data-level="3.4" data-path="working-with-a-single-batch-displays.html"><a href="working-with-a-single-batch-displays.html#stemplot-variations-breaking-the-stem-at-different-locations"><i class="fa fa-check"></i><b>3.4</b> Stemplot variations – breaking the stem at different locations<span></span></a></li>
<li class="chapter" data-level="3.5" data-path="working-with-a-single-batch-displays.html"><a href="working-with-a-single-batch-displays.html#stemplot-variations-2-5-and-10-leaves-per-stem"><i class="fa fa-check"></i><b>3.5</b> Stemplot variations – 2, 5, and 10 leaves per stem<span></span></a></li>
<li class="chapter" data-level="3.6" data-path="working-with-a-single-batch-displays.html"><a href="working-with-a-single-batch-displays.html#guidance-in-constructing-a-stemplot"><i class="fa fa-check"></i><b>3.6</b> Guidance in Constructing a Stemplot<span></span></a></li>
<li class="chapter" data-level="3.7" data-path="working-with-a-single-batch-displays.html"><a href="working-with-a-single-batch-displays.html#making-the-stemplot-resistant"><i class="fa fa-check"></i><b>3.7</b> Making the Stemplot Resistant<span></span></a></li>
<li class="chapter" data-level="3.8" data-path="working-with-a-single-batch-displays.html"><a href="working-with-a-single-batch-displays.html#a-few-closing-comments"><i class="fa fa-check"></i><b>3.8</b> A Few Closing Comments<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="single-batch-summaries.html"><a href="single-batch-summaries.html"><i class="fa fa-check"></i><b>4</b> Single Batch: Summaries<span></span></a>
<ul>
<li class="chapter" data-level="4.1" data-path="single-batch-summaries.html"><a href="single-batch-summaries.html#meet-the-data-1"><i class="fa fa-check"></i><b>4.1</b> Meet the Data<span></span></a></li>
<li class="chapter" data-level="4.2" data-path="single-batch-summaries.html"><a href="single-batch-summaries.html#ranks-and-depths"><i class="fa fa-check"></i><b>4.2</b> Ranks and Depths<span></span></a></li>
<li class="chapter" data-level="4.3" data-path="single-batch-summaries.html"><a href="single-batch-summaries.html#letter-values-a-set-of-summary-values"><i class="fa fa-check"></i><b>4.3</b> Letter Values: A Set of Summary Values<span></span></a></li>
<li class="chapter" data-level="4.4" data-path="single-batch-summaries.html"><a href="single-batch-summaries.html#counting-in"><i class="fa fa-check"></i><b>4.4</b> Counting In<span></span></a></li>
<li class="chapter" data-level="4.5" data-path="single-batch-summaries.html"><a href="single-batch-summaries.html#five-number-summary"><i class="fa fa-check"></i><b>4.5</b> Five-number Summary<span></span></a></li>
<li class="chapter" data-level="4.6" data-path="single-batch-summaries.html"><a href="single-batch-summaries.html#other-letter-values"><i class="fa fa-check"></i><b>4.6</b> Other Letter Values<span></span></a></li>
<li class="chapter" data-level="4.7" data-path="single-batch-summaries.html"><a href="single-batch-summaries.html#measures-of-center"><i class="fa fa-check"></i><b>4.7</b> Measures of Center<span></span></a></li>
<li class="chapter" data-level="4.8" data-path="single-batch-summaries.html"><a href="single-batch-summaries.html#measures-of-spread"><i class="fa fa-check"></i><b>4.8</b> Measures of Spread<span></span></a></li>
<li class="chapter" data-level="4.9" data-path="single-batch-summaries.html"><a href="single-batch-summaries.html#identifying-outliers"><i class="fa fa-check"></i><b>4.9</b> Identifying Outliers<span></span></a></li>
<li class="chapter" data-level="4.10" data-path="single-batch-summaries.html"><a href="single-batch-summaries.html#a-new-example"><i class="fa fa-check"></i><b>4.10</b> A New Example<span></span></a></li>
<li class="chapter" data-level="4.11" data-path="single-batch-summaries.html"><a href="single-batch-summaries.html#relationship-with-normal-data"><i class="fa fa-check"></i><b>4.11</b> Relationship with Normal Data<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="boxplots.html"><a href="boxplots.html"><i class="fa fa-check"></i><b>5</b> Boxplots<span></span></a>
<ul>
<li class="chapter" data-level="5.1" data-path="boxplots.html"><a href="boxplots.html#the-data"><i class="fa fa-check"></i><b>5.1</b> The Data:<span></span></a></li>
<li class="chapter" data-level="5.2" data-path="boxplots.html"><a href="boxplots.html#constructing-a-single-boxplot"><i class="fa fa-check"></i><b>5.2</b> Constructing A Single Boxplot<span></span></a></li>
<li class="chapter" data-level="5.3" data-path="boxplots.html"><a href="boxplots.html#interpreting-a-boxplot"><i class="fa fa-check"></i><b>5.3</b> Interpreting a Boxplot<span></span></a></li>
<li class="chapter" data-level="5.4" data-path="boxplots.html"><a href="boxplots.html#boxplots-to-compare-batches"><i class="fa fa-check"></i><b>5.4</b> Boxplots to Compare Batches<span></span></a></li>
<li class="chapter" data-level="5.5" data-path="boxplots.html"><a href="boxplots.html#comparisons-using-medians"><i class="fa fa-check"></i><b>5.5</b> Comparisons using Medians<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="spread-level-plot.html"><a href="spread-level-plot.html"><i class="fa fa-check"></i><b>6</b> Spread Level Plot<span></span></a>
<ul>
<li class="chapter" data-level="6.1" data-path="spread-level-plot.html"><a href="spread-level-plot.html#lets-meet-the-data"><i class="fa fa-check"></i><b>6.1</b> Let’s Meet the Data<span></span></a></li>
<li class="chapter" data-level="6.2" data-path="spread-level-plot.html"><a href="spread-level-plot.html#comparing-batches-in-the-raw-scale"><i class="fa fa-check"></i><b>6.2</b> Comparing Batches in the Raw Scale<span></span></a></li>
<li class="chapter" data-level="6.3" data-path="spread-level-plot.html"><a href="spread-level-plot.html#whats-wrong"><i class="fa fa-check"></i><b>6.3</b> What’s Wrong?<span></span></a></li>
<li class="chapter" data-level="6.4" data-path="spread-level-plot.html"><a href="spread-level-plot.html#the-spread-vs-level-plot"><i class="fa fa-check"></i><b>6.4</b> The Spread vs Level Plot<span></span></a></li>
<li class="chapter" data-level="6.5" data-path="spread-level-plot.html"><a href="spread-level-plot.html#reexpression"><i class="fa fa-check"></i><b>6.5</b> Reexpression<span></span></a></li>
<li class="chapter" data-level="6.6" data-path="spread-level-plot.html"><a href="spread-level-plot.html#reanalysis-of-the-data-in-new-scale"><i class="fa fa-check"></i><b>6.6</b> Reanalysis of the data in new scale<span></span></a></li>
<li class="chapter" data-level="6.7" data-path="spread-level-plot.html"><a href="spread-level-plot.html#wrap-up"><i class="fa fa-check"></i><b>6.7</b> Wrap Up<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="comparing-batches-iii.html"><a href="comparing-batches-iii.html"><i class="fa fa-check"></i><b>7</b> Comparing Batches III<span></span></a>
<ul>
<li class="chapter" data-level="7.1" data-path="comparing-batches-iii.html"><a href="comparing-batches-iii.html#a-case-study-where-the-spread-vs-level-plot-works"><i class="fa fa-check"></i><b>7.1</b> A Case Study where the Spread vs Level Plot Works<span></span></a></li>
<li class="chapter" data-level="7.2" data-path="comparing-batches-iii.html"><a href="comparing-batches-iii.html#a-case-study-where-the-spread-vs-level-plot-doesnt-work"><i class="fa fa-check"></i><b>7.2</b> A Case Study where the Spread vs Level Plot Doesn’t Work<span></span></a></li>
<li class="chapter" data-level="7.3" data-path="comparing-batches-iii.html"><a href="comparing-batches-iii.html#some-final-comments-about-spread-vs.-level-plots"><i class="fa fa-check"></i><b>7.3</b> Some final comments about spread vs. level plots<span></span></a></li>
<li class="chapter" data-level="7.4" data-path="comparing-batches-iii.html"><a href="comparing-batches-iii.html#why-does-the-spread-vs.-level-plot-work"><i class="fa fa-check"></i><b>7.4</b> Why does the spread vs. level plot work?<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="transformations.html"><a href="transformations.html"><i class="fa fa-check"></i><b>8</b> Transformations<span></span></a>
<ul>
<li class="chapter" data-level="8.1" data-path="transformations.html"><a href="transformations.html#why-do-we-rexpress-data"><i class="fa fa-check"></i><b>8.1</b> Why do we rexpress data?<span></span></a></li>
<li class="chapter" data-level="8.2" data-path="transformations.html"><a href="transformations.html#the-shape-of-the-data"><i class="fa fa-check"></i><b>8.2</b> The shape of the data<span></span></a></li>
<li class="chapter" data-level="8.3" data-path="transformations.html"><a href="transformations.html#trivial-reexpressions"><i class="fa fa-check"></i><b>8.3</b> Trivial reexpressions<span></span></a></li>
<li class="chapter" data-level="8.4" data-path="transformations.html"><a href="transformations.html#nontrivial-expressions-the-power-family"><i class="fa fa-check"></i><b>8.4</b> Nontrivial expressions: the power family<span></span></a></li>
<li class="chapter" data-level="8.5" data-path="transformations.html"><a href="transformations.html#some-properties-of-the-power-family"><i class="fa fa-check"></i><b>8.5</b> Some properties of the power family<span></span></a></li>
<li class="chapter" data-level="8.6" data-path="transformations.html"><a href="transformations.html#the-log-transformation"><i class="fa fa-check"></i><b>8.6</b> The log transformation<span></span></a></li>
<li class="chapter" data-level="8.7" data-path="transformations.html"><a href="transformations.html#ladders-of-powers"><i class="fa fa-check"></i><b>8.7</b> Ladders of powers<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="reexpressing-for-symmetry.html"><a href="reexpressing-for-symmetry.html"><i class="fa fa-check"></i><b>9</b> Reexpressing for Symmetry<span></span></a>
<ul>
<li class="chapter" data-level="9.1" data-path="reexpressing-for-symmetry.html"><a href="reexpressing-for-symmetry.html#data-for-the-day"><i class="fa fa-check"></i><b>9.1</b> Data for the day<span></span></a></li>
<li class="chapter" data-level="9.2" data-path="reexpressing-for-symmetry.html"><a href="reexpressing-for-symmetry.html#why-is-this-data-hard-to-interpret"><i class="fa fa-check"></i><b>9.2</b> Why is this data hard to interpret?<span></span></a></li>
<li class="chapter" data-level="9.3" data-path="reexpressing-for-symmetry.html"><a href="reexpressing-for-symmetry.html#checking-for-symmetry-by-looking-at-midsummaries"><i class="fa fa-check"></i><b>9.3</b> Checking for symmetry by looking at midsummaries<span></span></a></li>
<li class="chapter" data-level="9.4" data-path="reexpressing-for-symmetry.html"><a href="reexpressing-for-symmetry.html#reexpressing-to-achieve-approximate-symmetry"><i class="fa fa-check"></i><b>9.4</b> Reexpressing to achieve approximate symmetry<span></span></a></li>
<li class="chapter" data-level="9.5" data-path="reexpressing-for-symmetry.html"><a href="reexpressing-for-symmetry.html#hinkleys-quick-method"><i class="fa fa-check"></i><b>9.5</b> Hinkley’s quick method<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="reexpressing-for-symmetry-ii.html"><a href="reexpressing-for-symmetry-ii.html"><i class="fa fa-check"></i><b>10</b> Reexpressing for Symmetry II<span></span></a>
<ul>
<li class="chapter" data-level="10.1" data-path="reexpressing-for-symmetry-ii.html"><a href="reexpressing-for-symmetry-ii.html#data-for-the-day-1"><i class="fa fa-check"></i><b>10.1</b> Data for the day<span></span></a></li>
<li class="chapter" data-level="10.2" data-path="reexpressing-for-symmetry-ii.html"><a href="reexpressing-for-symmetry-ii.html#symmetry-plot"><i class="fa fa-check"></i><b>10.2</b> Symmetry plot<span></span></a></li>
<li class="chapter" data-level="10.3" data-path="reexpressing-for-symmetry-ii.html"><a href="reexpressing-for-symmetry-ii.html#roots-and-logs"><i class="fa fa-check"></i><b>10.3</b> Roots and logs<span></span></a></li>
<li class="chapter" data-level="10.4" data-path="reexpressing-for-symmetry-ii.html"><a href="reexpressing-for-symmetry-ii.html#hinkleys-method"><i class="fa fa-check"></i><b>10.4</b> Hinkley’s method<span></span></a></li>
<li class="chapter" data-level="10.5" data-path="reexpressing-for-symmetry-ii.html"><a href="reexpressing-for-symmetry-ii.html#matched-transformations"><i class="fa fa-check"></i><b>10.5</b> Matched transformations<span></span></a></li>
<li class="chapter" data-level="10.6" data-path="reexpressing-for-symmetry-ii.html"><a href="reexpressing-for-symmetry-ii.html#matching-method-1"><i class="fa fa-check"></i><b>10.6</b> Matching Method 1<span></span></a></li>
<li class="chapter" data-level="10.7" data-path="reexpressing-for-symmetry-ii.html"><a href="reexpressing-for-symmetry-ii.html#matching-method-2"><i class="fa fa-check"></i><b>10.7</b> Matching Method 2<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="transformations-summary.html"><a href="transformations-summary.html"><i class="fa fa-check"></i><b>11</b> Transformations Summary<span></span></a>
<ul>
<li class="chapter" data-level="11.1" data-path="transformations-summary.html"><a href="transformations-summary.html#why-do-we-reexpress-data"><i class="fa fa-check"></i><b>11.1</b> Why do we reexpress data?<span></span></a></li>
<li class="chapter" data-level="11.2" data-path="transformations-summary.html"><a href="transformations-summary.html#serendipitous-effects-of-transformation"><i class="fa fa-check"></i><b>11.2</b> Serendipitous effects of transformation<span></span></a></li>
<li class="chapter" data-level="11.3" data-path="transformations-summary.html"><a href="transformations-summary.html#when-is-it-worthwhile-to-transform"><i class="fa fa-check"></i><b>11.3</b> When is it worthwhile to transform?<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="introduction-to-plotting.html"><a href="introduction-to-plotting.html"><i class="fa fa-check"></i><b>12</b> Introduction to Plotting<span></span></a>
<ul>
<li class="chapter" data-level="12.1" data-path="introduction-to-plotting.html"><a href="introduction-to-plotting.html#meet-the-data-2"><i class="fa fa-check"></i><b>12.1</b> Meet the data<span></span></a></li>
<li class="chapter" data-level="12.2" data-path="introduction-to-plotting.html"><a href="introduction-to-plotting.html#graph-the-data"><i class="fa fa-check"></i><b>12.2</b> Graph the data<span></span></a></li>
<li class="chapter" data-level="12.3" data-path="introduction-to-plotting.html"><a href="introduction-to-plotting.html#describing-the-fit"><i class="fa fa-check"></i><b>12.3</b> Describing the fit<span></span></a></li>
<li class="chapter" data-level="12.4" data-path="introduction-to-plotting.html"><a href="introduction-to-plotting.html#looking-at-the-residuals"><i class="fa fa-check"></i><b>12.4</b> Looking at the residuals<span></span></a></li>
<li class="chapter" data-level="12.5" data-path="introduction-to-plotting.html"><a href="introduction-to-plotting.html#an-alternative-fit"><i class="fa fa-check"></i><b>12.5</b> An alternative fit<span></span></a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="resistant-line.html"><a href="resistant-line.html"><i class="fa fa-check"></i><b>13</b> Resistant Line<span></span></a>
<ul>
<li class="chapter" data-level="13.1" data-path="resistant-line.html"><a href="resistant-line.html#meet-the-data-3"><i class="fa fa-check"></i><b>13.1</b> Meet the data<span></span></a></li>
<li class="chapter" data-level="13.2" data-path="resistant-line.html"><a href="resistant-line.html#three-summary-points"><i class="fa fa-check"></i><b>13.2</b> Three summary points<span></span></a></li>
<li class="chapter" data-level="13.3" data-path="resistant-line.html"><a href="resistant-line.html#fitting-a-line-to-three-points"><i class="fa fa-check"></i><b>13.3</b> Fitting a line to three points<span></span></a></li>
<li class="chapter" data-level="13.4" data-path="resistant-line.html"><a href="resistant-line.html#improving-the-line-by-fitting-a-line-to-the-residuals"><i class="fa fa-check"></i><b>13.4</b> Improving the line by fitting a line to the residuals<span></span></a></li>
<li class="chapter" data-level="13.5" data-path="resistant-line.html"><a href="resistant-line.html#comparison-with-a-least-squares-fit"><i class="fa fa-check"></i><b>13.5</b> Comparison with a Least-Squares Fit<span></span></a></li>
<li class="chapter" data-level="13.6" data-path="resistant-line.html"><a href="resistant-line.html#interpreting-the-fit"><i class="fa fa-check"></i><b>13.6</b> Interpreting the fit<span></span></a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="plotting-ii.html"><a href="plotting-ii.html"><i class="fa fa-check"></i><b>14</b> Plotting II<span></span></a>
<ul>
<li class="chapter" data-level="14.1" data-path="plotting-ii.html"><a href="plotting-ii.html#fitting-a-line-to-the-population-in-the-later-years"><i class="fa fa-check"></i><b>14.1</b> Fitting a line to the population in the later years<span></span></a></li>
<li class="chapter" data-level="14.2" data-path="plotting-ii.html"><a href="plotting-ii.html#fitting-a-line-to-the-log-population-in-the-early-years"><i class="fa fa-check"></i><b>14.2</b> Fitting a line to the log population in the early years<span></span></a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="straightening.html"><a href="straightening.html"><i class="fa fa-check"></i><b>15</b> Straightening<span></span></a>
<ul>
<li class="chapter" data-level="15.1" data-path="straightening.html"><a href="straightening.html#meet-the-data-4"><i class="fa fa-check"></i><b>15.1</b> Meet the data<span></span></a></li>
<li class="chapter" data-level="15.2" data-path="straightening.html"><a href="straightening.html#a-nonlinear-relationship"><i class="fa fa-check"></i><b>15.2</b> A nonlinear relationship<span></span></a></li>
<li class="chapter" data-level="15.3" data-path="straightening.html"><a href="straightening.html#three-summary-points-and-measuring-curvature"><i class="fa fa-check"></i><b>15.3</b> Three summary points and measuring curvature<span></span></a></li>
<li class="chapter" data-level="15.4" data-path="straightening.html"><a href="straightening.html#reexpressing-to-reduce-curvature"><i class="fa fa-check"></i><b>15.4</b> Reexpressing to reduce curvature<span></span></a></li>
<li class="chapter" data-level="15.5" data-path="straightening.html"><a href="straightening.html#straightening-in-the-example"><i class="fa fa-check"></i><b>15.5</b> Straightening in the example<span></span></a></li>
<li class="chapter" data-level="15.6" data-path="straightening.html"><a href="straightening.html#making-sense-of-the-reexpression"><i class="fa fa-check"></i><b>15.6</b> Making sense of the reexpression<span></span></a></li>
<li class="chapter" data-level="15.7" data-path="straightening.html"><a href="straightening.html#straightening-fitting-and-flattening"><i class="fa fa-check"></i><b>15.7</b> Straightening, fitting, and flattening<span></span></a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="smoothing.html"><a href="smoothing.html"><i class="fa fa-check"></i><b>16</b> Smoothing<span></span></a>
<ul>
<li class="chapter" data-level="16.1" data-path="smoothing.html"><a href="smoothing.html#meet-the-data-5"><i class="fa fa-check"></i><b>16.1</b> Meet the data<span></span></a></li>
<li class="chapter" data-level="16.2" data-path="smoothing.html"><a href="smoothing.html#we-need-to-smooth"><i class="fa fa-check"></i><b>16.2</b> We need to smooth<span></span></a></li>
<li class="chapter" data-level="16.3" data-path="smoothing.html"><a href="smoothing.html#running-medians"><i class="fa fa-check"></i><b>16.3</b> Running medians<span></span></a></li>
<li class="chapter" data-level="16.4" data-path="smoothing.html"><a href="smoothing.html#end-value-smoothing"><i class="fa fa-check"></i><b>16.4</b> End-value smoothing<span></span></a></li>
<li class="chapter" data-level="16.5" data-path="smoothing.html"><a href="smoothing.html#splitting"><i class="fa fa-check"></i><b>16.5</b> Splitting<span></span></a></li>
<li class="chapter" data-level="16.6" data-path="smoothing.html"><a href="smoothing.html#hanning"><i class="fa fa-check"></i><b>16.6</b> Hanning<span></span></a></li>
<li class="chapter" data-level="16.7" data-path="smoothing.html"><a href="smoothing.html#the-smooth-and-the-rough"><i class="fa fa-check"></i><b>16.7</b> The smooth and the rough<span></span></a></li>
<li class="chapter" data-level="16.8" data-path="smoothing.html"><a href="smoothing.html#reroughing"><i class="fa fa-check"></i><b>16.8</b> Reroughing<span></span></a></li>
<li class="chapter" data-level="16.9" data-path="smoothing.html"><a href="smoothing.html#interpreting-the-final-smooth-and-rough"><i class="fa fa-check"></i><b>16.9</b> Interpreting the final smooth and rough<span></span></a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="median-polish.html"><a href="median-polish.html"><i class="fa fa-check"></i><b>17</b> Median Polish<span></span></a>
<ul>
<li class="chapter" data-level="17.1" data-path="median-polish.html"><a href="median-polish.html#meet-the-data-6"><i class="fa fa-check"></i><b>17.1</b> Meet the data<span></span></a></li>
<li class="chapter" data-level="17.2" data-path="median-polish.html"><a href="median-polish.html#an-additive-model"><i class="fa fa-check"></i><b>17.2</b> An additive model<span></span></a></li>
<li class="chapter" data-level="17.3" data-path="median-polish.html"><a href="median-polish.html#median-polish-1"><i class="fa fa-check"></i><b>17.3</b> Median polish<span></span></a></li>
<li class="chapter" data-level="17.4" data-path="median-polish.html"><a href="median-polish.html#interpreting-the-additive-model"><i class="fa fa-check"></i><b>17.4</b> Interpreting the additive model<span></span></a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="median-polish.html"><a href="median-polish.html#interpreting-the-row-and-column-effects"><i class="fa fa-check"></i><b>17.4.1</b> Interpreting the row and column effects<span></span></a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="median-polish.html"><a href="median-polish.html#looking-at-the-residuals-1"><i class="fa fa-check"></i><b>17.5</b> Looking at the residuals<span></span></a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="plotting-an-additive-plot.html"><a href="plotting-an-additive-plot.html"><i class="fa fa-check"></i><b>18</b> Plotting an Additive Plot<span></span></a>
<ul>
<li class="chapter" data-level="18.1" data-path="plotting-an-additive-plot.html"><a href="plotting-an-additive-plot.html#the-data-1"><i class="fa fa-check"></i><b>18.1</b> The data<span></span></a></li>
<li class="chapter" data-level="18.2" data-path="plotting-an-additive-plot.html"><a href="plotting-an-additive-plot.html#plotting-the-two-terms-of-the-additive-fit"><i class="fa fa-check"></i><b>18.2</b> Plotting the two terms of the additive fit<span></span></a></li>
<li class="chapter" data-level="18.3" data-path="plotting-an-additive-plot.html"><a href="plotting-an-additive-plot.html#making-sense-of-the-display"><i class="fa fa-check"></i><b>18.3</b> Making sense of the display<span></span></a></li>
<li class="chapter" data-level="18.4" data-path="plotting-an-additive-plot.html"><a href="plotting-an-additive-plot.html#adding-information-about-the-residuals-to-the-display"><i class="fa fa-check"></i><b>18.4</b> Adding information about the residuals to the display<span></span></a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="multiplicative-fit.html"><a href="multiplicative-fit.html"><i class="fa fa-check"></i><b>19</b> Multiplicative Fit<span></span></a>
<ul>
<li class="chapter" data-level="19.1" data-path="multiplicative-fit.html"><a href="multiplicative-fit.html#meet-the-data-7"><i class="fa fa-check"></i><b>19.1</b> Meet the data<span></span></a></li>
<li class="chapter" data-level="19.2" data-path="multiplicative-fit.html"><a href="multiplicative-fit.html#an-additive-model-isnt-suitable"><i class="fa fa-check"></i><b>19.2</b> An additive model isn’t suitable<span></span></a></li>
<li class="chapter" data-level="19.3" data-path="multiplicative-fit.html"><a href="multiplicative-fit.html#fitting-our-model-to-the-data"><i class="fa fa-check"></i><b>19.3</b> Fitting our model to the data<span></span></a></li>
<li class="chapter" data-level="19.4" data-path="multiplicative-fit.html"><a href="multiplicative-fit.html#interpreting-the-fit-1"><i class="fa fa-check"></i><b>19.4</b> Interpreting the fit<span></span></a></li>
<li class="chapter" data-level="19.5" data-path="multiplicative-fit.html"><a href="multiplicative-fit.html#interpreting-the-residuals"><i class="fa fa-check"></i><b>19.5</b> Interpreting the residuals<span></span></a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="extended-fit.html"><a href="extended-fit.html"><i class="fa fa-check"></i><b>20</b> Extended Fit<span></span></a>
<ul>
<li class="chapter" data-level="20.1" data-path="extended-fit.html"><a href="extended-fit.html#meet-the-data-8"><i class="fa fa-check"></i><b>20.1</b> Meet the data<span></span></a></li>
<li class="chapter" data-level="20.2" data-path="extended-fit.html"><a href="extended-fit.html#an-additive-fit"><i class="fa fa-check"></i><b>20.2</b> An additive fit<span></span></a></li>
<li class="chapter" data-level="20.3" data-path="extended-fit.html"><a href="extended-fit.html#looking-at-the-residuals-2"><i class="fa fa-check"></i><b>20.3</b> Looking at the residuals<span></span></a></li>
<li class="chapter" data-level="20.4" data-path="extended-fit.html"><a href="extended-fit.html#comparison-values"><i class="fa fa-check"></i><b>20.4</b> Comparison values<span></span></a></li>
<li class="chapter" data-level="20.5" data-path="extended-fit.html"><a href="extended-fit.html#extending-the-additive-model-by-one-more-term"><i class="fa fa-check"></i><b>20.5</b> Extending the additive model by one more term<span></span></a></li>
<li class="chapter" data-level="20.6" data-path="extended-fit.html"><a href="extended-fit.html#finding-k"><i class="fa fa-check"></i><b>20.6</b> Finding k<span></span></a></li>
<li class="chapter" data-level="20.7" data-path="extended-fit.html"><a href="extended-fit.html#relationship-with-multiplicative-fit"><i class="fa fa-check"></i><b>20.7</b> Relationship with multiplicative fit<span></span></a></li>
<li class="chapter" data-level="20.8" data-path="extended-fit.html"><a href="extended-fit.html#extended-fits-and-transformations"><i class="fa fa-check"></i><b>20.8</b> Extended fits and transformations<span></span></a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="binned-data.html"><a href="binned-data.html"><i class="fa fa-check"></i><b>21</b> Binned Data<span></span></a>
<ul>
<li class="chapter" data-level="21.1" data-path="binned-data.html"><a href="binned-data.html#meet-the-data-9"><i class="fa fa-check"></i><b>21.1</b> Meet the data<span></span></a></li>
<li class="chapter" data-level="21.2" data-path="binned-data.html"><a href="binned-data.html#constructing-a-histogram"><i class="fa fa-check"></i><b>21.2</b> Constructing a histogram<span></span></a></li>
<li class="chapter" data-level="21.3" data-path="binned-data.html"><a href="binned-data.html#a-rootogram"><i class="fa fa-check"></i><b>21.3</b> A rootogram<span></span></a></li>
<li class="chapter" data-level="21.4" data-path="binned-data.html"><a href="binned-data.html#fitting-a-gaussian-comparison-curve"><i class="fa fa-check"></i><b>21.4</b> Fitting a Gaussian comparison curve<span></span></a></li>
<li class="chapter" data-level="21.5" data-path="binned-data.html"><a href="binned-data.html#residuals"><i class="fa fa-check"></i><b>21.5</b> Residuals<span></span></a></li>
<li class="chapter" data-level="21.6" data-path="binned-data.html"><a href="binned-data.html#hanging-rootogram"><i class="fa fa-check"></i><b>21.6</b> Hanging rootogram<span></span></a></li>
<li class="chapter" data-level="21.7" data-path="binned-data.html"><a href="binned-data.html#interpreting-the-residuals-1"><i class="fa fa-check"></i><b>21.7</b> Interpreting the residuals<span></span></a></li>
<li class="chapter" data-level="21.8" data-path="binned-data.html"><a href="binned-data.html#other-definitions-of-residuals-double-root-residuals"><i class="fa fa-check"></i><b>21.8</b> Other definitions of residuals (Double Root Residuals)<span></span></a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="binned-data-ii.html"><a href="binned-data-ii.html"><i class="fa fa-check"></i><b>22</b> Binned Data II<span></span></a>
<ul>
<li class="chapter" data-level="22.1" data-path="binned-data-ii.html"><a href="binned-data-ii.html#introduction-1"><i class="fa fa-check"></i><b>22.1</b> Introduction<span></span></a></li>
<li class="chapter" data-level="22.2" data-path="binned-data-ii.html"><a href="binned-data-ii.html#meet-a-simulated-but-famous-dataset"><i class="fa fa-check"></i><b>22.2</b> Meet a simulated, but famous, dataset<span></span></a></li>
<li class="chapter" data-level="22.3" data-path="binned-data-ii.html"><a href="binned-data-ii.html#smoothing-the-root-counts"><i class="fa fa-check"></i><b>22.3</b> Smoothing the root counts<span></span></a></li>
<li class="chapter" data-level="22.4" data-path="binned-data-ii.html"><a href="binned-data-ii.html#fitting-a-symmetric-curve"><i class="fa fa-check"></i><b>22.4</b> Fitting a symmetric curve<span></span></a></li>
<li class="chapter" data-level="22.5" data-path="binned-data-ii.html"><a href="binned-data-ii.html#is-it-a-reasonable-fit"><i class="fa fa-check"></i><b>22.5</b> Is it a reasonable fit?<span></span></a></li>
<li class="chapter" data-level="22.6" data-path="binned-data-ii.html"><a href="binned-data-ii.html#the-famous-brewer"><i class="fa fa-check"></i><b>22.6</b> The famous brewer<span></span></a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="fraction-data.html"><a href="fraction-data.html"><i class="fa fa-check"></i><b>23</b> Fraction Data<span></span></a>
<ul>
<li class="chapter" data-level="23.1" data-path="fraction-data.html"><a href="fraction-data.html#the-quality-of-students-at-bgsu"><i class="fa fa-check"></i><b>23.1</b> The Quality of Students at BGSU<span></span></a></li>
<li class="chapter" data-level="23.2" data-path="fraction-data.html"><a href="fraction-data.html#meet-the-data-10"><i class="fa fa-check"></i><b>23.2</b> Meet the Data<span></span></a></li>
<li class="chapter" data-level="23.3" data-path="fraction-data.html"><a href="fraction-data.html#counted-fractions"><i class="fa fa-check"></i><b>23.3</b> Counted Fractions<span></span></a></li>
<li class="chapter" data-level="23.4" data-path="fraction-data.html"><a href="fraction-data.html#started-counts-and-split-counts"><i class="fa fa-check"></i><b>23.4</b> Started Counts and Split Counts<span></span></a></li>
<li class="chapter" data-level="23.5" data-path="fraction-data.html"><a href="fraction-data.html#three-matched-scales-for-counted-fractions-folded-fractions-roots-and-logs"><i class="fa fa-check"></i><b>23.5</b> Three Matched Scales for Counted Fractions (folded fractions, roots, and logs)<span></span></a></li>
<li class="chapter" data-level="23.6" data-path="fraction-data.html"><a href="fraction-data.html#an-example-illustrating-the-benefits-of-reexpressing-fractions"><i class="fa fa-check"></i><b>23.6</b> An Example Illustrating the Benefits of Reexpressing Fractions<span></span></a></li>
<li class="chapter" data-level="23.7" data-path="fraction-data.html"><a href="fraction-data.html#a-tukey-example-where-careful-reexpression-pays-off"><i class="fa fa-check"></i><b>23.7</b> A Tukey Example Where Careful Reexpression Pays Off<span></span></a></li>
<li class="chapter" data-level="23.8" data-path="fraction-data.html"><a href="fraction-data.html#back-to-the-data-an-analysis-based-on-flogs"><i class="fa fa-check"></i><b>23.8</b> Back to the Data – An Analysis Based on Flogs<span></span></a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Course in Exploratory Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="fraction-data" class="section level1 hasAnchor" number="23">
<h1><span class="header-section-number">23</span> Fraction Data<a href="fraction-data.html#fraction-data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="the-quality-of-students-at-bgsu" class="section level2 hasAnchor" number="23.1">
<h2><span class="header-section-number">23.1</span> The Quality of Students at BGSU<a href="fraction-data.html#the-quality-of-students-at-bgsu" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A general concern among faculty at BGSU is the quality of the incoming undergraduate freshmen class. Is the university admitting more students of questionable ability? If so, this has a great effect on the performance of the students that take precalculus mathematics in the department. Weak students generally don’t do well in their precalculus or introductory statistics classes.</p>
<p>Back in 1991, the Office of the President was preparing some data to show the university community how much the university had advanced in the nine years between the academic years 1981-1982 and 1990-1991. One statistic that they considered was the
“Percentage of Freshmen in the Bottom 50% of High School Graduating Class”</p>
<p>At first glance, one might wonder why they consider the percentage of students in the bottom 50% of their class – wouldn’t it be clearer to consider the percentage of students in the top 50% of their class?</p>
<p>Anyway, the data sheet shows the following:</p>
<table>
<thead>
<tr class="header">
<th>–</th>
<th>1981-1982</th>
<th>1990-1991</th>
<th>% Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Percentage of Freshmen</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>in the Bottom 50% of High</td>
<td>9.4 %</td>
<td>6.9 %</td>
<td>(26.6 %)</td>
</tr>
<tr class="odd">
<td>School Graduating Class</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>This is supposed to impress you – the percentage of students in the bottom half of their high school class decreased by 26.6 % in the nine-year period.</p>
<p>But what if we considered instead the percentage of students in the top half of the class – we get the following table:</p>
<table>
<thead>
<tr class="header">
<th>–</th>
<th>1981-1982</th>
<th>1990-1991</th>
<th>% Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Percentage of Freshmen</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>in the Top 50% of High</td>
<td>90.6 %</td>
<td>93.1 %</td>
<td>2.8 %</td>
</tr>
<tr class="odd">
<td>School Graduating Class</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>We see that the percentage of freshmen in the top half increased by 2.8 %. This doesn’t sound that impressive, so I think I know now why the President’s Office decided to consider the percentage in the bottom half.</p>
<p>But wait – it shouldn’t matter if we consider the percentage of freshmen in the top half or the percentage in the bottom half. Why should our measure of change depend on this arbitrary definition?</p>
<p>In this lecture, we’ll talk about accurate and effective ways of comparing proportions. This type of data suffers from the “change in variability” problem that we saw earlier in our comparison of batches and deserves an appropriate reexpression.</p>
</div>
<div id="meet-the-data-10" class="section level2 hasAnchor" number="23.2">
<h2><span class="header-section-number">23.2</span> Meet the Data<a href="fraction-data.html#meet-the-data-10" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The Office of Undergraduate Admissions collects data on the high school ranks of regularly admitted undergraduate students. Using the admissions data, the Office of Institutional Research has the following table that shows the number and % of students in different high school ranks for the past five years.</p>
<table>
<colgroup>
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
</colgroup>
<thead>
<tr class="header">
<th>–</th>
<th>1996</th>
<th></th>
<th>1997</th>
<th></th>
<th>1998</th>
<th></th>
<th>1999</th>
<th></th>
<th>2000</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HS Rank</td>
<td>N</td>
<td>%</td>
<td>N</td>
<td>%</td>
<td>N</td>
<td>%</td>
<td>N</td>
<td>%</td>
<td>N</td>
<td>%</td>
</tr>
<tr class="even">
<td>90% - 100%</td>
<td>321</td>
<td>13.3</td>
<td>345</td>
<td>14.2</td>
<td>390</td>
<td>13.0</td>
<td>373</td>
<td>12.3</td>
<td>357</td>
<td>12.1</td>
</tr>
<tr class="odd">
<td>80%-89%</td>
<td>434</td>
<td>18</td>
<td>356</td>
<td>14.7</td>
<td>486</td>
<td>16.2</td>
<td>504</td>
<td>16.6</td>
<td>430</td>
<td>14.6</td>
</tr>
<tr class="even">
<td>70%-79%</td>
<td>396</td>
<td>16.4</td>
<td>387</td>
<td>15.9</td>
<td>482</td>
<td>16.0</td>
<td>478</td>
<td>15.7</td>
<td>459</td>
<td>15.6</td>
</tr>
<tr class="odd">
<td>60%-69%</td>
<td>395</td>
<td>16.4</td>
<td>393</td>
<td>16.2</td>
<td>485</td>
<td>16.1</td>
<td>518</td>
<td>17.0</td>
<td>470</td>
<td>16.0</td>
</tr>
<tr class="even">
<td>50%-59%</td>
<td>377</td>
<td>15.6</td>
<td>366</td>
<td>15.1</td>
<td>458</td>
<td>15.2</td>
<td>439</td>
<td>14.4</td>
<td>490</td>
<td>16.7</td>
</tr>
<tr class="odd">
<td>Below 50%</td>
<td>493</td>
<td>20.4</td>
<td>581</td>
<td>23.9</td>
<td>704</td>
<td>23.4</td>
<td>727</td>
<td>23.9</td>
<td>736</td>
<td>25.0</td>
</tr>
<tr class="even">
<td>Total</td>
<td>2416</td>
<td>100</td>
<td>2428</td>
<td>100</td>
<td>3005</td>
<td>100</td>
<td>3039</td>
<td>100</td>
<td>2942</td>
<td>100</td>
</tr>
</tbody>
</table>
<p>We will focus here on the table of percentages.</p>
<table>
<thead>
<tr class="header">
<th>HS Rank</th>
<th>1996</th>
<th>1997</th>
<th>1998</th>
<th>1999</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90% - 100%</td>
<td>13.3</td>
<td>14.2</td>
<td>13.0</td>
<td>12.3</td>
</tr>
<tr class="even">
<td>80%-89%</td>
<td>18</td>
<td>14.7</td>
<td>16.2</td>
<td>16.6</td>
</tr>
<tr class="odd">
<td>70%-79%</td>
<td>16.4</td>
<td>15.9</td>
<td>16.0</td>
<td>15.7</td>
</tr>
<tr class="even">
<td>60%-69%</td>
<td>16.4</td>
<td>16.2</td>
<td>16.1</td>
<td>17.0</td>
</tr>
<tr class="odd">
<td>50%-59%</td>
<td>15.6</td>
<td>15.1</td>
<td>15.2</td>
<td>14.4</td>
</tr>
<tr class="even">
<td>Below 50%</td>
<td>20.4</td>
<td>23.9</td>
<td>23.4</td>
<td>23.9</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>100</td>
<td>100</td>
<td>100</td>
<td>100</td>
</tr>
</tbody>
</table>
<p>The objective here is to get an overall sense how the percentages are changing over the 5-year period. Certain low and high percentages might attract our eye (the 25.0% of students in the bottom half of the HS class in 2000 certainly seems high), but that’s just an isolated value and may not reflect the general pattern of change across years.</p>
</div>
<div id="counted-fractions" class="section level2 hasAnchor" number="23.3">
<h2><span class="header-section-number">23.3</span> Counted Fractions<a href="fraction-data.html#counted-fractions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To start off, how do we obtain data that is a fraction? This fraction is found by taking a COUNT and dividing by a total number. So
<span class="math display">\[
FRACTION = \frac{COUNT}{TOTAL}.
\]</span>
We call these data counted fractions, since the numerator of the fraction is some type of count.</p>
<p>In many cases, we create these counts by cutting continuous data. Our data is this type. A student’s high school rank is a percentage between 0 and 100, and we are cutting this in different places (90, 80, and so on) to get the fractions in the above table.</p>
</div>
<div id="started-counts-and-split-counts" class="section level2 hasAnchor" number="23.4">
<h2><span class="header-section-number">23.4</span> Started Counts and Split Counts<a href="fraction-data.html#started-counts-and-split-counts" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Suppose that we sampled 20 students and all of them were in the bottom 90% of their high school class. So the fraction of students in the top 10% of their class is
<span class="math display">\[
\frac{0}{20} = 0.
\]</span>
This answer is a bit unsatisfactory, since we know that if we kept on sampling, we would find some students in the top 10% of their class. So we want to adjust our numerator in our fraction for the possibility that some would fall in this class. We adjust the counts of “in the top 10%” and “not in the top 10%” (that is, the two classifications), by adding 1/6 to each type. Then the fraction of students in the top 10% would be
<span class="math display">\[
\frac{0 + 1/6}{20 + 1/3}.
\]</span></p>
<p>We call (0 + 1/6) a started count, and so the corresponding fraction is a started fraction.</p>
<p>Another issue is that, when we cut continuous data to get our counts, it is possible that some observations will fall on the fence. Since it makes sense to treat the two classes (those in the class and those not in the class) symmetrically, we add half of the counts on the fence to one class and the remaining half of the count to the other class.</p>
<p>Tukey defines the new count
<span class="math display">\[
{\rm ss-count \, below} = {\rm count \, below} + \frac{1}{2} ({\rm count \, equal}) + \frac{1}{6}
\]</span>
That is, we add three quantities:
- the count below the boundary
- one half of the count that falls on the boundary (we call this the split count)
- 1/6 (the started count)
and the corresponding fraction is given by
<span class="math display">\[
{\rm ss-fraction \, below} = \frac{{\rm ss-count \,below}}
{{\rm total \, count} +1/3}.
\]</span>
We won’t say any more about starting and split counts here since they won’t be needed for our example.</p>
</div>
<div id="three-matched-scales-for-counted-fractions-folded-fractions-roots-and-logs" class="section level2 hasAnchor" number="23.5">
<h2><span class="header-section-number">23.5</span> Three Matched Scales for Counted Fractions (folded fractions, roots, and logs)<a href="fraction-data.html#three-matched-scales-for-counted-fractions-folded-fractions-roots-and-logs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The main issue that we want to address is how to properly express fractions. Fraction data are hard to analyze for several reasons:</p>
<ul>
<li>People aren’t sure if they should work with the “fraction that is” or the “fraction that isn’t”. In the Office of the President example above, the person who made the table thought that there was some advantage to working with the fraction of students in the lower half of their class instead of the fraction of students in the top talk.</li>
<li>Small fractions near 0, and large fractions near 1 have small variation, and fractions close to .5 have large variation. We all know that the standard error of a sample proportion is</li>
</ul>
<p>This standard error is 0 when the fraction f is 0 or 1, and is maximized when f is equal to .5.</p>
<p>If we reexpress a fraction, what properties would we like of the reexpressed fraction?</p>
<ul>
<li>We would like to treat “those who are” and “whose who aren’t” in a symmetric fashion.</li>
<li>Since <span class="math inline">\(f = .5\)</span> is a central fraction value, it would be desirable if our reexpressed fraction is equal to 0 when the fraction is equal to .5.</li>
<li>If we swap a fraction <span class="math inline">\(f\)</span> with the fraction <span class="math inline">\(1-f\)</span>, the reexpressed fraction will change in size but the size of the fraction won’t change.</li>
</ul>
<p>The simplest reexpression that has these properties is the folded fraction, which we abbreviate by ff:
<span class="math display">\[
ff = f - (1-f).
\]</span></p>
<p>The table below gives some folded fractions for values of the fraction f.</p>
<table>
<thead>
<tr class="header">
<th>f</th>
<th>.05</th>
<th>.1</th>
<th>.3</th>
<th>.5</th>
<th>.7</th>
<th>.9</th>
<th>.95</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ff</td>
<td>-.9</td>
<td>-.8</td>
<td>-.4</td>
<td>0</td>
<td>.4</td>
<td>.8</td>
<td>.9</td>
</tr>
</tbody>
</table>
<p>Note that <span class="math inline">\(ff\)</span> satisfies our basic properties. The folded fraction for <span class="math inline">\(f = .1\)</span> is <span class="math inline">\(ff = -.8\)</span>; if we replace <span class="math inline">\(f = .1\)</span> by <span class="math inline">\(f = .9\)</span>, the value of <span class="math inline">\(ff\)</span> is changed from -8 to +.8, but the size of ff doesn’t change. A folded fraction <span class="math inline">\(ff = 0\)</span> corresponds to a fraction <span class="math inline">\(f = .5\)</span>.</p>
<p>We can obtain alternative folded reexpressions by taking the fractions <span class="math inline">\(f, 1-f\)</span> to the <span class="math inline">\(p\)</span>th power and then folding:
<span class="math display">\[
f^p - (1-f)^p.
\]</span></p>
<p>If we use a <span class="math inline">\(p = \frac{1}{2}\)</span> power, we get a folded root, or froot
<span class="math display">\[
f^{1/2} - (1-f)^{1/2}.
\]</span></p>
<p>If we use a p = 0 (one more half-step), we get a folded log, or flog
<span class="math display">\[
log(f) - log(1-f).
\]</span>
All three rexpressions (<span class="math inline">\(ff\)</span>, <span class="math inline">\(froot\)</span>, <span class="math inline">\(flog\)</span>) are equal to 0 when <span class="math inline">\(f\)</span> = .5. Also if you replace <span class="math inline">\(f\)</span> by <span class="math inline">\(1-f\)</span>, then the measure will change in sign.</p>
<p>To compare these reexpressions, we slightly modify the definitions of <span class="math inline">\(froot\)</span> and <span class="math inline">\(flog\)</span> so that they are matched with the folded fractions:
<span class="math display">\[
froot = (2 f)^{1/2} - (2 (1 - f))^{1/2}
\]</span>
<span class="math display">\[
flog = 1.15 log(f) - 1.15 log(1-f)
\]</span></p>
<p>The table below displays values of the reexpressions for some values of the fraction <span class="math inline">\(f\)</span>. The figure below graphs values of these three reexpressions.</p>
<table>
<thead>
<tr class="header">
<th>f</th>
<th>.05</th>
<th>.1</th>
<th>.3</th>
<th>.5</th>
<th>.7</th>
<th>.9</th>
<th>.95</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ff</td>
<td>-.9</td>
<td>-.8</td>
<td>-.4</td>
<td>0</td>
<td>.4</td>
<td>.8</td>
<td>.9</td>
</tr>
<tr class="even">
<td>froot</td>
<td>-1.06</td>
<td>-.89</td>
<td>-.41</td>
<td>0</td>
<td>.41</td>
<td>.89</td>
<td>1.06</td>
</tr>
<tr class="odd">
<td>flog</td>
<td>-1.47</td>
<td>-1.10</td>
<td>-.42</td>
<td>0</td>
<td>.42</td>
<td>1.10</td>
<td>1.47</td>
</tr>
</tbody>
</table>
<p><img src="Course-in-Exploratory-Data-Analysis_files/figure-html/unnamed-chunk-171-1.png" width="672" /></p>
<p>The folded fraction <span class="math inline">\(ff\)</span> is just a linear transformation of <span class="math inline">\(f\)</span> that changes the support from (0, 1) to (-1, 1). Due to the matching, note that <span class="math inline">\(ff\)</span>, <span class="math inline">\(froot\)</span> and <span class="math inline">\(flog\)</span> agree closely for values of <span class="math inline">\(f\)</span> between .3 and .7. The differences are primarily how the reexpressions handle extreme values of <span class="math inline">\(f\)</span> near 0 and 1. By taking the root and log, the <span class="math inline">\(froots\)</span> and <span class="math inline">\(flogs\)</span> stretch the scale for these extreme values. By stretching values of <span class="math inline">\(f\)</span> near 0 and 1, this reexpression is adjusting for the small spread in fraction values that are close to 0 or 1.</p>
<p>Here is another graph – we are plotting the three rexpressions (<span class="math inline">\(ff, froot, flog\)</span>) against the fraction <span class="math inline">\(f\)</span>. This again illustrates the stretching effect of the <span class="math inline">\(froot\)</span> and <span class="math inline">\(flog\)</span> reexpressions.</p>
<p><img src="Course-in-Exploratory-Data-Analysis_files/figure-html/unnamed-chunk-172-1.png" width="672" /></p>
</div>
<div id="an-example-illustrating-the-benefits-of-reexpressing-fractions" class="section level2 hasAnchor" number="23.6">
<h2><span class="header-section-number">23.6</span> An Example Illustrating the Benefits of Reexpressing Fractions<a href="fraction-data.html#an-example-illustrating-the-benefits-of-reexpressing-fractions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The dataset <code>college.ratings</code> contains a number of different measurements of a group of national universities in the United States based on a 2001 survey.
One of the interesting variables is the fraction <code>Top.10</code>, the proportion of students enrolled who were in the top 10 percent of their high school class. The variable <code>Tier</code> with four levels provides a general classification of the universities – the <code>Tier 1</code> schools are the top-rated schools, followed by the <code>Tier 2</code> schools, the <code>Tier 3</code> schools, and the <code>Tier 4</code> schools. We are interested how the <code>Top.10</code> variable varies between tiers, and if there is any advantage to reexpressing the fraction <code>Top.10</code> to a different scale.</p>
<p>Using the <code>geom_boxplot()</code> function, we construct parallel boxplots of the Top 10 variable across tier.</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="fraction-data.html#cb326-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(LearnEDAfunctions)</span>
<span id="cb326-2"><a href="fraction-data.html#cb326-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(college.ratings,</span>
<span id="cb326-3"><a href="fraction-data.html#cb326-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="fu">factor</span>(Tier), Top<span class="fl">.10</span>)) <span class="sc">+</span></span>
<span id="cb326-4"><a href="fraction-data.html#cb326-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">coord_flip</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Tier&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 28 rows containing non-finite values
## (stat_boxplot).</code></pre>
<p><img src="Course-in-Exploratory-Data-Analysis_files/figure-html/unnamed-chunk-173-1.png" width="672" /></p>
<p>It is difficult to compare these Top 10 rates due to the difference in variability across tiers. If we focus on the fourth-spreads (or interquartile ranges) the Tier 1 and Tier 2 rates have the small variation, followed by Tier 3 and Tier 4. Using the <code>summarize</code> function in the <code>dplyr</code> package, we compare the interquartile range of <code>Top.10</code> for each tier.</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="fraction-data.html#cb328-1" aria-hidden="true" tabindex="-1"></a>college.ratings <span class="sc">%&gt;%</span> </span>
<span id="cb328-2"><a href="fraction-data.html#cb328-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Tier) <span class="sc">%&gt;%</span> </span>
<span id="cb328-3"><a href="fraction-data.html#cb328-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">IQR =</span> <span class="fu">IQR</span>(Top<span class="fl">.10</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 2
##    Tier    IQR
##   &lt;int&gt;  &lt;dbl&gt;
## 1     1 0.235 
## 2     2 0.155 
## 3     3 0.09  
## 4     4 0.0925</code></pre>
<p>If we focus on comparisons of tiers 2, 3, 4, we see that the spread of the Tier 2 values (0.155) is about 1.7 times larger than the spread of the Tier 3 values (0.090).</p>
<p>Next, let’s see the effect of transformating the top 10 variable to the <span class="math inline">\(froot\)</span> and <span class="math inline">\(flog\)</span> scales. We write short functions defining these functions, and then show boxplots using these two scales.</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="fraction-data.html#cb330-1" aria-hidden="true" tabindex="-1"></a>froot <span class="ot">&lt;-</span> <span class="cf">function</span>(p) <span class="fu">sqrt</span>(p) <span class="sc">-</span> <span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">-</span> p)</span>
<span id="cb330-2"><a href="fraction-data.html#cb330-2" aria-hidden="true" tabindex="-1"></a>flog <span class="ot">&lt;-</span> <span class="cf">function</span>(p) <span class="fu">log</span>(p) <span class="sc">-</span> <span class="fu">log</span>(<span class="dv">1</span> <span class="sc">-</span> p)</span></code></pre></div>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="fraction-data.html#cb331-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(college.ratings,</span>
<span id="cb331-2"><a href="fraction-data.html#cb331-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="fu">factor</span>(Tier), <span class="fu">froot</span>(Top<span class="fl">.10</span>))) <span class="sc">+</span></span>
<span id="cb331-3"><a href="fraction-data.html#cb331-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb331-4"><a href="fraction-data.html#cb331-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Froot(Top 10)&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Tier&quot;</span>)</span></code></pre></div>
<p><img src="Course-in-Exploratory-Data-Analysis_files/figure-html/unnamed-chunk-176-1.png" width="672" /></p>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="fraction-data.html#cb332-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(college.ratings,</span>
<span id="cb332-2"><a href="fraction-data.html#cb332-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="fu">factor</span>(Tier), <span class="fu">flog</span>(Top<span class="fl">.10</span>))) <span class="sc">+</span></span>
<span id="cb332-3"><a href="fraction-data.html#cb332-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb332-4"><a href="fraction-data.html#cb332-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Flog(Top 10)&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Tier&quot;</span>)</span></code></pre></div>
<p><img src="Course-in-Exploratory-Data-Analysis_files/figure-html/unnamed-chunk-177-1.png" width="672" /></p>
<p>Have these reexpressions helped in equalizing spread? We compute the IQRs of the groups using the <span class="math inline">\(froot\)</span> and <span class="math inline">\(flog\)</span> scales.</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="fraction-data.html#cb333-1" aria-hidden="true" tabindex="-1"></a>college.ratings <span class="sc">%&gt;%</span> </span>
<span id="cb333-2"><a href="fraction-data.html#cb333-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Tier) <span class="sc">%&gt;%</span> </span>
<span id="cb333-3"><a href="fraction-data.html#cb333-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">IQR_froot =</span> <span class="fu">IQR</span>(<span class="fu">froot</span>(Top<span class="fl">.10</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb333-4"><a href="fraction-data.html#cb333-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">IQR_flog =</span> <span class="fu">IQR</span>(<span class="fu">flog</span>(Top<span class="fl">.10</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##    Tier IQR_froot IQR_flog
##   &lt;int&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1     1     0.393    1.48 
## 2     2     0.231    0.717
## 3     3     0.148    0.540
## 4     4     0.173    0.763</code></pre>
<p>If we focus again on comparisons between tiers 2, 3, and 4, it appears that the <span class="math inline">\(flog\)</span> expression is best for equalizing spreads. If look at the ratio of the largest IQR to the smallest IQR, then we compute the ratio 1.56 for <span class="math inline">\(froot\)</span>s and <span class="math inline">\(1.41\)</span> for <span class="math inline">\(flog\)</span>s.</p>
<p>Since <span class="math inline">\(flog\)</span>s have approximately equalized spreads, we can make comparisons between the top 10 flog fractions between tiers 2, 3, and 4 by computing medians.</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="fraction-data.html#cb335-1" aria-hidden="true" tabindex="-1"></a>college.ratings <span class="sc">%&gt;%</span> </span>
<span id="cb335-2"><a href="fraction-data.html#cb335-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Tier) <span class="sc">%&gt;%</span> </span>
<span id="cb335-3"><a href="fraction-data.html#cb335-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">M_flog =</span> <span class="fu">median</span>(<span class="fu">flog</span>(Top<span class="fl">.10</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 2
##    Tier M_flog
##   &lt;int&gt;  &lt;dbl&gt;
## 1     1  1.39 
## 2     2 -0.800
## 3     3 -1.32 
## 4     4 -1.82</code></pre>
<p>On the <span class="math inline">\(flog\)</span> scale, the Tier 2 “top 10” fractions tend to be -0.80 - (-1.32) = 0.52 higher than the Tier 3 fractions. Similarly, on the flog scale, the Tier 3 “top 10” fractions tend to be -1.32 - (-1.82) = 0.50 higher than the Tier 4 fractions.</p>
</div>
<div id="a-tukey-example-where-careful-reexpression-pays-off" class="section level2 hasAnchor" number="23.7">
<h2><span class="header-section-number">23.7</span> A Tukey Example Where Careful Reexpression Pays Off<a href="fraction-data.html#a-tukey-example-where-careful-reexpression-pays-off" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Tukey’s EDA book has a great example that illustrates the benefit of reexpressing fractions. This table comes from a newspaper article – the Washington Post February 2, 1962 article titled “Protestants shifts support to Kennedy”. As you might or might not know, John Kennedy was the first Catholic to have a serious chance of being elected president and one suspected that the Catholics would be more behind Kennedy than Protestants in the election between Kennedy and Nixon. There were polls taken on the dates 11/60 and 1/62. Kennedy’s support increased from 38% to 59% among the Protestants, in contrast to the 11% change in support – 78% to 89% – among the Catholics. On the surface, it would appear that Kennedy’s support has increased more among the Protestants.</p>
<table>
<thead>
<tr class="header">
<th>–</th>
<th>Protestants</th>
<th>Protestants</th>
<th>Catholics</th>
<th>Catholics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Date</td>
<td>11/60</td>
<td>1/62</td>
<td>11/60</td>
<td>1/62</td>
</tr>
<tr class="even">
<td>Kennedy</td>
<td>38%</td>
<td>59%</td>
<td>78%</td>
<td>89%</td>
</tr>
<tr class="odd">
<td>Nixon</td>
<td>62%</td>
<td>41%</td>
<td>22%</td>
<td>11%</td>
</tr>
</tbody>
</table>
<p>But this conclusion is deceptive since there is smaller variation among the large fractions (in the 70-80% range) than among the middle-range fractions between 38-59%. Suppose that we reexpress to flogs. For example, we reexpress <span class="math inline">\(f\)</span> = .38 to <span class="math inline">\(flog = \log(.38)-\log(.62)\)</span>, and so on for all the fractions in the table.</p>
<table>
<thead>
<tr class="header">
<th>–</th>
<th>Protestants</th>
<th>Protestants</th>
<th>Catholics</th>
<th>Catholics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Date</td>
<td>11/60</td>
<td>1/62</td>
<td>11/60</td>
<td>1/62</td>
</tr>
<tr class="even">
<td>Kennedy</td>
<td>-0.24</td>
<td>0.18</td>
<td>0.63</td>
<td>1.05</td>
</tr>
</tbody>
</table>
<p>Now let’s look at the change in support in the <span class="math inline">\(flog\)</span> scale. The change in support (from 11/60 to 1/62) among the Protestants was <span class="math inline">\(.18 - (-.24) = .42\)</span> and the change in support among the Catholics was also 1.05 - .63 = 0.42. So, by adjusting for the variability problem in the fractions, we see that really Protestant and Catholic changes are similar. Our conclusion is that JFK’s popularity improved by 0.42 on <span class="math inline">\(flog\)</span> scale (for both Protestants and Catholics)</p>
</div>
<div id="back-to-the-data-an-analysis-based-on-flogs" class="section level2 hasAnchor" number="23.8">
<h2><span class="header-section-number">23.8</span> Back to the Data – An Analysis Based on Flogs<a href="fraction-data.html#back-to-the-data-an-analysis-based-on-flogs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s return to our BGSU admissions example. We are interested in looking at any possible trend in the HS rank data across years. Here is our data, where the numbers represent the percentages of students in the different HS Rank classes for a given year.</p>
<table>
<thead>
<tr class="header">
<th>HS Rank</th>
<th>1996</th>
<th>1997</th>
<th>1998</th>
<th>1999</th>
<th>2000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90% - 100%</td>
<td>13.3</td>
<td>14.2</td>
<td>13.0</td>
<td>12.3</td>
<td>12.1</td>
</tr>
<tr class="even">
<td>80%-89%</td>
<td>18</td>
<td>14.7</td>
<td>16.2</td>
<td>16.6</td>
<td>14.6</td>
</tr>
<tr class="odd">
<td>70%-79%</td>
<td>16.4</td>
<td>15.9</td>
<td>16.0</td>
<td>15.7</td>
<td>15.6</td>
</tr>
<tr class="even">
<td>60%-69%</td>
<td>16.4</td>
<td>16.2</td>
<td>16.1</td>
<td>17.0</td>
<td>16.0</td>
</tr>
<tr class="odd">
<td>50%-59%</td>
<td>15.6</td>
<td>15.1</td>
<td>15.2</td>
<td>14.4</td>
<td>16.7</td>
</tr>
<tr class="even">
<td>Below 50%</td>
<td>20.4</td>
<td>23.9</td>
<td>23.4</td>
<td>23.9</td>
<td>25.0</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>100</td>
<td>100</td>
<td>100</td>
<td>100</td>
<td>100</td>
</tr>
</tbody>
</table>
<p>What we will do is to cut the HS Rank values different places and compute the corresponding flogs. For example, suppose that we cut HS Rank at 90%. Then we have the data table</p>
<table>
<thead>
<tr class="header">
<th>HS Rank</th>
<th>1996</th>
<th>1997</th>
<th>1998</th>
<th>1999</th>
<th>2000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90% - 100%</td>
<td>13.3</td>
<td>14.2</td>
<td>13.0</td>
<td>12.3</td>
<td>12.1</td>
</tr>
<tr class="even">
<td>80%-89%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>70%-79%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>60%-69%</td>
<td>86.7</td>
<td>85.8</td>
<td>87.0</td>
<td>87.7</td>
<td>87.9</td>
</tr>
<tr class="odd">
<td>50%-59%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Below 50%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>100</td>
<td>100</td>
<td>100</td>
<td>100</td>
<td>100</td>
</tr>
</tbody>
</table>
<p>where I have combined the percentages below the cut. I convert the year fractions (.133, .142, .130, .123, .121) to flogs (I use the basic definition <span class="math inline">\(\log(f) - \log(1-f)\)</span> here.)</p>
<table style="width:100%;">
<colgroup>
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th>HS Rank</th>
<th>1996</th>
<th>1997</th>
<th>1998</th>
<th>1999</th>
<th>2000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90% - 100%</td>
<td><span class="math inline">\(-1.87\)</span></td>
<td><span class="math inline">\(-1.80\)</span></td>
<td><span class="math inline">\(-1.90\)</span></td>
<td><span class="math inline">\(-1.96\)</span></td>
<td><span class="math inline">\(-1.98\)</span></td>
</tr>
<tr class="even">
<td>80%-89%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>70%-79%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>60%-69%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>50%-59%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Below 50%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Next, we cut the HS Rank data at 80% as follows:</p>
<table>
<thead>
<tr class="header">
<th>HS Rank</th>
<th>1996</th>
<th>1997</th>
<th>1998</th>
<th>1999</th>
<th>2000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90% - 100%</td>
<td>31.3</td>
<td>28.9</td>
<td>29.2</td>
<td>28.9</td>
<td>26.7</td>
</tr>
<tr class="even">
<td>80%-89%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>70%-79%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>60%-69%</td>
<td>68.7</td>
<td>71.1</td>
<td>71.8</td>
<td>71.1</td>
<td>73.3</td>
</tr>
<tr class="odd">
<td>50%-59%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Below 50%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Again we convert the fractions to flogs.</p>
<table style="width:100%;">
<colgroup>
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th>HS Rank</th>
<th>1996</th>
<th>1997</th>
<th>1998</th>
<th>1999</th>
<th>2000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90% - 100%</td>
<td><span class="math inline">\(-0.79\)</span></td>
<td><span class="math inline">\(-0.90\)</span></td>
<td><span class="math inline">\(-0.89\)</span></td>
<td><span class="math inline">\(-0.90\)</span></td>
<td><span class="math inline">\(-1.01\)</span></td>
</tr>
<tr class="even">
<td>80%-89%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>70%-79%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>60%-69%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>50%-59%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Below 50%</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>If we do this procedure for all 5 possible cuts, then we get the following table of flogs:</p>
<table>
<thead>
<tr class="header">
<th>CUT</th>
<th>1996</th>
<th>1997</th>
<th>1998</th>
<th>1999</th>
<th>2000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90-100% between 0-89%</td>
<td>-1.87</td>
<td>-1.80</td>
<td>-1.90</td>
<td>-1.96</td>
<td>-1.98</td>
</tr>
<tr class="even">
<td>80-100% between 0-79%</td>
<td>-0.79</td>
<td>-0.90</td>
<td>-0.89</td>
<td>-0.90</td>
<td>-1.01</td>
</tr>
<tr class="odd">
<td>70-100% between 0-69%</td>
<td>-0.09</td>
<td>-0.21</td>
<td>-0.19</td>
<td>-0.22</td>
<td>-0.31</td>
</tr>
<tr class="even">
<td>60-100% between 0-59%</td>
<td>0.58</td>
<td>0.45</td>
<td>0.46</td>
<td>0.47</td>
<td>0.34</td>
</tr>
<tr class="odd">
<td>50-100% between 0-49%</td>
<td>1.37</td>
<td>1.16</td>
<td>1.18</td>
<td>1.15</td>
<td>1.10</td>
</tr>
</tbody>
</table>
<p>This table essentially gives an analysis of fractions where all possible cuts are considered. We are interested in how the flogs change across years. So we compute the differences between consecutive years. The first column shows the change in the flog between 1996 and 1997, the second column the change in flog between 1997 and 1998, and so on.</p>
<table>
<thead>
<tr class="header">
<th>CUT</th>
<th>1996-1997</th>
<th>1997-1998</th>
<th>1998-1999</th>
<th>1999-2000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90-100% between 0-89%</td>
<td>0.08</td>
<td>-0.10</td>
<td>-0.06</td>
<td>-0.02</td>
</tr>
<tr class="even">
<td>80-100% between 0-79%</td>
<td>-0.11</td>
<td>0.01</td>
<td>-0.01</td>
<td>-0.11</td>
</tr>
<tr class="odd">
<td>70-100% between 0-69%</td>
<td>-0.12</td>
<td>0.02</td>
<td>-0.02</td>
<td>-0.09</td>
</tr>
<tr class="even">
<td>60-100% between 0-59%</td>
<td>-0.13</td>
<td>0.01</td>
<td>0.01</td>
<td>-0.14</td>
</tr>
<tr class="odd">
<td>50-100% between 0-49%</td>
<td>-0.21</td>
<td>0.02</td>
<td>-0.03</td>
<td>-0.05</td>
</tr>
<tr class="even">
<td>MEDIAN</td>
<td>-0.12</td>
<td>0.01</td>
<td>-0.01</td>
<td>-0.09</td>
</tr>
</tbody>
</table>
<p>By looking down each column, we get a general sense of how the HS rank percentages change in consecutive years. The MEDIAN row gives the median change in flog for each two-year sequence. It is pretty clear that the BGSU freshmen’s HS rank significantly decreased from 1996 to 1997 and from 1999 to 2000. In contrast, the HS ranks stayed roughly the same between 1997 and 1999. It would be interesting to see if there were any changes in the admission procedure that may have impacted the quality of the incoming BGSU freshmen.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="binned-data-ii.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/23-FractionData.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Course in Exploratory Data Analysis.pdf", "Course in Exploratory Data Analysis.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
