<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jim Albert">
<meta name="dcterms.date" content="2024-11-17">

<title>Clutch Performances</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Clutch_files/libs/clipboard/clipboard.min.js"></script>
<script src="Clutch_files/libs/quarto-html/quarto.js"></script>
<script src="Clutch_files/libs/quarto-html/popper.min.js"></script>
<script src="Clutch_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Clutch_files/libs/quarto-html/anchor.min.js"></script>
<link href="Clutch_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Clutch_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Clutch_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Clutch_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Clutch_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#clutch-performers-in-2013" id="toc-clutch-performers-in-2013" class="nav-link" data-scroll-target="#clutch-performers-in-2013"><span class="header-section-number">2</span> Clutch Performers in 2013</a></li>
  <li><a href="#team-clutch-hitting---part-i" id="toc-team-clutch-hitting---part-i" class="nav-link" data-scroll-target="#team-clutch-hitting---part-i"><span class="header-section-number">3</span> Team Clutch Hitting - Part I</a></li>
  <li><a href="#team-clutch-hitting---part-2" id="toc-team-clutch-hitting---part-2" class="nav-link" data-scroll-target="#team-clutch-hitting---part-2"><span class="header-section-number">4</span> Team Clutch Hitting - Part 2</a></li>
  <li><a href="#luck-in-the-pythagorean-theorem" id="toc-luck-in-the-pythagorean-theorem" class="nav-link" data-scroll-target="#luck-in-the-pythagorean-theorem"><span class="header-section-number">5</span> Luck in the Pythagorean Theorem</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1"><span class="header-section-number">5.1</span> Introduction</a></li>
  <li><a href="#the-2016-season" id="toc-the-2016-season" class="nav-link" data-scroll-target="#the-2016-season"><span class="header-section-number">5.2</span> The 2016 season</a></li>
  <li><a href="#pythagorean-slope" id="toc-pythagorean-slope" class="nav-link" data-scroll-target="#pythagorean-slope"><span class="header-section-number">5.3</span> Pythagorean slope</a></li>
  <li><a href="#size-of-the-luck-component" id="toc-size-of-the-luck-component" class="nav-link" data-scroll-target="#size-of-the-luck-component"><span class="header-section-number">5.4</span> Size of the luck component?</a></li>
  <li><a href="#explanations-for-the-luck-component" id="toc-explanations-for-the-luck-component" class="nav-link" data-scroll-target="#explanations-for-the-luck-component"><span class="header-section-number">5.5</span> Explanations for the luck component?</a></li>
  <li><a href="#final-comments" id="toc-final-comments" class="nav-link" data-scroll-target="#final-comments"><span class="header-section-number">5.6</span> Final comments</a></li>
  </ul></li>
  <li><a href="#clutch-home-runs" id="toc-clutch-home-runs" class="nav-link" data-scroll-target="#clutch-home-runs"><span class="header-section-number">6</span> Clutch Home Runs</a>
  <ul class="collapse">
  <li><a href="#introduction-2" id="toc-introduction-2" class="nav-link" data-scroll-target="#introduction-2"><span class="header-section-number">6.1</span> Introduction</a></li>
  <li><a href="#downloading-the-retrosheet-play-by-play-data" id="toc-downloading-the-retrosheet-play-by-play-data" class="nav-link" data-scroll-target="#downloading-the-retrosheet-play-by-play-data"><span class="header-section-number">6.2</span> Downloading the Retrosheet Play-by-Play Data:</a></li>
  <li><a href="#computing-run-expectancies-and-win-probabilities" id="toc-computing-run-expectancies-and-win-probabilities" class="nav-link" data-scroll-target="#computing-run-expectancies-and-win-probabilities"><span class="header-section-number">6.3</span> Computing Run Expectancies and Win Probabilities</a></li>
  <li><a href="#value-of-home-runs" id="toc-value-of-home-runs" class="nav-link" data-scroll-target="#value-of-home-runs"><span class="header-section-number">6.4</span> Value of Home Runs?</a></li>
  <li><a href="#summing-up" id="toc-summing-up" class="nav-link" data-scroll-target="#summing-up"><span class="header-section-number">6.5</span> Summing Up</a></li>
  </ul></li>
  <li><a href="#is-a-pitchers-winloss-record-meaningful" id="toc-is-a-pitchers-winloss-record-meaningful" class="nav-link" data-scroll-target="#is-a-pitchers-winloss-record-meaningful"><span class="header-section-number">7</span> Is a Pitcher’s Win/Loss Record Meaningful?</a>
  <ul class="collapse">
  <li><a href="#introduction-3" id="toc-introduction-3" class="nav-link" data-scroll-target="#introduction-3"><span class="header-section-number">7.1</span> Introduction</a></li>
  <li><a href="#data-work" id="toc-data-work" class="nav-link" data-scroll-target="#data-work"><span class="header-section-number">7.2</span> Data Work</a></li>
  <li><a href="#sandy-koufax" id="toc-sandy-koufax" class="nav-link" data-scroll-target="#sandy-koufax"><span class="header-section-number">7.3</span> Sandy Koufax</a></li>
  <li><a href="#some-graphs" id="toc-some-graphs" class="nav-link" data-scroll-target="#some-graphs"><span class="header-section-number">7.4</span> Some Graphs</a></li>
  <li><a href="#some-unusual-pitchers" id="toc-some-unusual-pitchers" class="nav-link" data-scroll-target="#some-unusual-pitchers"><span class="header-section-number">7.5</span> Some Unusual Pitchers</a></li>
  <li><a href="#takeaways" id="toc-takeaways" class="nav-link" data-scroll-target="#takeaways"><span class="header-section-number">7.6</span> Takeaways</a></li>
  </ul></li>
  <li><a href="#clutch-hitters-in-2024---a-runs-added-approach" id="toc-clutch-hitters-in-2024---a-runs-added-approach" class="nav-link" data-scroll-target="#clutch-hitters-in-2024---a-runs-added-approach"><span class="header-section-number">8</span> Clutch Hitters in 2024 - A Runs Added Approach</a>
  <ul class="collapse">
  <li><a href="#introduction-4" id="toc-introduction-4" class="nav-link" data-scroll-target="#introduction-4"><span class="header-section-number">8.1</span> Introduction</a></li>
  <li><a href="#a-model-for-a-player-who-has-not-clutch-ability" id="toc-a-model-for-a-player-who-has-not-clutch-ability" class="nav-link" data-scroll-target="#a-model-for-a-player-who-has-not-clutch-ability"><span class="header-section-number">8.2</span> A Model for a Player Who Has Not Clutch Ability</a></li>
  <li><a href="#corey-seager" id="toc-corey-seager" class="nav-link" data-scroll-target="#corey-seager"><span class="header-section-number">8.3</span> Corey Seager</a></li>
  <li><a href="#a-measure-of-clutch" id="toc-a-measure-of-clutch" class="nav-link" data-scroll-target="#a-measure-of-clutch"><span class="header-section-number">8.4</span> A Measure of Clutch</a></li>
  <li><a href="#takeaways-1" id="toc-takeaways-1" class="nav-link" data-scroll-target="#takeaways-1"><span class="header-section-number">8.5</span> Takeaways</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Clutch Performances</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jim Albert </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 17, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>These posts from the “Exploring Baseball Data with R” blog deal with clutch performances in baseball by teams and individuals.</p>
<p>Section 2 describes one method of defining clutch performances of hitters. We look at the mean runs value of plate appearances of hitters in scoring and non-scoring bases situations. One takeaway is that there appears to be a strong positive relationship between a player’s performance and his “clutch” performance.</p>
<p>Sections 3 and 4 focus on clutch performances of teams. Part 1 of this study relates the probability of scoring with the number of runners in scoring position. Using this measure, Part 2 compares the 30 teams with respect to clutch performance in scoring runs. One takeaway is that there is little evidence that teams have less or more ability to advance runners in scoring position.</p>
<p>Section 5 looks at the well-known Pythagorean formula and explores the residuals, the number of games won over what is expected by the Pythagorean relationship. We see a “extreme records” effect – for example, teams who are very successful tend to win more than expected from their R/RA ration.</p>
<p>Section 6 explores the clutch home runs hit during the 2018 season and Section 7 explores if there is any meaning of a pitcher’s win/loss record beyond the pitcher’s ratio of runs scored against the runs allowed. By itself, the pitcher’s W/L record is informative, but it is not that useful if one has many alternative measures of pitching performance.</p>
<p>Section 8 focuses on clutch performances of hitters. The RE24 measure is situation-dependent and that motives the consideration of a new measure that adjusts RE24 for the runners on base/outs situation. This post describes the construction of this new measure by use of a model that assummes that situation and performance are independent.</p>
</section>
<section id="clutch-performers-in-2013" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="clutch-performers-in-2013"><span class="header-section-number">2</span> Clutch Performers in 2013</h2>
<p>In the last post, I illustrated reading into R the 2013 Retrosheet play-by-play data. Also, I illustrated computing the run values of all plays using a function version of the R code from our book. Here we use this data to find the best clutch performers in the 2013 season.</p>
<p>We have a data frame <code>d2013</code> containing all of the plays. We use the subset function to restrict attention to plays where there was a batting event (excluding events like attempted steals).</p>
<pre><code>d2013 &lt;- subset(d2013, BAT_EVENT_FL == TRUE)</code></pre>
<p>In my previous function, we added a new variable <code>STATE</code> which gives the current runners on base and the number of outs. We define a new variable <code>Scoring.Position</code> which is “yes” if there are runners in scoring position and “no” otherwise.</p>
<pre><code>d2013$Scoring.Position &lt;- with(d2013,
      ifelse(STATE=="010 0" | STATE=="010 1" | STATE=="010 2" |
            STATE=="011 0" | STATE=="011 1" | STATE=="011 2" |
            STATE=="110 0" | STATE=="110 1" | STATE=="110 2" |
            STATE=="101 0" | STATE=="101 1" | STATE=="101 2" |
            STATE=="001 0" | STATE=="001 1" | STATE=="001 2" |
            STATE=="111 0" | STATE=="111 1" | STATE=="111 2",
            "yes", "no")
            )</code></pre>
<p>For each batter, we want to compute the number of plate appearances and the mean runs value for batting plays when runners in scoring position, and for other plays. This is conveniently done using the new <code>dplyr</code> package.</p>
<pre><code>library(dplyr)
RUNS.VALUE &lt;- summarise(group_by(d2013, BAT_ID, Scoring.Position),
                  PA = n(),
                  meanRUNS = mean(RUNS.VALUE))</code></pre>
<p>Next, we use several applications of subset and merge to create a new data frame <code>RUNSsituation</code>. A given row will contain the PA and means runs for a given batter when runners are in SP and not-SP situations. We only consider hitters who have 100 PA’s in each situation.</p>
<pre><code>RUNS.VALUE1 &lt;- subset(RUNS.VALUE, PA &gt;= 100)
RUNS.SP &lt;- subset(RUNS.VALUE1, Scoring.Position=="yes")
RUNS.NSP &lt;- subset(RUNS.VALUE1, Scoring.Position=="no")
RUNSsituation &lt;- merge(RUNS.SP, RUNS.NSP, by="BAT_ID")</code></pre>
<p>We compute the <code>Mean</code> runs value and the <code>Difference</code>, the difference between the mean runs values in scoring position and non-scoring position situations.</p>
<pre><code>RUNSsituation$Mean &lt;- with(RUNSsituation,
           (PA.x * meanRUNS.x + PA.y * meanRUNS.y) / (PA.x + PA.y))
RUNSsituation$Difference &lt;- with(RUNSsituation,
            meanRUNS.x - meanRUNS.y)</code></pre>
<p>The <code>ggplot2</code> package is used to plot the mean (that we call <code>Performance</code>) against the difference (that we call <code>Clutch</code>). I plot abbreviated player codes so we can easily identify hitters.</p>
<pre><code>library(ggplot2)
ggplot(RUNSsituation,
  aes(Mean, Difference, label=substr(BAT_ID, 1, 4))) +
  geom_text(color="blue")  +
  geom_hline(yintercept=0, color="red") +
  geom_vline(xintercept=0, color="red") +
  xlab("PERFORMANCE") + ylab("CLUTCH")</code></pre>
<p><img src="figures/clutch/clutch1.png" class="img-fluid" style="width:70.0%"></p>
<p>From the plot we see that Miguel Cabrera and Chris Davis had the highest mean performances and Freddie Freeman and Allen Craig had the best clutch performances using our definition of clutch. B.J. Upton was one of the weakest performers (from a runs value perspective) and also was the worst clutch performers using this measure. What is interesting is that there is a pretty strong positive relationship between performance and clutch. So the best clutch performers tend to be the better hitters. So maybe in our search for clutch players one needs to adjust for level of performance.</p>
</section>
<section id="team-clutch-hitting---part-i" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="team-clutch-hitting---part-i"><span class="header-section-number">3</span> Team Clutch Hitting - Part I</h2>
<p>Suppose we’re interested in exploring clutch hitting in baseball. Essentially, scoring runs is a two-stage process – one puts runners on base and then advance them to home. Teams are especially interested in scoring runners who are in scoring position. We’ll use Retrosheet data and R to explore the relationship between runners in scoring position and runs scored. Specifically, is there a single number that we can use to summarize this relationship?</p>
<p>We begin by reading in the Retrosheet play-by-play data for the 2013 season. I earlier had created this worksheet by downloading all of the Retrosheet play-by-play files. (See the earlier post which described the process of downloading the Retrosheet files into R.)</p>
<pre><code>load("pbp2013.Rdata")</code></pre>
<p>The variable <code>HALF.INNING</code> is a unique identifier for the game and half inning. Using the summarize function in the dplyr package, I create a new data frame S with two variables: RSP, the number of runners in scoring position, and RUNS the number of these runners who eventually score. (The variables <code>BASE_2_RUN_ID</code>, <code>BASE3_RUN_ID</code>, <code>RUN2_DEST_ID</code>, and <code>RUN3_DEST_ID</code> are helpful here.)</p>
<pre><code>library(dplyr)
S &lt;- summarize(group_by(d2013, BAT_TEAM, HALF.INNING), RSP = length(unique(c(as.character(BASE2_RUN_ID),
    as.character(BASE3_RUN_ID)))) - 1, RUNS = sum(RUN2_DEST_ID &gt;= 4) + sum(RUN3_DEST_ID &gt;=
    4))</code></pre>
<p>Using the <code>cut()</code> function I create a categorical variable <code>Cat.RUNS</code> which classifies the runs scored into the classes “0 Runs”, “1 Run”, etc. We use the subset function to only consider the situations when at least one runner is in scoring position.</p>
<pre><code>S$Cat.RUNS &lt;- cut(S$RUNS, breaks = c(-0.5, 0.5, 1.5, 2.5, 3.5, 1000), labels = c("0 Runs",
    "1 Run", "2 Runs", "3 Runs", "4+ Runs"))
S.RSP &lt;- subset(S, RSP &gt;= 1)</code></pre>
<p>The <code>table()</code> function displays all counts for all values of <code>RSP</code> and <code>Cat.Runs</code>.</p>
<pre><code>TB &lt;- with(S.RSP, table(RSP, Cat.RUNS))
TB

##    Cat.RUNS
## RSP 0 Runs 1 Run 2 Runs 3 Runs 4+ Runs
##   1   8817  1908      0      0       0
##   2   1662  2527    566      0       0
##   3     80   723    928    199       0
##   4      4    47    344    378      64
##   5      0     1     31    123     144
##   6      0     0      2      5     115
##   7      0     0      0      0      54
##   8      0     0      0      0      13
##   9      0     0      0      0       2</code></pre>
<p>We see, for example, there were 1908 half-innings where there was exactly one runner in scoring position and that runner scored.</p>
<p>The <code>prop.table()</code> function with argument 1 gives the row proportions of the table.</p>
<pre><code>TB &lt;- with(S.RSP, table(RSP, Cat.RUNS))
P &lt;- prop.table(TB, 1)
round(P, 3)

##    Cat.RUNS
## RSP 0 Runs 1 Run 2 Runs 3 Runs 4+ Runs
##   1  0.822 0.178  0.000  0.000   0.000
##   2  0.350 0.531  0.119  0.000   0.000
##   3  0.041 0.375  0.481  0.103   0.000
##   4  0.005 0.056  0.411  0.452   0.076
##   5  0.000 0.003  0.104  0.411   0.482
##   6  0.000 0.000  0.016  0.041   0.943
##   7  0.000 0.000  0.000  0.000   1.000
##   8  0.000 0.000  0.000  0.000   1.000
##   9  0.000 0.000  0.000  0.000   1.000</code></pre>
<p>For example, when there is one runner in scoring position (RSP=1), this runner will score with probability 0.178. When there are two runners in scoring position, both will score with probability 0.119, etc.</p>
<p>I’m interested in exploring the relationship between the number of runners in scoring position and the chance the team scores at least 1 run, the chance the team scores 2 or more runs, and the chance the team scores 3 or more runs. I create a new data frame with three variables <code>Runners.SP</code>, <code>Probability</code>, and <code>Type</code>.</p>
<pre><code>P1plus &lt;- 1 - P[1:5, "0 Runs"]
P2plus &lt;- 1 - P[1:5, "0 Runs"] - P[1:5, "1 Run"]
P3plus &lt;- 1 - P[1:5, "0 Runs"] - P[1:5, "1 Run"] - P[1:5, "2 Runs"]
d1 &lt;- data.frame(Runners.SP = 1:5, Probability = P1plus, Type = "1+ Runs")
d2 &lt;- data.frame(Runners.SP = 1:5, Probability = P2plus, Type = "2+ Runs")
d3 &lt;- data.frame(Runners.SP = 1:5, Probability = P3plus, Type = "3+ Runs")
d &lt;- rbind(d1, d2, d3)</code></pre>
<p>I use the <code>ggplot2</code> package to plot line plots of P(scoring 1+ runs), P(scoring 2+ runs), and P(scoring 3+ runs) against the number of runners in scoring position.</p>
<pre><code>library(ggplot2)
ggplot(d, aes(Runners.SP, Probability, color = Type)) + geom_line(size = 2) +
    theme(text = element_text(size = rel(5))) + theme(legend.text = element_text(size = rel(4))) +
    theme(legend.title = element_blank()) + labs(title = "Clutch Hitting - Probability Scale") +
    theme(plot.title = element_text(size = rel(6), color = "red"))</code></pre>
<p><img src="figures/clutch/clutch2.png" class="img-fluid" style="width:70.0%"></p>
<p>This is a tough graph to interpret since the curves are not linear – this is because the vertical scale (probability) has to fall between 0 and 1 and that causes the curves to have the S shape.</p>
<p>This is a nice way to improve this graph – we reexpress each probability to the logit scale. We create a new variable Logit = log (prob / (1 - prob)). This will be used to transform the P(scoring 1+ runs), P(scoring 2+ runs) and P(scoring 3+ runs). (It takes some practice to get used to thinking of logits. A probability less than 0.5 gets reexpressed to a negative logit, a probability larger than 0.5 gets changed to a positive logit. Probabilities fall between 0 and 1, while logits can take on any value from -infinity to +infinity.)</p>
<pre><code>d$Logit &lt;- with(d, log(Probability/(1 - Probability)))
d$Logit &lt;- ifelse(is.infinite(d$Logit), NaN, d$Logit)</code></pre>
<p>Look what happens when we redraw the graph with the logit (instead of the probability) on the vertical scale.</p>
<pre><code>ggplot(d, aes(Runners.SP, Logit, color = Type)) + geom_line(size = 2) + scale_y_continuous(limits = c(-3,
    6)) + theme(text = element_text(size = rel(5))) + theme(legend.text = element_text(size = rel(4))) +
    theme(legend.title = element_blank()) + labs(title = "Clutch Hitting - Logit Scale") +
    theme(plot.title = element_text(size = rel(6), color = "red"))</code></pre>
<p><img src="figures/clutch/clutch3.png" class="img-fluid" style="width:70.0%"></p>
<p>This is much easier to interpret since we see three parallel lines. On the logit scale, having one more runner in scoring position increases the probability of scoring 1+ runs by about 2.3. Also (since the lines have the same slope), the chance of scoring 2 or more runs increases (on the logit scale) by 2.3 for each additional runner in scoring position. A similar statement can be made about the chance of scoring 3 or more runs (on the logit scale).</p>
<p>In effect, we have reduced a discussion of clutch hitting to a single slope that relates the number of runners in scoring position to the logit of the probability of scoring x+ runs where x can be 1, 2, or 3. In a later post, we’ll use this idea to compare the clutch hitting abilities of the 30 teams.</p>
</section>
<section id="team-clutch-hitting---part-2" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="team-clutch-hitting---part-2"><span class="header-section-number">4</span> Team Clutch Hitting - Part 2</h2>
<p>Let’s return to my previous post where we were talking about clutch hitting – that is, the ability of a team to score runners who are in scoring position.</p>
<p>The question we want to focus on is this: do teams really differ in their ability to advance runners from scoring position to home?</p>
<p>Here’s the R work, reviewing what I did in the previous post.</p>
<p>Load in the Retrosheet play-by-play data for the 2013 season. Since we want to consider plays at the beginning of the inning – we use the subset function with the condition that <code>LEADOFF_FL = TRUE</code>.</p>
<pre><code>load("pbp2013.Rdata")
d.inning &lt;- subset(d2013, LEADOFF_FL==TRUE)</code></pre>
<p>As before, we create a data set with two variables: <code>RSP</code> = number of runs in scoring position and <code>RUNS</code> = the number of runners in scoring position who actually score. Since we are focusing on the process of advancing runners to home, we consider innings where there is at least one runner in scoring position.</p>
<pre><code>library(dplyr)
S &lt;- summarize(group_by(d2013, BAT_TEAM, HALF.INNING),
               RSP=length(unique(c(as.character(BASE2_RUN_ID)
                                   as.character(BASE3_RUN_ID)))) - 1,
               RUNS=sum(RUN2_DEST_ID &gt;= 4) + sum(RUN3_DEST_ID &gt;= 4))

S$cruns &lt;- cut(S$RUNS,
                  breaks=c(-.5, .5, 1.5, 2.5, 3.5, 1000),
                  labels=c("0 Runs", "1 Run", "2 Runs",
                           "3 Runs", "4+ Runs"))
S.RSP &lt;- subset(S, RSP &gt;= 1)</code></pre>
<p>As before, we tabulate runners in scoring position and runs scored.</p>
<pre><code>with(S.RSP, table(RSP, cruns))

##    cruns
## RSP 0 Runs 1 Run 2 Runs 3 Runs 4+ Runs
##   1   8817  1908      0      0       0
##   2   1662  2527    566      0       0
##   3     80   723    928    199       0
##   4      4    47    344    378      64
##   5      0     1     31    123     144
##   6      0     0      2      5     115
##   7      0     0      0      0      54
##   8      0     0      0      0      13
##   9      0     0      0      0       2</code></pre>
<p>A simple way to summarize the relationship in the table is by fitting an ordinal logistic regression model. One can write this model as <span class="math display">\[
logit(Prob(R \ge c)) = \log\left(\frac{Prob(R \ge c)}{1 - Prob(R \ge c)}\right) = - \gamma_c + \beta x
\]</span> where <span class="math inline">\(R\)</span> is the number of runs scored, <span class="math inline">\(x\)</span> is the number of runners in scoring position, <span class="math inline">\(\beta\)</span> tells us how much the logit of the probability (the left hand side of the equation) changes as you have one more runner in scoring position.</p>
<p>This model is easy to fit using the <code>clm()</code> function in the ordinal package. I show the estimate of <span class="math inline">\(\beta\)</span> and the associated standard error.</p>
<pre><code>library(ordinal)
fit &lt;- clm(cruns ~ RSP, data=S.RSP)
c(beta=fit$coef[5], se=sqrt(vcov(fit)[5, 5]))

## beta.RSP       se
##  2.39485  0.02485</code></pre>
<p>Since it is easy to think about this fitted model on the probability scale, I display the fitted probabilities of scoring 1+ runs, 2+ runs, 3+ runs, and 4+ runs as a function of the number of runners in scoring position. Notice I use the inverse logit function invlogit (in the arm package) to convert <span class="math inline">\(- \gamma_c + \beta x\)</span> to a probability scale.</p>
<pre><code>library(arm)
beta &lt;- fit$coef[5]
gam &lt;- fit$coef[1:4]
curve(invlogit(-gam[1] + beta * x), 1, 4,
      ylim=c(0, 1), xlab="RUNNERS IN SCORING POSITION",
      ylab="PROBABILITY")
for(j in 2:4)
   curve(invlogit(-gam[j] + beta * x), add = TRUE)
text(c(2, 2.5, 3, 3.5), c(.7, .25, .15, .05),
     c("1+ Runs", "2+ Runs", "3+ Runs", "4+ Runs"))</code></pre>
<p><img src="figures/clutch/clutch4.png" class="img-fluid" style="width:70.0%"></p>
<p>This model fit gives us a general idea about clutch hitting – how the number of runners in scoring position translates to runs scored.</p>
<p>The interesting question is how do teams differ in clutch hitting?</p>
<p>We address this question by fitting this ordinal regression model separately to each team. We write a short function one.fit which does this for one team, and then the useful function sapply applies this function for all teams.</p>
<pre><code>one.fit &lt;- function(team, d, covariate){
    fit &lt;- clm(as.formula(paste("cruns ~", covariate)),
                data=subset(d, BAT_TEAM==team))
    b &lt;- coef(fit)[5]
    se &lt;- sqrt(vcov(fit)[5, 5])
    return(c(b, se))}

TEAMS &lt;- unique(as.character(S.RSP$BAT_TEAM))
estimates &lt;- sapply(TEAMS, one.fit, S.RSP, "RSP")
round(estimates, 2)

     ANA  ARI  ATL  BAL  BOS  CHA  CHN  CIN  CLE  COL  DET  HOU  KCA  LAN  MIA
RSP 2.19 2.56 2.51 2.46 2.28 2.50 2.33 2.40 2.34 2.50 2.29 2.39 2.39 2.33 2.55
    0.12 0.14 0.15 0.14 0.12 0.15 0.14 0.13 0.13 0.14 0.12 0.14 0.14 0.13 0.15
     MIL  MIN  NYA  NYN  OAK  PHI  PIT  SDN  SEA  SFN  SLN  TBA  TEX  TOR  WAS
RSP 2.51 2.38 2.39 2.60 2.33 2.54 2.34 2.33 2.29 2.35 2.51 2.38 2.54 2.31 2.48
    0.14 0.14 0.14 0.15 0.14 0.15 0.14 0.13 0.14 0.13 0.14 0.13 0.14 0.13 0.14</code></pre>
<p>Looking at the <span class="math inline">\(\beta\)</span> estimates, one might think that teams differ in clutch hitting ability. For example, the Mets have a large <span class="math inline">\(\beta\)</span> estimate of 2.60 which indicates they were strong in advancing runners in 2013 and Anaheim with an estimate of 2.19 appears to be poor in clutch hitting. But you have to look at these estimates relative to the standard errors.</p>
<p>Once we have computed a “clutch” estimate <span class="math inline">\(\hat\beta\)</span>, our knowledge about the true clutch ability <span class="math inline">\(\beta\)</span> can be described by a normal curve with mean <span class="math inline">\(\hat\beta\)</span> and standard deviation <span class="math inline">\(se\)</span>, where <span class="math inline">\(se\)</span> is the standard error of the estimate <span class="math inline">\(\hat\beta\)</span>.</p>
<p>We plot all of these normal curves for the team clutch abilities <span class="math inline">\(\beta_1,... , \beta_{30}\)</span> on the same graph.</p>
<pre><code>curve(dnorm(x, estimates[1, 1], estimates[2, 1]),
      1.5, 3.5, ylim=c(0, 4),
      xlab="Beta", ylab="Posterior Density",
      main="Team Estimates of Clutch Hitting")
for(j in 2:30)
  curve(dnorm(x, estimates[1, j], estimates[2, j]), add=TRUE)</code></pre>
<p><img src="figures/clutch/clutch5.png" class="img-fluid" style="width:70.0%"></p>
<p>What do we see? The bottom line is that there is a lot of overlap in these curves. This means there is little statistical evidence that teams actually have different abilities to advance runners in scoring position. Teams do differ in their abilities to get on-base, and in their abilities to get extra-base hits, but not in their abilities to perform well or badly in clutch situations.</p>
</section>
<section id="luck-in-the-pythagorean-theorem" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="luck-in-the-pythagorean-theorem"><span class="header-section-number">5</span> Luck in the Pythagorean Theorem</h2>
<section id="introduction-1" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="introduction-1"><span class="header-section-number">5.1</span> Introduction</h3>
<p>Last week, I was providing an introduction to baseball analytics to freshmen data science majors and I introduced the Pythagorean Theorem which relates runs to wins, &nbsp;I thought it would be interesting to revisit this relationship, focusing on teams that do better or worse than what is expected by Pythagorean, that is, the “luck” component.</p>
</section>
<section id="the-2016-season" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="the-2016-season"><span class="header-section-number">5.2</span> The 2016 season</h3>
<p>To get started, let’s look at the 2016 season. &nbsp;The Pythagorean relationship, on the log scale, can be written as</p>
<p><span class="math display">\[
\log(W / L) = k \log(R / RA)
\]</span></p>
<p>(I express it this way since this is now a linear model and easy to fit using the R <code>lm()</code> function.) &nbsp;Below I plot values of <span class="math inline">\(\log(W/L)\)</span> and <span class="math inline">\(\log(R/RA)\)</span> for the 30 teams and overlay a least-squares line.</p>
<p><img src="figures/clutch/clutch6.png" class="img-fluid" style="width:70.0%"></p>
<p>Here the estimated slope is 1.68. &nbsp;Teams that fall above the line are considered lucky in the sense that they won more games than one would expect based on the runs scored and allowed. &nbsp;Looking at the graph, Texas appeared to be lucky and Minnesota was unusually unlucky. &nbsp;The Cubs were extreme on their ratio of runs to runs scored, but their point falls a little below the line, indicating they were a little unlucky in terms of their W/L ratio.</p>
<p>This raises several questions:</p>
<ul>
<li>How has the Pythagorean slope changed over seasons?</li>
<li>What is the general size of this luck component? &nbsp;That is, over many seasons, how many additional wins or losses to teams have based on “luck”? &nbsp;(Here I am using luck to describe the variation in wins/losses not explained by the R/RA ratio.)</li>
<li>Are there possible explanations for the luck component?</li>
</ul>
</section>
<section id="pythagorean-slope" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="pythagorean-slope"><span class="header-section-number">5.3</span> Pythagorean slope</h3>
<p>To see how the Pythagorean slope has changed over seasons, I fit this model for the past 50 seasons – here is a graph of the estimated slope against seasons.</p>
<p><img src="figures/clutch/clutch7.png" class="img-fluid" style="width:70.0%"></p>
<p>In the days of low scoring like 1968, the estimate was small (1.6), and then the estimate showed a steady increase until 1990, steady from 1990 to 2005, and then has shown a decrease in recent seasons. &nbsp;What is actually remarkable is not the trend, but the high variability of the estimate – it appears that we don’t get a great estimate at this slope from data from a single season.</p>
</section>
<section id="size-of-the-luck-component" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="size-of-the-luck-component"><span class="header-section-number">5.4</span> Size of the luck component?</h3>
<p>In my model, the residual is relatively hard to interpret since the variables are on a log scale. &nbsp;So I focus on the residual</p>
<p>Residual = Actual Wins - Predicted Wins</p>
<p>So, for example, if Residual = 5, then this team has won 5 more games than one would expect based on the Pythagorean relationship. &nbsp;For each of my 50 seasons, I found all of the residuals – here is a density estimate of all of these residuals.</p>
<p><img src="figures/clutch/clutch8.png" class="img-fluid" style="width:70.0%"></p>
<p>These residuals are bell-shaped &nbsp;and 85% of the values fall between -5 and 5. &nbsp;Thus it is pretty unusual for a team to win more than 5 or lose more than 5 games than expected. &nbsp;Only 2% of the residuals exceed 10 in absolute value. &nbsp;It is really unusual for a team to vary 10 or more than expected by the Pythagorean formula. &nbsp;(By the way, the 2016 Texas team actually had a residual value of 13 which was the most remarkable lucky season in this 50-season exploration.)</p>
</section>
<section id="explanations-for-the-luck-component" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="explanations-for-the-luck-component"><span class="header-section-number">5.5</span> Explanations for the luck component?</h3>
<p>Okay, what are some possible explanations for a team winning more games than expected?</p>
<ul>
<li>They win a lot of close games.</li>
<li>They have great relievers who are good in preserving games.</li>
<li>They are good in playing small ball, that is scoring the winning runs by singles, bunts, etc. in close games.</li>
</ul>
<p>In the BR article referenced above, it says “Deviations from expected W-L are often attributed to the quality of a team’s bullpen, or more dubiously,”clutch play”; many sabermetrics advocates believe the deviations are the result of luck and random chance.”</p>
<p>I believe it has been shown that luck is not persistent in that a team that is lucky one season does not tend to be lucky the previous season. &nbsp;That is, there is a small association between the luck values for consecutive seasons.</p>
<p>But I’ll throw out one interesting thing that I found. &nbsp;Suppose we graph the residuals against the number of games won for all 50 seasons. &nbsp;I overlay a smoothing curve to see the pattern.</p>
<p><img src="figures/clutch/clutch9.png" class="img-fluid" style="width:70.0%"></p>
<p>What this appears to show is a “team with extreme records” effect. &nbsp;Teams that are very successful (that is, win 95 or more games) tend to win more than one would expect based on the R/RA ratio. &nbsp;Conversely, poor teams tend to lose more than one would expect based on the Pythagorean relationship. &nbsp;For a team with 100 wins, it wins about 3 games more than expected.</p>
</section>
<section id="final-comments" class="level3" data-number="5.6">
<h3 data-number="5.6" class="anchored" data-anchor-id="final-comments"><span class="header-section-number">5.6</span> Final comments</h3>
<p>I think the general topic of Pythagorean residuals is interesting and deserves further exploration, &nbsp;For example, it would be interesting to examine the teams like the 2016 Rangers that had very lucky and very unlucky seasons and see if there are any common characteristics.</p>
<p>This study is easy to reproduce using Retrosheet game log data. &nbsp;I have downloaded the game log files for many seasons and it is easy to bring these files into R. &nbsp;Let me know if any of you are interested in seeing the R code for this exploration.</p>
</section>
</section>
<section id="clutch-home-runs" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="clutch-home-runs"><span class="header-section-number">6</span> Clutch Home Runs</h2>
<section id="introduction-2" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="introduction-2"><span class="header-section-number">6.1</span> Introduction</h3>
<p>One of the most popular posts in this blog has been the one giving instructions how to download the Retrosheet play-by-play files. Unfortunately, some people have struggled using the R functions that we describe in our text and this particular post. So I thought it would be helpful to describe a simple method of getting these Retrosheet files into R. Also I wrote a short package that facilitates computing the run values and associated win probabilities for all plays in a Retrosheet dataset. Once you have the Retrosheet data with the run values and win probabilities, you can do a lot of interesting explorations. Below I illustrate exploring the win probabilities of home runs during the 2018 season.</p>
</section>
<section id="downloading-the-retrosheet-play-by-play-data" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="downloading-the-retrosheet-play-by-play-data"><span class="header-section-number">6.2</span> Downloading the Retrosheet Play-by-Play Data:</h3>
<p>Here’s a simpler method. First, one double-clicks on the Retrosheet page to download a zip file containing all of the files for a particular season. (For the 2018 season, there will be 30 files in this compressed file, one corresponding to the home games for each team.) After you unzip the archive, then you run a Chadwick program at the Terminal level (type a single line) to put all of the data into a single csv file. This csv file can then be directly read into R by say the read_csv() function in the readr package.</p>
<p>I describe this process at the page below:</p>
<p>https://bayesball.github.io/VB/Simple_Retrosheet.html</p>
</section>
<section id="computing-run-expectancies-and-win-probabilities" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="computing-run-expectancies-and-win-probabilities"><span class="header-section-number">6.3</span> Computing Run Expectancies and Win Probabilities</h3>
<p>After one has downloaded the Retrosheet data, the next useful step is to compute the run expectancies and win probabilities for all plays. I made some small revisions to my R functions and put them in a new R package WinProbability. (Some description of my methods for computing the win probabilities can be found on the Part I and Part II posts.) Assuming you have downloaded Retrosheet data for a single season, one function in this package will add a header with variable names and compute the run expectancies. Another function will add the win probabilities to the Retrosheet dataset, and a third function will graph the win probabilities for a specific game of interest.</p>
<p>Here’s a description of installing the WinProbability package and doing these calculations:</p>
<p>https://bayesball.github.io/VB/WinProbabilities.html</p>
</section>
<section id="value-of-home-runs" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="value-of-home-runs"><span class="header-section-number">6.4</span> Value of Home Runs?</h3>
<p>To illustrate some work with the 2018 Retrosheet data, let’s explore the value of home runs hit in the 2018 season. In the runs expectancy chapter of our book, we looked at the run value of home runs – one takeaway is that the average run value of a home run is only about 1.4. Perhaps a more relevant measure of the value of a home run is the WPA or win probability added. The WPA, or more precisely the absolute value of the WPA tells us the benefit of the home run (that is, the increase in the team’s win probability) towards the ultimate goal of winning the game for the player’s team. Let’s explore the distribution of WPA across all home run hitters for the 2018 season</p>
<p>A reasonable graph is a scatterplot of the home run count (horizontal axis) against the average values of abs(WPA) (vertical axis) for all 2018 players. I’ve labelled some interesting points in this graph.</p>
<p><img src="figures/clutch/clutch10.png" class="img-fluid" style="width:70.0%"></p>
<p>Brandon Phillips and Raimel Tapia each had only one home run in 2018, but these specific home runs really had an impact. Red Sox fan readers might recall Phillips’ dramatic 9th inning two-run home run in the Sox’ 9-8 win over the Braves on September. Likewise, Ramiel Tapia’s had a grand slam for the Rockies that led to their victory over the D-Backs. Each of these home run increased their team’s win probability by more than 40%.</p>
<p>D.J. LeMahieu had only 15 home runs in 2018, but he seems to stand out with respect to the average abs WPA – his home runs increased his team’s win probability by over 20% on average. This means his home runs seemed to occur at important moments during his team’s games.</p>
<p>We know Khris Davis bested J.D. Martinez with respect to the home run total (48 compared to 43). It is interesting to compare the values of these home runs. Below I display the mean run value and the mean abs(WPA) for both hitters.</p>
<p>What is interesting is that both players tended to average 1.5 run value per home run – a little above average. But Davis’ mean abs WPA is 0.033 higher than Martinez’s value. Let’s look at this more carefully by displaying parallel dotplots of the abs WPA values for the two players. Davis has more home runs than Martinez that increase his team’s probability of winning by 0.2 or higher.</p>
<p><img src="figures/clutch/clutch11.png" class="img-fluid" style="width:70.0%"></p>
</section>
<section id="summing-up" class="level3" data-number="6.5">
<h3 data-number="6.5" class="anchored" data-anchor-id="summing-up"><span class="header-section-number">6.5</span> Summing Up</h3>
<ul>
<li><p>All of the R code for this exercise can be found on my Github Gist site.</p></li>
<li><p>Can we conclude that Khris Davis is a “clutch” home run hitter, in the sense that he tends to hit his home runs during clutch situations? Actually, no. All I have demonstrated is that for the 2018 season, Davis’ home runs contributed more, on average, towards his team’s victories than other players such as J.D. Martinez. It might be better said that Davis was lucky in that he was given the opportunity to hit home runs in important situations.</p></li>
<li><p>Now if one could show that Davis’s home runs consistently contributed more towards team wins than other home run hitters, that would be more interesting.</p></li>
<li><p>To follow up this comments, it is easy to check if this same pattern held in the previous 2017 season. Okay, Davis also had a higher mean abs(WPA) value than Martinez in 2017, so this getting more interesting. (Actually Davis was also had a higher mean abs(WPA) value in the 2016 season.)</p></li>
</ul>
<p><img src="figures/clutch/clutch12.png" class="img-fluid" style="width:70.0%"></p>
<ul>
<li>But even if you could show Khris Davis’ is consistently clutch in this sense, I still wouldn’t be that excited by it. This reminds me of a Bill James’ statement that a situational effect is only meaningful if we understand the process that could cause this situational effect. In this setting, it would be hard to think of some reasoning or rationale that would cause Davis to more likely hit home runs in important situations.</li>
</ul>
</section>
</section>
<section id="is-a-pitchers-winloss-record-meaningful" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="is-a-pitchers-winloss-record-meaningful"><span class="header-section-number">7</span> Is a Pitcher’s Win/Loss Record Meaningful?</h2>
<section id="introduction-3" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="introduction-3"><span class="header-section-number">7.1</span> Introduction</h3>
<p>I recently picked up the book <em>State of Play</em> by Bill Ripken at my local library. Ripken questions whether advanced statistics accurately reflect the reality of the game of baseball. I am currently reading Chapter 6 where Ripken has issues with the belief among the analytics community that pitching wins do not matter. In contrast, Ripken believes that a pitcher’s win/loss record is informative about a pitcher beyond his other pitching measures such as ERA, SO, BB, etc. Specifically, if you compare two similar pitchers Pitcher A and Pitcher B, where Pitcher A has a superior win/loss record, Ripken thinks that Pitcher A tends to perform well in clutch situations during a game. In my years of research on clutch situations in baseball, I think that beliefs in player clutch ability tend to be overstated, so I am not sure I would agree with Ripken’s statements. But I thought an exploration of the usefulness of a pitcher’s W/L record might lead to an interesting study.</p>
<p>To get started, I sent off an email message to Tom Tango asking for some guidance how to assess the value of a pitcher’s win/loss record. Tom was kind to offer the following quick response:</p>
<p>“W/L records are useful… if you have nothing at all. But once you have a pitcher’s RA/9, and you have his Run Support, THEN the W/L record <em>might</em> give you additional information.&nbsp; Maybe. So, figure out the Pythag record of a pitcher using his RA/9 and his run support, and compare that to his actual W/L record.&nbsp; Better at the career level.”</p>
<p>I will try out Tom’s idea and see what we learn about a pitcher’s W/L record beyond what would be predicted by the Pythagorean formula from the runs scored (R) and runs allowed (RA).</p>
</section>
<section id="data-work" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="data-work"><span class="header-section-number">7.2</span> Data Work</h3>
<p>I decided to focus on the career statistics for all pitchers who debuted in the 1955 season or later and had at least 250 pitching decisions (I wanted to include Sandy Koufax who had a sterling 165-87 career W/L record.). There were 171 pitchers in this group. The standard statistics using the Lahman database only include the runs allowed by the pitcher, not the runs scored by the pitcher’s team. So I went through all of the Retrosheet play-by-play season files. For each inning where the pitcher pitched, I collected the runs scored and the runs allowed. For convenience, I ignored the situation where the pitcher only pitched part of the inning – an inning was credited to a pitcher if he started the inning. For each pitcher in my group, I collect the career wins (W), losses (L), runs scored (R) and runs allowed (RA).</p>
</section>
<section id="sandy-koufax" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="sandy-koufax"><span class="header-section-number">7.3</span> Sandy Koufax</h3>
<p>Since I was originally thinking about Sandy Koufax, I have that Koufax had a 165-87 W/L record in his career. For the innings that he pitched, Koufax had 1152 runs scored and 846 runs allowed. Based on the Pythagorean relationship (to be described shortly), we will compute that, based on this runs data, Koufax is expected to win 160.3 games. So Koufax won 165 - 160.3 = 4.7 more games than expected.</p>
</section>
<section id="some-graphs" class="level3" data-number="7.4">
<h3 data-number="7.4" class="anchored" data-anchor-id="some-graphs"><span class="header-section-number">7.4</span> Some Graphs</h3>
<p>If you read “The Relation Between Runs and Wins” chapter in the Second Edition of <em>Analyzing Baseball Data with R</em>, you’ll see that there tends to be a linear relationship between the logarithm of the ratio of a teams wins and losses <span class="math inline">\(\log (W / L)\)</span> and the logarithm of the ratio of a teams runs scored to runs allowed <span class="math inline">\(\log (R / RA)\)</span>. Baseball Reference indicates that the slope of this Pythagorean relationship is about 1.81. So I will graph a pitcher’s career <span class="math inline">\(\log (W / L)\)</span> value against his career <span class="math inline">\(\log (R / RA)\)</span> and overlay a line corresponding to the Pythagorean relationship. If a pitcher’s point in this graph is above the line, that indicates that he wins more games than would be anticipated by the runs/runs allowed data.</p>
<p>First I constructed a scatterplot for all pitchers with winning career records. Many of the points do follow the Pythagorean line. But I notice many pitchers with points below the line – these pitchers win less games than expected giving the runs data. There is one extreme pitcher Lindy McDaniel (point on the lower right) where his team scored 2040 runs while he allowed 859 runs – his 141-119 W/L record was much weaker than one would expect based on the runs data. (I think I should look more carefully at McDaniel’s data to see if this is correct.)</p>
<p><img src="figures/clutch/clutch13.png" class="img-fluid" style="width:70.0%"></p>
<p>Since we are primarily interested in studying the better pitchers, I constructed a new scatterplot for those pitchers who won at least 55% of their game decisions. For these pitchers, the Pythagorean line seems to provide a good fit to the general pattern.</p>
<p><img src="figures/clutch/clutch14.png" class="img-fluid" style="width:70.0%"></p>
<p>In this group of pitchers, let’s explore the residuals where I define a residual as</p>
<p>Residual = <span class="math inline">\(\log(W / L) - 1.81 \log (R / RA)\)</span></p>
<p>Here’s a graph of the residuals with a horizontal comparison line at 0. The large residuals in absolute value tend to be negative – there are a number of pitchers where the winning percentage is significantly smaller than the prediction based on the Pythagorean formula.</p>
<p><img src="figures/clutch/clutch15.png" class="img-fluid" style="width:70.0%"></p>
</section>
<section id="some-unusual-pitchers" class="level3" data-number="7.5">
<h3 data-number="7.5" class="anchored" data-anchor-id="some-unusual-pitchers"><span class="header-section-number">7.5</span> Some Unusual Pitchers</h3>
<p>Here are some lists of the extreme residuals among the pitchers with at least a 55% winning percentage. To make these easier to understand, I express these residuals on the wins scale. The Pythagorean relationship can be written in terms of the proportion of wins P:</p>
<p><span class="math inline">\(P = \frac{(R / RA)^{1.81}}{1 + (R / RA)^{1.81}}\)</span></p>
<p>By multiplying these proportions by the number of decisions (W + L), one obtains the expected number of wins for all pitchers. I first show a list of the top positive residuals – these are the pitchers who win (W) more than expected (EW) based on the runs data. Then I display the top negative residuals – these pitchers who win less than expected. On the top list, we see several great pitchers such as Randy Johnson and Roger Clemens – they won 13.6 and 11.2 more games than expected based on the Pythagorean model. In contrast, John Candelaria had by far the largest negative residual – he won 23.3 fewer games than expected from the model.</p>
<pre><code>  Pitcher           W    EW    RW
  &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Randy Johnson   303  289.  13.6
2 Bob Welch       211  200.  11.3
3 Roger Clemens   354  343.  11.2
4 Kevin Brown     211  200.  10.5
5 Dave McNally    184  177.   7.2
6 Don Sutton      324  317    7  

  Pitcher             W    EW    RW
  &lt;chr&gt;           &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 John Candelaria   177  200. -23.3
2 Jim Perry         215  238. -22.7
3 Fergie Jenkins    284  305. -21.3
4 Luis Tiant        229  247. -17.7
5 John Smoltz       213  229. -15.8
6 Don Drysdale      209  222. -13.1</code></pre>
</section>
<section id="takeaways" class="level3" data-number="7.6">
<h3 data-number="7.6" class="anchored" data-anchor-id="takeaways"><span class="header-section-number">7.6</span> Takeaways</h3>
<ul>
<li><p>Is a pitcher’s W/L record meaningful? Looking at pitcher career W/L records, the Pythagorean relationship appears to provide reasonable predictions of a pitcher’s winning percentage from his ratio of runs scored to runs allowed. The deviations from the Pythagorean relationship tend to be larger on the negative side – these pitchers win less games than predicted based on their career values of R and RA.</p></li>
<li><p>Interesting pitchers. One interesting takeaway was that the “extreme” pitchers tended to win fewer games than expected due to the Pythagorean relationship. By looking at the season-to-season performance of these pitchers, one may get additional insight on why they won fewer games.</p></li>
<li><p>Looking at wins at a finer level? Bill Ripken believes that the winning pitchers tend to make the good pitchers at crucial points during a game. A careful investigation of this claim would be a different study that focuses on the pitch values of specific games. Do better pitchers tend to throw good pitches during important situations?</p></li>
<li><p>My belief? I would agree with Tom Tango that a pitcher’s win/loss record by itself is informative about the quality of a pitcher. But this study doesn’t appear to help the case for the usefulness of a pitcher’s W/L record beyond the multitude of other pitching measures. One understands a pitcher’s W/L record by just seeing the runs scored and runs allowed. It is unfortunate that the media use a pitcher’s W/L record to decide on pitching awards – wins and losses are really a measure of the quality of a team rather than the quality of a particular starting pitcher.</p></li>
</ul>
</section>
</section>
<section id="clutch-hitters-in-2024---a-runs-added-approach" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="clutch-hitters-in-2024---a-runs-added-approach"><span class="header-section-number">8</span> Clutch Hitters in 2024 - A Runs Added Approach</h2>
<section id="introduction-4" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="introduction-4"><span class="header-section-number">8.1</span> Introduction</h3>
<p>In Chapter 5 of our ABDWR book, we discuss the process of constructing the runs expectancy table that gives the average number of runs scored in the remainder of the inning for each bases/outs situation. Using these runs expectancies, one can find the runs value of any play. By accumulating these runs values over a season for each player, one obtains the player “Base-Out Runs Added” measure (abbreviated by RE24) that is given in the Player Win Probability table in Baseball Reference.</p>
<p>There are two types of performance measures described in Chapter 2 of Sean Smith’s WAR in Pieces book. (By the way, although I haven’t finished this book, I’d recommend this to anyone who wishes to learn about the components of the WAR measure.) Many of the measures like AVG, SLG, OBP, wOBA are context-neutral – they don’t depend on the situation (runners on base and number of outs) that the batters face. Other measures such as RE24 do depend on the context. Measures like RE24 and RBI give explicit credit for getting hits when there are runners in scoring position.</p>
<p>That raises a question. When you look at Corey Seager’s 2024 season value of RE24 = 35.4, how do you interpret this? Did Seager achieve these runs added because he was a good hitter, or maybe he was just good in hitting in clutch situations with runners on base? In other words, good hitting and clutch hitting are confounded in the construction of the RE24 measure. Is there a way of removing the clutch aspect from the RE24 measure to get a “context-neutral” adjusted RE24 that better reflects batter ability?</p>
<p>In this post, we’ll describe a simulation approach for removing the clutch component from the RE24 measure. In doing this, it will be possible to give a new measure of clutch performance. We’ll see that Seager actually was a clutch hitter in the 2024 season.</p>
</section>
<section id="a-model-for-a-player-who-has-not-clutch-ability" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="a-model-for-a-player-who-has-not-clutch-ability"><span class="header-section-number">8.2</span> A Model for a Player Who Has Not Clutch Ability</h3>
<p>We define a state as the runners on base and the number of outs – for example, the state “010 1” refers to the situation where there is a runner on 2nd and there is 1 out. For each of Corey Seager’s plate appearances, we collect the state and the outcome. (For the purposes of this description, we need to record only one of the 6 outcomes 1B, 2B, 3B, HR, BB, and Out, where BB includes a IBB, HBP or catcher interference.).</p>
<p>Suppose Seager is not clutch in that his chance of any PA outcome does not depend on the state. In this season, Seager had 81 singles, 21 doubles, 30 home runs, 53 walks, and the remaining outs, and all possible permutations of these outcomes are equally likely over the states. This suggests a simple way of obtaining a “clutch-free” RE24 measure:</p>
<ul>
<li><p>Randomly permute the outcomes over the 533 states that Seager faced in this season.</p></li>
<li><p>Find the new states given the original states and the outcomes. (This requires a definition of runner advancement to be defined shortly.)</p></li>
<li><p>Compute the runs values using these state to new state transitions and runs scored.</p></li>
<li><p>Sum the runs values to obtain RE24.</p></li>
<li><p>Repeat this process many times to get many RE24 values. The mean of these RE24 values is my clutch-free RE24 estimate.</p></li>
</ul>
<p>Since we are changing the outcomes over the states, we need to give a rule for runner advancement to obtain the new states. I use a simple rule where a single advances runners two bases and a double advances runners three bases. I certainly could improve this rule to make it more realistic, but I believe the clutch measure won’t depend much on this runner advancement definition.</p>
</section>
<section id="corey-seager" class="level3" data-number="8.3">
<h3 data-number="8.3" class="anchored" data-anchor-id="corey-seager"><span class="header-section-number">8.3</span> Corey Seager</h3>
<p>Let’s try this procedure for the 2024 Corey Seager. I run this permutation simulation 200 times, obtaining 200 values of RE24 under the “not-clutch” model. Here is a histogram of the RE24 values. If Seager truly is a non-clutch player where his outcomes don’t depend on the situation, we anticipate that he will get a RE24 measure in the high 20’s, although there is certainly uncertainty in these RE24 values.</p>
<p><img src="figures/clutch/clutch16.png" class="img-fluid" style="width:70.0%"></p>
</section>
<section id="a-measure-of-clutch" class="level3" data-number="8.4">
<h3 data-number="8.4" class="anchored" data-anchor-id="a-measure-of-clutch"><span class="header-section-number">8.4</span> A Measure of Clutch</h3>
<p>We can take the mean of these simulated RE24 values to be the measure of RE24 adjusted for the situation. Here it turns out to be AVG = 28.3 runs added.</p>
<p>Actually (assuming my runner advancement definition), Seager contributed 41.0 runs this season which is shown by the black vertical line in the display. Seager was a good hitter in clutch situations where there were runners on base. We can measure clutch by a Z-score that subtracts the mean and divides by the standard deviation, where the mean and standard deviation are computed from this non-clutch model. Here we obtain</p>
<p><span class="math display">\[
Z = \frac{41.0 - 28.3} {5.6} = 2.27
\]</span></p>
<p>Actually Seager was very clutch in the sense that his observed runs was over 2 standard deviations over the mean under the non-clutch model.</p>
</section>
<section id="takeaways-1" class="level3" data-number="8.5">
<h3 data-number="8.5" class="anchored" data-anchor-id="takeaways-1"><span class="header-section-number">8.5</span> Takeaways</h3>
<ul>
<li><p>I did apply this RE24 adjustment for all hitters in the 2024 season, but I think I’ll postpone that work for a future post. I think it is worth summarizing the main points here.</p></li>
<li><p>Some measures like RBI and RE24 depend on the situation (runners on base) and so it is hard to interpret these measures since they include both hitter ability and clutch performances.</p></li>
<li><p>It is desirable to adjust RE24 for the context to obtain a “context-free” measure of performance.</p></li>
<li><p>We propose a model where batting outcome is independent of the state. By simulating from the model, we obtain replicates of RE24 that don’t depend on the state.</p></li>
<li><p>This gives us a state-free RE24 measure to be mean of the simulated RE24 values from the model.</p></li>
<li><p>By compare the actual RE24 measurement with this state-free measure, we obtain a measure of clutch performance. Using this measure, we found that Corey Seager was very clutch in 2024.</p></li>
<li><p>Despite beliefs that players like David Ortiz and Reggie Jackson are clutch, clutch performances tend not to be predictive. So I have no reason to believe that Seager will be clutch in the 2025 season.</p></li>
<li><p>I’ve written a bit on clutch performances in baseball. This page collects many of my posts on clutch performances of players or teams.</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>