<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jim Albert">
<meta name="dcterms.date" content="2023-01-01">

<title>Runs Expectancy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="Runs_Expectancy_files/libs/clipboard/clipboard.min.js"></script>
<script src="Runs_Expectancy_files/libs/quarto-html/quarto.js"></script>
<script src="Runs_Expectancy_files/libs/quarto-html/popper.min.js"></script>
<script src="Runs_Expectancy_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Runs_Expectancy_files/libs/quarto-html/anchor.min.js"></script>
<link href="Runs_Expectancy_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Runs_Expectancy_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Runs_Expectancy_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Runs_Expectancy_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Runs_Expectancy_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="toc-section-number">1</span>  Introduction</a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started"><span class="toc-section-number">2</span>  Getting Started</a>
  <ul class="collapse">
  <li><a href="#downloading-retrosheet-data" id="toc-downloading-retrosheet-data" class="nav-link" data-scroll-target="#downloading-retrosheet-data"><span class="toc-section-number">2.1</span>  Downloading Retrosheet Data</a></li>
  <li><a href="#computing-the-runs-values" id="toc-computing-the-runs-values" class="nav-link" data-scroll-target="#computing-the-runs-values"><span class="toc-section-number">2.2</span>  Computing the Runs Values</a></li>
  </ul></li>
  <li><a href="#summarizing-a-runs-expectancy-matrix" id="toc-summarizing-a-runs-expectancy-matrix" class="nav-link" data-scroll-target="#summarizing-a-runs-expectancy-matrix"><span class="toc-section-number">3</span>  Summarizing a Runs Expectancy Matrix</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1"><span class="toc-section-number">3.1</span>  Introduction</a></li>
  <li><a href="#basic-pattern" id="toc-basic-pattern" class="nav-link" data-scroll-target="#basic-pattern"><span class="toc-section-number">3.2</span>  Basic Pattern</a></li>
  <li><a href="#interpreting-the-fit" id="toc-interpreting-the-fit" class="nav-link" data-scroll-target="#interpreting-the-fit"><span class="toc-section-number">3.3</span>  Interpreting the Fit</a></li>
  <li><a href="#examining-the-residuals" id="toc-examining-the-residuals" class="nav-link" data-scroll-target="#examining-the-residuals"><span class="toc-section-number">3.4</span>  Examining the Residuals</a></li>
  <li><a href="#using-this-summary" id="toc-using-this-summary" class="nav-link" data-scroll-target="#using-this-summary"><span class="toc-section-number">3.5</span>  Using this Summary</a></li>
  </ul></li>
  <li><a href="#computing-the-woba-weights" id="toc-computing-the-woba-weights" class="nav-link" data-scroll-target="#computing-the-woba-weights"><span class="toc-section-number">4</span>  Computing the wOBA Weights</a>
  <ul class="collapse">
  <li><a href="#introduction-2" id="toc-introduction-2" class="nav-link" data-scroll-target="#introduction-2"><span class="toc-section-number">4.1</span>  Introduction</a></li>
  <li><a href="#runs-expectancy-matrix" id="toc-runs-expectancy-matrix" class="nav-link" data-scroll-target="#runs-expectancy-matrix"><span class="toc-section-number">4.2</span>  Runs Expectancy Matrix</a></li>
  <li><a href="#runs-value-of-play" id="toc-runs-value-of-play" class="nav-link" data-scroll-target="#runs-value-of-play"><span class="toc-section-number">4.3</span>  Runs Value of Play</a></li>
  <li><a href="#runs-value-of-an-outcome" id="toc-runs-value-of-an-outcome" class="nav-link" data-scroll-target="#runs-value-of-an-outcome"><span class="toc-section-number">4.4</span>  Runs Value of an Outcome</a></li>
  <li><a href="#computing-the-weights" id="toc-computing-the-weights" class="nav-link" data-scroll-target="#computing-the-weights"><span class="toc-section-number">4.5</span>  Computing the Weights</a></li>
  <li><a href="#bump-the-weights-so-that-outs-have-a-value-of-zero" id="toc-bump-the-weights-so-that-outs-have-a-value-of-zero" class="nav-link" data-scroll-target="#bump-the-weights-so-that-outs-have-a-value-of-zero"><span class="toc-section-number">4.6</span>  Bump the Weights So that Outs Have a Value of Zero</a></li>
  <li><a href="#scaling-woba" id="toc-scaling-woba" class="nav-link" data-scroll-target="#scaling-woba"><span class="toc-section-number">4.7</span>  Scaling wOBA</a></li>
  </ul></li>
  <li><a href="#visualizations-of-pitch-value" id="toc-visualizations-of-pitch-value" class="nav-link" data-scroll-target="#visualizations-of-pitch-value"><span class="toc-section-number">5</span>  Visualizations of Pitch Value</a>
  <ul class="collapse">
  <li><a href="#introduction-3" id="toc-introduction-3" class="nav-link" data-scroll-target="#introduction-3"><span class="toc-section-number">5.1</span>  Introduction</a></li>
  <li><a href="#review-of-balls-and-strikes-effects" id="toc-review-of-balls-and-strikes-effects" class="nav-link" data-scroll-target="#review-of-balls-and-strikes-effects"><span class="toc-section-number">5.2</span>  Review of Balls and Strikes Effects</a></li>
  <li><a href="#pitch-value" id="toc-pitch-value" class="nav-link" data-scroll-target="#pitch-value"><span class="toc-section-number">5.3</span>  Pitch Value</a></li>
  <li><a href="#graph-of-pitch-values" id="toc-graph-of-pitch-values" class="nav-link" data-scroll-target="#graph-of-pitch-values"><span class="toc-section-number">5.4</span>  Graph of Pitch Values</a></li>
  <li><a href="#values-of-four-seamers" id="toc-values-of-four-seamers" class="nav-link" data-scroll-target="#values-of-four-seamers"><span class="toc-section-number">5.5</span>  Values of Four-Seamers</a></li>
  <li><a href="#values-of-sliders" id="toc-values-of-sliders" class="nav-link" data-scroll-target="#values-of-sliders"><span class="toc-section-number">5.6</span>  Values of Sliders</a></li>
  <li><a href="#values-of-changeups" id="toc-values-of-changeups" class="nav-link" data-scroll-target="#values-of-changeups"><span class="toc-section-number">5.7</span>  Values of Changeups</a></li>
  <li><a href="#r-work" id="toc-r-work" class="nav-link" data-scroll-target="#r-work"><span class="toc-section-number">5.8</span>  R Work?</a></li>
  <li><a href="#further-reading-on-pitch-value" id="toc-further-reading-on-pitch-value" class="nav-link" data-scroll-target="#further-reading-on-pitch-value"><span class="toc-section-number">5.9</span>  Further Reading on Pitch Value</a></li>
  </ul></li>
  <li><a href="#beyond-runs-expectancy" id="toc-beyond-runs-expectancy" class="nav-link" data-scroll-target="#beyond-runs-expectancy"><span class="toc-section-number">6</span>  Beyond Runs Expectancy</a>
  <ul class="collapse">
  <li><a href="#introduction-4" id="toc-introduction-4" class="nav-link" data-scroll-target="#introduction-4"><span class="toc-section-number">6.1</span>  Introduction</a></li>
  <li><a href="#runs-scored-in-a-half-inning" id="toc-runs-scored-in-a-half-inning" class="nav-link" data-scroll-target="#runs-scored-in-a-half-inning"><span class="toc-section-number">6.2</span>  Runs Scored in a Half-Inning</a></li>
  <li><a href="#comparing-runs-scored-between-two-situations" id="toc-comparing-runs-scored-between-two-situations" class="nav-link" data-scroll-target="#comparing-runs-scored-between-two-situations"><span class="toc-section-number">6.3</span>  Comparing Runs Scored Between Two Situations</a></li>
  <li><a href="#advantage-in-all-situations" id="toc-advantage-in-all-situations" class="nav-link" data-scroll-target="#advantage-in-all-situations"><span class="toc-section-number">6.4</span>  Advantage in All Situations</a></li>
  <li><a href="#a-new-table" id="toc-a-new-table" class="nav-link" data-scroll-target="#a-new-table"><span class="toc-section-number">6.5</span>  A New Table</a></li>
  <li><a href="#graphing-the-effects" id="toc-graphing-the-effects" class="nav-link" data-scroll-target="#graphing-the-effects"><span class="toc-section-number">6.6</span>  Graphing the Effects</a></li>
  <li><a href="#why" id="toc-why" class="nav-link" data-scroll-target="#why"><span class="toc-section-number">6.7</span>  Why?</a></li>
  <li><a href="#a-statistical-note" id="toc-a-statistical-note" class="nav-link" data-scroll-target="#a-statistical-note"><span class="toc-section-number">6.8</span>  A Statistical Note</a></li>
  </ul></li>
  <li><a href="#beyond-runs-expectancy---some-background" id="toc-beyond-runs-expectancy---some-background" class="nav-link" data-scroll-target="#beyond-runs-expectancy---some-background"><span class="toc-section-number">7</span>  Beyond Runs Expectancy - Some Background</a>
  <ul class="collapse">
  <li><a href="#introduction-modeling-runs-scored-in-an-inning" id="toc-introduction-modeling-runs-scored-in-an-inning" class="nav-link" data-scroll-target="#introduction-modeling-runs-scored-in-an-inning"><span class="toc-section-number">7.1</span>  Introduction: Modeling Runs Scored in an Inning</a></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression"><span class="toc-section-number">7.2</span>  Logistic Regression</a></li>
  <li><a href="#more-cutpoints---ordinal-regression" id="toc-more-cutpoints---ordinal-regression" class="nav-link" data-scroll-target="#more-cutpoints---ordinal-regression"><span class="toc-section-number">7.3</span>  More Cutpoints - Ordinal Regression</a></li>
  <li><a href="#proportional-odds" id="toc-proportional-odds" class="nav-link" data-scroll-target="#proportional-odds"><span class="toc-section-number">7.4</span>  Proportional Odds</a></li>
  <li><a href="#comparing-runs-expectancy-with-ordinal-coefficients" id="toc-comparing-runs-expectancy-with-ordinal-coefficients" class="nav-link" data-scroll-target="#comparing-runs-expectancy-with-ordinal-coefficients"><span class="toc-section-number">7.5</span>  Comparing Runs Expectancy with Ordinal Coefficients</a></li>
  <li><a href="#takeaways" id="toc-takeaways" class="nav-link" data-scroll-target="#takeaways"><span class="toc-section-number">7.6</span>  Takeaways</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Runs Expectancy</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jim Albert </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 1, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>This document contains several articles from the “Exploring Baseball Data with R” blog on the general topic of runs expectancy which is a central topic in sabermetrics.</p>
<p>Section 2 describes the process of downloading play-by-play Retrosheet data for a specific season. Another function is helpful for computing the runs values for all of the plays that season.</p>
<p>Section 3 discusses the runs expectancy matrix which can be used to evaluate values of plays and different strategies during a game. This section describes the use of a graph to summarize the main patterns of this matrix.</p>
<p>A popular modern way to evaluate batting performance is the weighted on-base percentage or wOBA. We explain in Section 4 how to use Retrosheet play-by-play data to compute the weights of the different positive outcomes that are used in the wOBA.</p>
<p>Runs values are also helpful in evaluating pitches. Section 5 describes the concept of a pitch value and shows the value of different types of pitches over the zone.</p>
<p>One drawback of the runs expectancy matrix is that runs potential is measured solely by the mean runs in the remainder of the inning. Section 6 introduces a more general approach where runs are represented as an ordinal variable and one measures the advantage of a given situation by use of an ordinal regression model. Section 7 provides some background material on this ordinal response approach. This section provides some interesting comparisons between the runs expectancy table and the “runs advantage” table which displays the ordinal regression coefficient for all states.</p>
</section>
<section id="getting-started" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="getting-started"><span class="header-section-number">2</span> Getting Started</h2>
<section id="downloading-retrosheet-data" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="downloading-retrosheet-data"><span class="header-section-number">2.1</span> Downloading Retrosheet Data</h3>
<p>Here’s an outline of how to download the Retrosheet play files for a particular season.</p>
<p>There is a blog posting on this at https://baseballwithr.wordpress.com/2014/02/10/downloading-retrosheet-data-and-runs-expectancy/</p>
<ol type="1">
<li><p>Download the Chadwick files following the advice from the website mentioned on the blog post – this will parse the original source files.</p></li>
<li><p>I set up the current working director to have the following file structure.</p></li>
</ol>
<p><img src="figures/expectancy/folderstructure.png" class="img-fluid"></p>
<ol start="3" type="1">
<li>I download the R function <code>parse.retrosheet2.pbp.R()</code> from my gist site.</li>
</ol>
<!-- -->
<pre><code>library(devtools)
source_gist("https://gist.github.com/bayesball/8892981",
            filename="parse.retrosheet2.pbp.R")</code></pre>
<ol start="4" type="1">
<li>Now I am ready to download the Retrosheet play-by-play data for the 2021 season.</li>
</ol>
<!-- -->
<pre><code>parse.retrosheet2.pbp(2021)</code></pre>
<ol start="5" type="1">
<li>Two new files “all2021.csv” and “roster.csv” are stored in the “download.folder/unzipped” folder. Using the <code>read_csv()</code> function I read in the play-by-play data.</li>
</ol>
<!-- -->
<pre><code>library(readr)
d2021 &lt;- read_csv("download.folder/unzipped/all2021.csv",
                  col_names = FALSE)</code></pre>
<ol start="6" type="1">
<li>Last I want to add variable names to the header of the data file. I read a header file from our Github site and use this to assign the variable names.</li>
</ol>
<!-- -->
<pre><code>fields &lt;- read.csv("https://raw.githubusercontent.com/beanumber/baseball_R/master/data/fields.csv")
names(d2021) &lt;- fields[, "Header"]</code></pre>
<ol start="7" type="1">
<li>The data frame <code>d2021</code> is ready to explore. Here is the first row of the file.</li>
</ol>
<!-- -->
<pre><code>d2021[1, ]</code></pre>
</section>
<section id="computing-the-runs-values" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="computing-the-runs-values"><span class="header-section-number">2.2</span> Computing the Runs Values</h3>
<p>Once the Retrosheet play-by-play data is downloaded, then the function <code>compute.runs.expectancy()</code> will compute the runs values for all plays.</p>
<p>One can download this function from the Github Gist site.</p>
<pre><code>library(devtools)
source_gist("https://gist.github.com/bayesball/8892999",
            filename="compute.runs.expectancy.R")</code></pre>
<p>Assuming the file “all2021.csv” is stored in the working directory, the following command will read in the csv file, compute the runs values and store the resulting data frame as `d2021’.</p>
<pre><code>d2021 &lt;- compute.runs.expectancy(2021)</code></pre>
<p>The following command will output the current state <code>STATE</code>, the new state <code>NEW.STATE</code> and the <code>RUNS.VALUE</code> for the first few plays in the season file.</p>
<pre><code>library(dplyr)
d2018 %&gt;% 
  select(STATE, NEW.STATE, RUNS.VALUE) %&gt;% 
  head()</code></pre>
</section>
</section>
<section id="summarizing-a-runs-expectancy-matrix" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="summarizing-a-runs-expectancy-matrix"><span class="header-section-number">3</span> Summarizing a Runs Expectancy Matrix</h2>
<section id="introduction-1" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="introduction-1"><span class="header-section-number">3.1</span> Introduction</h3>
<p>A basic object in sabermetrics research is the Runs Expectancy Matrix that gives the mean number of runs scored in the remainder of the inning for each possible state (number of outs and runners on base) of a half-inning. This FanGraphs page provides a general description of this matrix and why it is so useful in baseball analyses. Chapter 5 of Analyzing Baseball With R describes how to construct this matrix from Retrosheet data and illustrates the use of this matrix to measure the values of plays. Here is the matrix for the 2019 season. For example, reading the “1 out, 023 runners” entry, this says that, on average, there will be 1.42 runs scored in the remainder of the inning when there is 1 out and runners on 2nd and 3rd.</p>
<p><img src="figures/expectancy/runs0.png" class="img-fluid" style="width:70.0%"></p>
<p>I am interested in exploring how the values in this matrix have changed over twenty seasons of Major League Baseball. Since the nature of run scoring has changed dramatically during the Statcast Era (due to the increasing count of home runs), I would think that this matrix would be changing in interesting ways.</p>
<p>If we focus on the top left entry (000 with no outs) of the matrix, this graph shows how the runs expectancy for this situation has changed in the 20-year period from 2000 to 2019. We see a decline in average run production from 2006 to 2014 followed by a steady rise in the Statcast era from 2015 to 2019.</p>
<p><img src="figures/expectancy/runs1.png" class="img-fluid" style="width:70.0%"></p>
<p>To see the changes in the expectancy matrix over this period, I thought it would be helpful to summarize this matrix by use of a few numbers. If this could be done, it would facilitate comparisons across seasons. Here I present an attractive way to visualize and summarize the values in this 3 by 8 runs matrix.</p>
</section>
<section id="basic-pattern" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="basic-pattern"><span class="header-section-number">3.2</span> Basic Pattern</h3>
<p>If you look at the runs expectancy matrix, note that I have arranged the runners on base values so that for a specific row (number of outs) the run values increase from left to right. What is the nature of this increase? Let’s define a Bases Score equal to the sum of bases occupied plus one if there is more than one runner on base, that is</p>
<p>Bases Score = Sum(bases occupied) + I(# of Runners &gt; 1)</p>
<p>where I() is the indicator function (1 if the argument is true and 0 otherwise). The Score values will go from 0 to 7 corresponding to the 8 columns of the matrix. Let’s graph the run values in the matrix as a function of the Score and fit a line to the points for each number of outs. Interestingly, we see three linear relations that appear to be a good fit to this data.</p>
<p><img src="figures/expectancy/runs2.png" class="img-fluid" style="width:70.0%"></p>
<p>I have a data frame RE with three variables – <code>Runs</code>, <code>Score</code> (numeric) and <code>Outs</code> (categorical). To find the equations of these three lines, I fit a linear model to Runs where there is an interaction between Score and Outs. This model allows for varying intercepts and varying slopes among the three values of Outs.</p>
<pre><code>fit &lt;- lm(Runs ~ Outs * Score, data = RE)</code></pre>
</section>
<section id="interpreting-the-fit" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="interpreting-the-fit"><span class="header-section-number">3.3</span> Interpreting the Fit</h3>
<p>This fit provides intercepts and slopes for the three fitted lines corresponding to the three Outs values.</p>
<pre><code>##   Outs Intercept Slope
## 1    0      0.64  0.24
## 2    1      0.35  0.18
## 3    2      0.13  0.08</code></pre>
<ul>
<li><p>The intercepts give estimates of the Runs when there are no runners on base (Score = 0). With the bases empty, we expect the team will score 0.64, 0.35, and 0.13 runs with 0, 1, and 2 outs, respectively.</p></li>
<li><p>The slopes give the increase in Runs when the Score value increases by one. When there are no outs, each unit increase in Score will increase the expected Runs by 0.24. So if a runner on first successfully steals second with no outs, the Score increases by one and the Runs increases by 0.24. Suppose there is a runner on 1st with no outs and there is a walk. One is transitioning from the 100 state (Score = 1) to 120 state (Score = 4) and so the Runs would increase by 3 (0.24) = 0.72.</p></li>
<li><p>Similarly, when there is one out, there will be a 0.18 increase in Runs for each unit increase in Score, and when there are two outs, there will be a 0.08 increase in Runs for each unit increase in Score. So for example, a walk with a runner on 1st, two outs, will increase the Runs by 3 (0.08) = 0.24.</p></li>
<li><p>The fitted slopes clearly shows the effect of outs on run scoring. An event that improves the bases situation has more runs impact with 0 outs compared to one or two outs.</p></li>
</ul>
</section>
<section id="examining-the-residuals" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="examining-the-residuals"><span class="header-section-number">3.4</span> Examining the Residuals</h3>
<p>Of course, these lines don’t provide a perfect fit, and so we’re interested in exploring the vertical deviations (the residuals) for additional insight. Here I plot the residuals as a function of the Score using different colors for the Outs values. What do I see?</p>
<p><img src="figures/expectancy/runs3.png" class="img-fluid" style="width:70.0%"></p>
<ul>
<li><p>Although the sizes of the residuals are small relative to the fitted values, there is a clear pattern – NEGATIVE (bases empty), POSITIVE (one runner), NEGATIVE (two runners), POSITIVE (bases loaded). I could remove this general pattern with a more sophisticated fit, but I would lose the simple interpretation of the linear fit.</p></li>
<li><p>There are some interesting large residuals, 000 with no outs (LARGE NEGATIVE), 003 with 0 or 1 out (LARGE POSITIVE), and 120 with one out (LARGE NEGATIVE). Since there are multiple ways to advance a runner on 3rd with less than 2 outs (sac fly, wild pitch or passed ball), I am not surprised about the large positive residuals for 003 with 0 or 1 out. Perhaps the multiple ways to get outs in the 120 situation account for the large negative residual.</p></li>
</ul>
</section>
<section id="using-this-summary" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="using-this-summary"><span class="header-section-number">3.5</span> Using this Summary</h3>
<p>Sometime next year, I’ll post something related to run production in the last 20 years of baseball. But here are some thoughts about these summaries of the runs expectancy matrix.</p>
<ul>
<li><p>The Slopes. The main takeaway are the slopes 0.24, 0.18, and 0.08 which give the improvement in expected runs for each increase in the Bases Score variable. These are easy to remember and can be used in game situations. Suppose a manager wants to quickly compute the run value of a double that scores a runner on first with one out. The runners state has changed from 100 to 020 – since the change in Bases Score is 1, there is an advantage of 0.18 runs. Adding that to the single run scored, the runs value of this particular double is 0.18 + 1 = 1.18.</p></li>
<li><p>Comparing Seasons. We have summarized the runs expectancies by six numbers – the three intercepts and the three slopes. One can compare run scoring of two seasons by comparing the intercepts or by comparing the slopes. We did illustrate comparison of average run scoring across twenty seasons which is a comparison of the intercepts with no outs.</p></li>
<li><p>Impact of HR Hitting? One question is how the home run hitting impacts the run expectancy matrix. For example, if a team is really focusing on hitting home runs, what is the advantage of moving a runner from first to second? This is a question related to the slope summaries.</p></li>
<li><p>Beyond Mean Runs. It would also be interesting to see how home run hitting affects other metrics such as the probability of scoring from a given state. Some years ago, I wrote a paper “Beyond Runs Expectancy” published in the Journal of Sports Analytics that looked at distributions of run scoring and how they change across different situations.</p></li>
</ul>
</section>
</section>
<section id="computing-the-woba-weights" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="computing-the-woba-weights"><span class="header-section-number">4</span> Computing the wOBA Weights</h2>
<section id="introduction-2" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="introduction-2"><span class="header-section-number">4.1</span> Introduction</h3>
<p>We start with the definition of <span class="math inline">\(wOBA\)</span> as given on the FanGraphs web site.</p>
<p><span class="math display">\[
wOBA = \frac{w_1 uBB + w_2 HBP + w_3 1B + w_4 2B + w_5 3B + w_6 HR}{AB + BB - IBB + SF + HBP}
\]</span></p>
<p>There are several features of this formula:</p>
<ul>
<li><p>The weights <span class="math inline">\(w_1, ..., w_6\)</span> are proportional to their runs values.</p></li>
<li><p>Note that the denominator includes all batting plays with the exception of intentional walks (<span class="math inline">\(IBB\)</span>). Note that the outcome “out” does not appear in the numerator. Implicitly, this means that the weights for all “out” events are equal to zero.</p></li>
<li><p>To be similar to the <span class="math inline">\(OBP\)</span> formula, we will see that we need to bump our weights so that the value assigned to the out outcome is zero.</p></li>
<li><p>In addition, there is a scaling factor to include so that the average <span class="math inline">\(wOBA\)</span> value is equal to the average <span class="math inline">\(OBP\)</span> across all players in the given season.</p></li>
</ul>
</section>
<section id="runs-expectancy-matrix" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="runs-expectancy-matrix"><span class="header-section-number">4.2</span> Runs Expectancy Matrix</h3>
<p>To describe the process of obtaining the weights in the <span class="math inline">\(wOBA\)</span> formula, we begin by finding the runs expectancy matrix.</p>
<p>A state of an half-inning consists the number of outs and the runners on base. Since there are three possible outs (0, 1, 2) and eight possible configurations of runners on base (each base can be occupied or not), there are 3 <span class="math inline">\(\times\)</span> 8 = 24 possible states. For each state, we find the average number of runs scored in the remainder of the half-inning. If we do this for all states, we obtain the runs expectancy matrix.</p>
<p>Here is this matrix using all plays from the 2022 season:</p>
<pre><code>    000   001   010   011   100   101   110   111
0 0.477 1.231 1.092 2.000 0.863 1.765 1.443 2.396
1 0.256 0.973 0.672 1.398 0.505 1.147 0.901 1.524
2 0.097 0.378 0.306 0.548 0.207 0.500 0.436 0.768</code></pre>
</section>
<section id="runs-value-of-play" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="runs-value-of-play"><span class="header-section-number">4.3</span> Runs Value of Play</h3>
<p>For any batting play, there are two states:</p>
<ul>
<li><span class="math inline">\(STATE_0\)</span>, the state of the inning when the hitter comes to bat</li>
<li><span class="math inline">\(STATE_1\)</span>, the state of the inning after the batting play</li>
</ul>
<p>The runs value (<span class="math inline">\(Value\)</span>) of the batting play is defined as the difference in the runs value of the two states plus the runs scored on the play (<span class="math inline">\(RUNS\)</span>).</p>
<p><span class="math display">\[
Value = Runs(STATE_1) - Runs(STATE_0) + RUNS
\]</span></p>
<p>Using this formula, we can compute the value of all batting plays in the 2022 season.</p>
</section>
<section id="runs-value-of-an-outcome" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="runs-value-of-an-outcome"><span class="header-section-number">4.4</span> Runs Value of an Outcome</h3>
<p>Suppose we are interested in the runs value of a particular batting outcome, say a home run. We average the runs values for all home runs hit in the 2022 season. We obtain the value of a home run hit in 2022 is 1.4. This likely seems small, but most home runs are hit with no runners on base and even when there are men on base, the runs value of the after state (bases are empty) will be smaller than the runs value of the state with runners on base.</p>
</section>
<section id="computing-the-weights" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="computing-the-weights"><span class="header-section-number">4.5</span> Computing the Weights</h3>
<p>In a similar fashion, we can compute the runs value for all six events (unintentional walk, hit-by-pitch, single, double, triple, home run) and we obtain the following weights. The table gives the name of each event with the corresponding value of the variable <code>EVENT_CD</code> in the Retrosheet dataset.</p>
<pre><code>  Event EVENT_CD Weight
  &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt;
1 uBB         14  0.316
2 HBP         16  0.347
3 1B          20  0.458
4 2B          21  0.770
5 3B          22  1.02 
6 HR          23  1.40 </code></pre>
</section>
<section id="bump-the-weights-so-that-outs-have-a-value-of-zero" class="level3" data-number="4.6">
<h3 data-number="4.6" class="anchored" data-anchor-id="bump-the-weights-so-that-outs-have-a-value-of-zero"><span class="header-section-number">4.6</span> Bump the Weights So that Outs Have a Value of Zero</h3>
<p>Actually, we can compute the runs value of all outcomes of a plate appearance. In particular, we note that outs have a value of <span class="math inline">\(-0.26\)</span>. Since the value of outs is 0 in the definition of OBP, we want to adjust all of our event values so that out has a value of 0. We do this adjustment by adding 0.26 to the values of the six events, obtaining the new weights displayed below.</p>
<pre><code>  Event EVENT_CD Weight
  &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt;
1 uBB         14  0.576
2 HBP         16  0.607
3 1B          20  0.718
4 2B          21  1.03 
5 3B          22  1.28 
6 HR          23  1.66 </code></pre>
</section>
<section id="scaling-woba" class="level3" data-number="4.7">
<h3 data-number="4.7" class="anchored" data-anchor-id="scaling-woba"><span class="header-section-number">4.7</span> Scaling wOBA</h3>
<p>Last, we want to rescale the <span class="math inline">\(wOBA\)</span> value so the the mean <span class="math inline">\(wOBA\)</span> matches the mean on-base percentage <span class="math inline">\(OBP\)</span>.</p>
<p>By applying the <span class="math inline">\(wOBA\)</span> formula to all batting plays, we obtain</p>
<p><span class="math display">\[
Mean(wOBA) = 0.2521
\]</span></p>
<p>Since the average <span class="math inline">\(OBP\)</span> for all players in the 2022 season is .310, our adjusted <span class="math inline">\(wOBA\)</span> is given by</p>
<p><span class="math display">\[
wOBA_{adj} = \frac{0.310}{0.2521} wOBA.
\]</span></p>
<p>With this adjustment, we obtain the following new weights.</p>
<pre><code>    Event EVENT_CD Weight adj_Weight
  &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt;      &lt;dbl&gt;
1 uBB         14  0.576      0.708
2 HBP         16  0.607      0.747
3 1B          20  0.718      0.883
4 2B          21  1.03       1.27 
5 3B          22  1.28       1.57 
6 HR          23  1.66       2.05</code></pre>
<p>For comparison, I have added the 2022 wOBA weights as reported on the FanGraphs website.</p>
<pre><code>   Event EVENT_CD Weight adj_Weight FanGraphs
  &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
1 uBB         14  0.576      0.708     0.689
2 HBP         16  0.607      0.747     0.72 
3 1B          20  0.718      0.883     0.884
4 2B          21  1.03       1.27      1.26 
5 3B          22  1.28       1.57      1.60 
6 HR          23  1.66       2.05      2.07  </code></pre>
<p>Note that our adjusted weights agree pretty closely with the FanGraphs weights. There are small discrepancies, but essentially we have reproduced the FanGraphs wOBA formula from the raw Retrosheet data.</p>
</section>
</section>
<section id="visualizations-of-pitch-value" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="visualizations-of-pitch-value"><span class="header-section-number">5</span> Visualizations of Pitch Value</h2>
<section id="introduction-3" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="introduction-3"><span class="header-section-number">5.1</span> Introduction</h3>
<p>In last week’s post, we explored pitch decisions and the influence of the count on those decisions. For example, pitchers are most likely to throw off-speed pitches when they are ahead in the count. Also, the location of the pitch depends on the count. For example, on a 0-2 count, it is common for a pitcher to throw a low off-speed pitch or a high fastball. In contrast, when the pitcher is behind in the count, he is likely to throw a fastball in the middle of the zone. By use of density estimate graphs, we saw some interesting pitch location patterns for individual pitchers.</p>
<p>Here we focus on the outcome of the pitch and how that outcome varies as a function of the pitch location. From the pitcher’s perspective, there are different ways to think about a desirable pitch outcome. During the plate appearance, the pitcher gains with a pitch resulting in an additional strike or loses with a pitch resulting in an additional ball. A pitch that ends the plate appearance with a strikeout or other out is a gain and a pitch that is put in-play for a hit is a loss for the pitcher. One way of measuring a desirable pitch outcome is by use of expected runs, specifically the runs gained (on average) from that pitch. We’ll review some of the material from the “Balls and Strikes Effects” chapter of <em>Analyzing Baseball with R</em>. Then we’ll use that material together with information about the runs value of different end-of-PA events to define pitch values. Once we have assigned a value to each pitch during the 2019 season, we can use graphs of a smoothed fit to understand the locations of the regions about the zone where a particular type of pitch is effective.</p>
</section>
<section id="review-of-balls-and-strikes-effects" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="review-of-balls-and-strikes-effects"><span class="header-section-number">5.2</span> Review of Balls and Strikes Effects</h3>
<p>In Chapter 6 of ABWR we explain how to measure balls and strikes effects. Using Retrosheet play-by-play data, we first compute (from Chapter 5 work) the runs value for each plate appearance outcome that changes the state (runners on base, number of outs and runs scored). Next, we define variables c01, c10, c11, etc. that indicate if the count for a plate appearance passes through the respective counts 0-1, 1-0, 1-1, etc. By averaging the run values over each of these indicator variables, we obtain the mean run value passing through each possible count. I’ve displayed these mean run values in the following figure using 2019 season data – these are similar to the values displayed in ABWR, Figure 6.2 from data from an earlier season.</p>
<p><img src="figures/expectancy/runs5.png" class="img-fluid" style="width:70.0%"></p>
<p>We also can compute the runs value of each possible end-of-PA event (out, single, walk, HBP, strikeout, etc) by averaging the run values. We learn for example, that an out loses on average 0.28 runs and a single and home run, gain on average 0.46 and 1.38 runs, respectively. Note that these run values are averages and don’t depend on the current situation of runners and outs.</p>
</section>
<section id="pitch-value" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="pitch-value"><span class="header-section-number">5.3</span> Pitch Value</h3>
<p>Once we’ve computed the runs value for each possible count and each end-of-PA event, then the value of a pitch is simply the change in runs value</p>
<p>Pitch Value = Runs Value (new count or end of PA event) - Runs Value (old count).</p>
<p>For example, suppose the count is 1-1 and the pitcher throws a ball, changing the count to 2-1. The value of that pitch (using numbers from the above figure) is</p>
<p>Value = Runs Value (2-1) - Runs Value (1-1) = 0.035 - (-0.015) = 0.050</p>
<p>Here a pitch adding a ball has a runs value of 0.05 favorable to the hitter. Suppose a batter hits a home run on an 0-2 pitch. The value of this pitch is</p>
<p>Value = Runs Value (HR) - Runs Value (0-2) = 1.38 - (-0.103) = 1.48.</p>
<p>Note that the pitch value of this home run exceeds the average HR runs value since the home run was hit on a 0-2 pitch.</p>
</section>
<section id="graph-of-pitch-values" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="graph-of-pitch-values"><span class="header-section-number">5.4</span> Graph of Pitch Values</h3>
<p>Now that we have assigned values to all pitches, we are interested in seeing how the pitch value varies across the zone. I have already illustrated the use of the <code>CalledStrike</code> package in an earlier post to display patterns of smoothed fits of different batting measures, say launch speed or swinging rates, and so it is straightforward to use similar functions to display patterns of smoothed pitch values over the zone. Basically, one fits a generalized additive model where the pitch value is represented as a smooth function of the plate_x and plate_z variables, one uses the fitted model to predict the pitch value over a grid, and then graphs the fitted values by a filled contour graph.</p>
<p>Usually we think of desirable pitch locations from the pitcher’s perspective. So we will consider the negative of the runs values, so a positive pitch value is advantageous to the pitcher. The values of the two pitches above (a ball on a 1-1 count) and a home run on a 0-2 pitch will be recoded as -0.050 and -1.48 respectively. The color scheme in the plots below will be orange for locations desirable for the pitcher and yellow for locations desirable to the hitter.</p>
</section>
<section id="values-of-four-seamers" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="values-of-four-seamers"><span class="header-section-number">5.5</span> Values of Four-Seamers</h3>
<p>To begin, here is a contour graph display of the smoothed pitch values of all four-seam fastballs thrown in the 2019 season. Since the pattern of the values depends on the pitcher and batter sides, there are four displays, one for each combination of sides. Orange indicates a region advantageous to the pitcher and yellow indicates an advantage to the hitter. For a left-handed hitter (left side of the graph), for pitchers of both sides we see that a fastball is beneficial outside and high. We see a similar pattern of orange (high and outside) for right-handed hitters. It is interesting that southpaws also seem to have positive value for fastballs thrown inside to right-handed hitters. Clearly it is not desirable to throw a fastball in the middle of the zone.</p>
<p><img src="figures/expectancy/runs6.png" class="img-fluid" style="width:70.0%"></p>
</section>
<section id="values-of-sliders" class="level3" data-number="5.6">
<h3 data-number="5.6" class="anchored" data-anchor-id="values-of-sliders"><span class="header-section-number">5.6</span> Values of Sliders</h3>
<p>Here is a similar display for all sliders thrown by both sides of pitcher to both sides of batter. A right-handed pitcher (bottom row) wants to throw the slider to the outside, either low outside or high outside. For southpaw pitchers (top row), they want to throw their sliders outside to left-handed hitters and high outside to right-handed hitters. It is interesting that there appears to be some advantage for a leftie to throw low and inside to a right-handed hitter.</p>
<p><img src="figures/expectancy/runs7.png" class="img-fluid" style="width:70.0%"></p>
</section>
<section id="values-of-changeups" class="level3" data-number="5.7">
<h3 data-number="5.7" class="anchored" data-anchor-id="values-of-changeups"><span class="header-section-number">5.7</span> Values of Changeups</h3>
<p>Here is a visual display of the pitch values of changeups. Generally effective changeups are ones that are low and outside. Looking at the right-right confrontation (bottom-right), note the large white circle in the middle indicating that poorly located sliders tend to have negative consequences.</p>
<p><img src="figures/expectancy/runs8.png" class="img-fluid" style="width:70.0%"></p>
</section>
<section id="r-work" class="level3" data-number="5.8">
<h3 data-number="5.8" class="anchored" data-anchor-id="r-work"><span class="header-section-number">5.8</span> R Work?</h3>
<p>I have outlined all of my work creating the pitch values and graphing the smoothed values over the zone on my Github Gist site. There are several new functions in the <code>CalledStrike</code> package – the function <code>compute_pitch_values()</code> will compute the pitch values for a Statcast dataset and the function <code>pitch_value_contour()</code> will produce the type of filled contour plots shown here.</p>
</section>
<section id="further-reading-on-pitch-value" class="level3" data-number="5.9">
<h3 data-number="5.9" class="anchored" data-anchor-id="further-reading-on-pitch-value"><span class="header-section-number">5.9</span> Further Reading on Pitch Value</h3>
<p>The notion of pitch value has been around awhile in sabermetrics so there is a good literature on the subject. Here are some older references that I found including the first one by my ABWR coauthor Max (by the way, there is a graph in Max’s post of pitch values of sliders that resembles the one presented here).</p>
<ul>
<li><p>Pitch Run Value and Count by Max Marchi, The Hardball Times</p></li>
<li><p>Searching for the Game’s Best Pitch by John Walsh, The Hardball Times</p></li>
<li><p>Pitch Type Linear Weights by Steve Slowinski, FanGraphs</p></li>
<li><p>Run Value by Pitch Location by Dave Allen, The Baseball Analysts</p></li>
</ul>
</section>
</section>
<section id="beyond-runs-expectancy" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="beyond-runs-expectancy"><span class="header-section-number">6</span> Beyond Runs Expectancy</h2>
<section id="introduction-4" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="introduction-4"><span class="header-section-number">6.1</span> Introduction</h3>
<p>We begin by displaying the well-known runs expectancy table (data from the recent 2022 season) introduced by George Lindsey in 1963. It gives the average runs scored in the remainder of the inning for each situation defined by runners on base and number of outs.</p>
<p><img src="figures/expectancy/runs0.png" class="img-fluid" style="width:70.0%"></p>
<p>This table provides the foundation for the development of many measures of performance such as wOBA. However, it always has seemed a bit unsatisfying to me since it provides an incomplete view of run scoring potential. For example, when there is a single out and runners on 2nd and 3rd, we see from the table that teams will score an average of 1.42 runs. But this is only an average and does not directly inform us on the probability of not scoring or the probability of scoring 2 or 3 runs. It seems better to describe runs potential in a way that would say more about the future distribution of runs scored than just the mean.</p>
<p>Some years ago, I wrote a paper <em>Beyond Runs Expectancy</em> published in the <em>Journal of Sports Analytics</em> which models run scoring in a different way. Instead of focusing only on the average runs scored, I broke runs scored into the following 5 categories:</p>
<p>0 runs, 1 run, 2 runs, 3 runs, 4 or more runs</p>
<p>Then I used a popular regression model for ordinal outcomes to explore how run scoring differs between teams and how run scoring changes with respect to various situational effects like home vs away, runners on base, and so on. In this post, the plan is to introduce this modeling method and show how one can replace the runs expectancy table with a similar table (that I call a <em>Runs Advantage Table</em>) that gives us more information about the potential for scoring runs.</p>
</section>
<section id="runs-scored-in-a-half-inning" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="runs-scored-in-a-half-inning"><span class="header-section-number">6.2</span> Runs Scored in a Half-Inning</h3>
<p>We treat the runs scored as an ordinal variable and compute logits to describe changes in the runs scored probabilities as we move from one category to another.</p>
<p>Using 2022 season data, I collect the runs scored in the remainder of the inning in the situation where we have bases empty with no outs. From the following table, we see that in this situation, there were no runs scored in 73.4% of innings, 1 run scored in 14.3% of the innings and so on.</p>
<pre><code>O_RUNS.ROI     n   Proportion
          0 33073   0.734
          1  6421   0.143
          2  3091   0.069
          3  1423   0.032
         4+  1050   0.023</code></pre>
<p>For each outcome, we compute a logit defined as the log of the ratio of the fraction less than or equal to the outcome to the fraction larger than the outcome.</p>
<p><span class="math display">\[
Logit = \log\left(\frac{frac \, outcome \, or \, smaller}{frac \, larger \, than \, outcome}\right)
\]</span> So for the “0” outcome, we compute</p>
<p><span class="math display">\[
Logit = \log\left( \frac{.734}{.143 + .069 + .032 + .023}\right),
\]</span> for the “1” outcome, we compute</p>
<p><span class="math display">\[
Logit = \log\left( \frac{.734 + .143 }{.069 + .032 + .023}\right),
\]</span></p>
<p>If we do this for all five outcomes we get the following table.</p>
<pre><code>O_RUNS.ROI Percent smaller larger Logit
         0   0.734   0.734  0.266 1.015
         1   0.143   0.877  0.123 1.960
         2   0.069   0.945  0.055 2.846
         3   0.032   0.977  0.023 3.736
        4+   0.023   1.000  0.000   Inf</code></pre>
<p>We call the values in the <code>Logit</code> column boundary values – on the logit scale, they divide the probabilities of the 0, 1, 2, 3 outcome categories.</p>
</section>
<section id="comparing-runs-scored-between-two-situations" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="comparing-runs-scored-between-two-situations"><span class="header-section-number">6.3</span> Comparing Runs Scored Between Two Situations</h3>
<p>Suppose now that we have runners on 1st and 2nd with no outs. There is more potential to score runs in this situation than in the “no runners, no outs” situation. How do we measure this advantage?</p>
<p>We fit an ordinal logistic regression model to measure the changes in the logits dividing the “smaller” and “larger” categories of run scored.</p>
<p>The model says that the logit of “smaller” in category <span class="math inline">\(k\)</span> is equal to a boundary value <span class="math inline">\(a_k\)</span> minus an effect <span class="math inline">\(\eta\)</span> due to the new situation.</p>
<p><span class="math display">\[
logit P(smaller) = a_k - \eta
\]</span></p>
<p>We fit this model using the <code>polr()</code> function in the <code>MASS</code> package.</p>
<pre><code>polr(O_RUNS.ROI ~ 1 + STATE, 
      data = filter(d2022, STATE %in% two_states))

Coefficients:
STATE110 0 
  1.557154 

Intercepts:
     0|1      1|2      2|3     3|4+ 
1.016599 1.956651 2.817440 3.704878 </code></pre>
<p>The “Intercepts” in the R output are familiar – these are just the boundary logit values that we found between the different run categories. The coefficient estimate is <span class="math inline">\(\eta = 1.557\)</span> – this is the advantage of the “110 0” situation over the “000 0” situation on the logit scale.</p>
<p>For any runs value <span class="math inline">\(k\)</span> and runners on 1st and 2nd with no outs. <span class="math display">\[
logit P(category \, k \, or \, smaller) = a_k - 1.557
\]</span> By construction, for the bases empty and no outs situation <span class="math display">\[
logit P(category \, k \, or \, smaller) = a_k
\]</span> so the advantage of the new situation is 1.557.</p>
<p>It is probably easiest to understand this fit when expressed in terms of the runs probabilities. I display the fitted probabilities for the two states below. With this more advantageous runners on base situation, the chance of not scoring has dropped from 0.734 and 0.368 and the chance of a “big” inning (4 runs or more) has climbed from 0.024 to 0.105.</p>
<pre><code>      State
   000 0 110 0
0  0.734 0.368
1  0.142 0.231
2  0.067 0.181
3  0.032 0.116
4+ 0.024 0.105</code></pre>
</section>
<section id="advantage-in-all-situations" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="advantage-in-all-situations"><span class="header-section-number">6.4</span> Advantage in All Situations</h3>
<p>We can repeat this exercise for all situations defined by runners on base and number of outs. Using the <code>polr()</code> function we just fit the model</p>
<pre><code>O_RUNS.ROI ~ 1 + STATE</code></pre>
<p>The output of the fit are coefficients that give the advantage of each of the 24 states relative to the “bases empty, no outs” state.</p>
</section>
<section id="a-new-table" class="level3" data-number="6.5">
<h3 data-number="6.5" class="anchored" data-anchor-id="a-new-table"><span class="header-section-number">6.5</span> A New Table</h3>
<p>By letting runs scored be an ordinal response and fitting an ordinal logistic model, we obtain a new table of regression coefficients (called a Runs Advantage Table) that gives the advantage of a new situation over the “000 0” state.</p>
<pre><code>              RUNS ADVANTAGE TABLE
     000   100   020   120   003   103  023  123
 0  0.00  0.68  1.13  1.54  1.62  1.94 2.09 2.51
 1 -0.69 -0.01  0.43  0.68  1.04  1.21 1.52 1.63
 2 -1.60 -0.94 -0.47 -0.29 -0.19 -0.12 0.00 0.28</code></pre>
<p>To make sense of this new table …</p>
<ul>
<li>Remember, by model definition the “000 0” state has a value of run advantage 0. Negative run advantage values correspond to runner/outs states that are worse (in terms of scoring runs potential) then the “000 0” state. Positive values (like the “120 0” state) correspond to situations that are more advantageous for scoring runs.</li>
<li>The numbers don’t represent mean runs scored in the remainder of the inning. Instead, they represent the change in logits over the base situation. For example, we see from the table that the value for bases loaded and one out is 1.70. This means that the logit <span class="math display">\[
logit \left(\frac{scoring \le 2}{scoring &gt; 2}\right)
\]</span> is 1.70 smaller than the same logit for the bases empty and no outs situation. Also by the model definition, the logit <span class="math display">\[
logit \left(\frac{scoring \le k}{scoring &gt; k}\right)
\]</span> would be 1.70 smaller than the base rate for any choice of boundary value <span class="math inline">\(k\)</span>.</li>
</ul>
</section>
<section id="graphing-the-effects" class="level3" data-number="6.6">
<h3 data-number="6.6" class="anchored" data-anchor-id="graphing-the-effects"><span class="header-section-number">6.6</span> Graphing the Effects</h3>
<p>As I did earlier for the runs expectancy table, I can graph the run advantages of the different situations (the regression coefficients) as a function of the bases score defined by</p>
<p>Bases Score = sum of runner on bases weights,</p>
<p>where runners on 1st, 2nd, and 3rd are assigned weights of 1, 2, and 4. As before, the color of the point corresponds to the number of outs and I have added smoothing curves to show the basic pattern of these run advantage values.</p>
<p><img src="figures/expectancy/runs9.png" class="img-fluid" style="width:70.0%"></p>
<ul>
<li>The general behavior of these ordinal model coefficients is similar to the behavior of the runs expectancy values. As the bases score increases, there is an increasing trend in the coefficients.</li>
<li>Also for a given value of the bases score, the coefficients decrease as a function of the number of outs.</li>
<li>In contrast to the graph of run expectancies, the trend in these values for a given number of outs is nonlinear.<br>
</li>
<li>The nonlinear pattern is most obvious for two outs. There is a sizable increase when the bases score goes from 0 to 2. But for base score values from 2 to 7, there are only small increases in the coefficients. In contrast, when there no outs, there is (approximately) a constant increase in the coefficient value for each one unit increase in bases score.</li>
</ul>
</section>
<section id="why" class="level3" data-number="6.7">
<h3 data-number="6.7" class="anchored" data-anchor-id="why"><span class="header-section-number">6.7</span> Why?</h3>
<p>What is the point of introducing a new table describe the advantage of particular runner and bases situations?</p>
<ul>
<li><p>Remember I was dissatisfied with just knowing the mean number of runs scored in the remainder of the inning. A mean number like 0.54 is not that helpful in the sense that a team can’t score 0.54 runs. It would be clearer to talk about the chance of scoring, say 0, 1, 2 runs in the remainder of the inning.</p></li>
<li><p>In this method, I am using an ordinal regression model to estimate the run probabilities in the five categories 0, 1, 2, 3, 4+. The probabilities in the five categories change when one goes from the “bases empty and no runners” to another state. The model fit gives a single coefficient which is an additive change to the logits.</p></li>
<li><p>Using this method, I can tell a manager exactly how the run distribution changes when there are runners on base. Although we are measuring things on a logit scale, one can also reexpress the logit distributions back to the probability scale.</p></li>
<li><p>In a future post, I’ll provide some illustrations how this new table can be used similar to the applications of the basic runs expectancy table.</p></li>
</ul>
</section>
<section id="a-statistical-note" class="level3" data-number="6.8">
<h3 data-number="6.8" class="anchored" data-anchor-id="a-statistical-note"><span class="header-section-number">6.8</span> A Statistical Note</h3>
<p>The runs expectancy table gives the mean number of runs scored in the remainder of the inning. Is it possible to create a probability table for runs scored if we know only the mean? Yes, if the distribution of runs scored has a Poisson distribution. Unfortunately, the Poisson is a poor fit to run scoring data for a single half-inning. I did try some alternative distributions like negative binomial, zero-inflated distributions, but they required too many parameters. That led me to use the ordinal scale for run scoring described here.</p>
</section>
</section>
<section id="beyond-runs-expectancy---some-background" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="beyond-runs-expectancy---some-background"><span class="header-section-number">7</span> Beyond Runs Expectancy - Some Background</h2>
<section id="introduction-modeling-runs-scored-in-an-inning" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="introduction-modeling-runs-scored-in-an-inning"><span class="header-section-number">7.1</span> Introduction: Modeling Runs Scored in an Inning</h3>
<p>In last week’s post, I presented a different way of understanding runs potential over different states of an inning defined by the runners on base and the number of outs. The problem of modeling runs scored has addressed by many people over the years. For example, Keith Woolner in this article describes a RPI formula and Patriot describes in this post the Tango distribution and use of a zero-inflated negative binomial distribution.</p>
<p>Some years ago, I did explore the use of standard distributions to represent the runs scored in a half-inning. What I found was that the Poisson model underestimated the probability of a scoreless inning and the negative binomial model (which uses an additional parameter) was unsatisfactory. I could have continued with more sophisticated probability models, but the ordinal response approach seemed pretty easy to apply.</p>
<p>Since some readers may not be familiar with the cumulative logit ordinal response regression model, I will introduce this model by assuming that there is an unobserved run-scoring variable behind the scenes. This motivates the familiar logistic model, and by using more cutpoints, the ordinal regression model. There is an important assumption with this ordinal model, called proportional odds, and I’ll give evidence that this is approximately true for the run scoring data.</p>
<p>Last I’ll contrast runs expectancy and my runs advantage tables over 20 seasons of data. Tom Tango suggested in my ordering of states that the “120” state (runners on 1st and 2nd) should go before the “003” state (runner on third). Runs expectancy suggests that “120” is more valuable than “003” when there are 0 or 2 outs, but runs advantage gives an opposite conclusion.</p>
</section>
<section id="logistic-regression" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">7.2</span> Logistic Regression</h3>
<p>Here is a graphical way to think about logistic regression. Suppose you could measure the run-scoring performance <span class="math inline">\(Z\)</span> of a team – you don’t observe this, but it is the culmination of the team’s ability to get on base and move runners to home. We assume that <span class="math inline">\(Z\)</span> has a logistic (bell-shaped) curve distribution with mean <span class="math inline">\(\mu\)</span> and scale 1 that I show below.</p>
<p>I’d added a vertical line at <span class="math inline">\(Z = 0\)</span>. We observe for each inning if one or more runs scores (<span class="math inline">\(Z &gt; 0\)</span>) or a run does not score (<span class="math inline">\(Z \le 0\)</span>). The mean <span class="math inline">\(\mu\)</span> might depend on other things like the team, home vs away or other covariates. This representation is equivalent to a logistic regression model.</p>
<p><img src="figures/expectancy/runs11.png" class="img-fluid" style="width:70.0%"></p>
</section>
<section id="more-cutpoints---ordinal-regression" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="more-cutpoints---ordinal-regression"><span class="header-section-number">7.3</span> More Cutpoints - Ordinal Regression</h3>
<p>In logistic regression we just recorded 1 if one or more run scores in an inning. Suppose instead we record if one of the five outcomes happens:</p>
<p>no runs scored, 1 run, 2 runs, 3 runs, 4 or more runs</p>
<p>Now we have an ordinal response. We represent the ordinal response model using the same picture but now we have four lines dividing the five possible outcomes. The mean <span class="math inline">\(\mu\)</span> is a function of different things that impact run scoring such as the state of the inning (number of outs and bases occupied.). So really ordinal regression and logistic regression follow the same representation about the logistic curve for <span class="math inline">\(Z\)</span>. The only difference is that we have one cutpoint (0) for the binary response in logistic regression and we have four cutpoints for the ordinal response in ordinal regression. When we fit the ordinal regression model, we estimate the boundaries (cutpoints) and the covariate effect.</p>
<p><img src="figures/expectancy/runs12.png" class="img-fluid" style="width:70.0%"></p>
</section>
<section id="proportional-odds" class="level3" data-number="7.4">
<h3 data-number="7.4" class="anchored" data-anchor-id="proportional-odds"><span class="header-section-number">7.4</span> Proportional Odds</h3>
<p>There is one big assumption in ordinal logistic regression. Suppose we wish to compare the run scoring in two different states, say “no runners on with 0 outs” and “runner on 1st with 1 out”. We assume that the run scoring in the two states has the same logistic curve, where the only difference is the locations – that is, the two curves have the same spread.</p>
<p>Suppose we collect the run scoring <span class="math inline">\(R\)</span> in two states and compute the logits</p>
<p><span class="math display">\[LOGIT =  \log\left(\frac{P(R \le j)}{P(R &gt; j)}\right)\]</span></p>
<p>and we plot these logits against the boundary (value of <span class="math inline">\(j\)</span>) for each state. The model assumes that these logit curves are parallel. That is</p>
<p>LOGIT (state 2) = LOGIT(state 1) + constant.</p>
<p>We can state this in terms of odds which is the ratio of the probability of runs less than or equal to j to the probability of runs greater than j.</p>
<p><span class="math display">\[ODDS =  \frac{P(R \le j)}{P(R &gt; j)}\]</span></p>
<p>For one state the ODDS is a constant multiple of the ODDS for a second state – this is the proportional odds assumption.</p>
<p>ODDS (state 2) = constant <span class="math inline">\(\times\)</span> ODDS (state 1).</p>
<p>We can check this assumption graphically for the 2022 season data. Below I plot the observed logits as a function of the boundary for all 24 states defined by number of outs and runners on base. Generally these logit curves do look parallel – this suggest that the ordinal regression model is reasonable for the run-scoring data.</p>
<p><img src="figures/expectancy/runs10.png" class="img-fluid" style="width:70.0%"></p>
<p>Since this graph is cluttered, let’s look at some specific comparisons of bases situations.</p>
<section id="consecutive-walks" class="level4" data-number="7.4.1">
<h4 data-number="7.4.1" class="anchored" data-anchor-id="consecutive-walks"><span class="header-section-number">7.4.1</span> Consecutive Walks</h4>
<p>Suppose the bases are empty and there are two consecutive walks, so the bases situation moves from “000” to “100” to “120”. Using twenty seasons of data (2000 through 2019), the following plot graphs the cumulative logits <span class="math display">\[LOGIT =  \log\left(\frac{P(R \le j)}{P(R &gt; j)}\right)\]</span> against the boundary value <span class="math inline">\(j\)</span> for the bases “000”, “100”, “120” and for 0, 1, and 2 outs. Here for each value of outs, the logits for the three bases situation look approxiately parallel, confirming the proportional odds assumption. By looking at the Runs Advantage Table, we can get some simple summaries from the fitted ordinal model. For example, when there is one out, moving from “000” to “100” will increase the coefficient by 0.68, and moving from “100” to “120” will increase the coefficient by another 0.69.</p>
<p><img src="figures/expectancy/compare1.png" class="img-fluid" style="width:70.0%"></p>
<p>Suppose we consider the three consecutive walks situation, moving from “000” to “100” to “120” to “123”. The below figure plots the cumulative logits – again the lines look roughly parallel confirming the proportional odds assumption.</p>
<p><img src="figures/expectancy/compare2.png" class="img-fluid" style="width:70.0%"></p>
</section>
<section id="comparing-runner-on-3rd-with-runners-on-1st-and-2nd" class="level4" data-number="7.4.2">
<h4 data-number="7.4.2" class="anchored" data-anchor-id="comparing-runner-on-3rd-with-runners-on-1st-and-2nd"><span class="header-section-number">7.4.2</span> Comparing Runner on 3rd with Runners on 1st and 2nd</h4>
<p>Suppose instead that we consider the “runner on 3rd” situation with the “runners on 1st and 2nd” situation. Here is a graph of the observed logits for those situations.</p>
<p><img src="figures/expectancy/compare3.png" class="img-fluid" style="width:70.0%"></p>
<p>Here the logit lines are clearly not parallel. When there is one out …</p>
<ul>
<li><p>the “003” situation is better than “120” at the 0/1 breakpoint. It is more likely for one run to score when there is a runner on 3rd.</p></li>
<li><p>for the other breakpoints, the “120” situation is better than “003”. There is a better chance for more runs to score when you have two runners.</p></li>
</ul>
</section>
<section id="one-runner-situations" class="level4" data-number="7.4.3">
<h4 data-number="7.4.3" class="anchored" data-anchor-id="one-runner-situations"><span class="header-section-number">7.4.3</span> One Runner Situations</h4>
<p>Let’s consider the three situations “100”, “020” and “003” where there is exactly one runner on base.</p>
<p>Looking at the below figure, note that the three situations are very similar with respect to the cumulative logits at 1/2, 2/3 and 3/4+. But the logits differ at 0/1 – this means that it is more likely for a runner to score from 3rd than from 2nd or from 1st.</p>
<p><img src="figures/expectancy/compare4.png" class="img-fluid" style="width:70.0%"></p>
</section>
<section id="two-runner-situations" class="level4" data-number="7.4.4">
<h4 data-number="7.4.4" class="anchored" data-anchor-id="two-runner-situations"><span class="header-section-number">7.4.4</span> Two Runner Situations</h4>
<p>Next let’s consider the three two-runner situations “120”, “103” and “023” – the logits for these three states for all out values are displayed below.</p>
<p>When there are 0 or 1 outs, it is clearly less likely to score in the “120” situation than the other two situations. It is more likely to score more than 1 run in the “023” situation than the other two situations. The three states are similar in the chances of scoring three or more runs in the remainder of the inning.</p>
<p><img src="figures/expectancy/compare5.png" class="img-fluid" style="width:70.0%"></p>
</section>
</section>
<section id="comparing-runs-expectancy-with-ordinal-coefficients" class="level3" data-number="7.5">
<h3 data-number="7.5" class="anchored" data-anchor-id="comparing-runs-expectancy-with-ordinal-coefficients"><span class="header-section-number">7.5</span> Comparing Runs Expectancy with Ordinal Coefficients</h3>
<p>There is an interesting comparison between the familiar runs expectancy table and my “runs advantage table” where you are displaying the ordinal regression slopes for all bases/outs situation.</p>
<p>Here is the run expectancy table (using data for 20 seasons 2000-2019) and the graph of these values. Following Tom Tango’s suggestion, the “Bases Score” is defined to be</p>
<p>Bases Score = 1 (runner on 1st) + 2 (runner on 2nd) + 4 (runner on 3rd)</p>
<p><img src="figures/expectancy/runs13.png" class="img-fluid" style="width:70.0%"></p>
<p>Note that, for 0 and 2 outs, the “003” situation (column 5) has lower runs expectation than the “120” situation (column 4).</p>
<p>Here is the corresponding table and graph for my ordinal regression coefficients (again using 20 seasons of data). We note:</p>
<p><img src="figures/expectancy/runs14.png" class="img-fluid" style="width:70.0%"></p>
<p>We don’t have that situation described above – “120” has a smaller coefficient than “003” for each of the three outs values.</p>
<p>Generally, the ordinal coefficients are monotone increasing as a function of the bases score for each values of outs.</p>
</section>
<section id="takeaways" class="level3" data-number="7.6">
<h3 data-number="7.6" class="anchored" data-anchor-id="takeaways"><span class="header-section-number">7.6</span> Takeaways</h3>
<ul>
<li><p>Probability Modeling of Runs Scored? Run scoring in baseball is not well represented by typical probability models like the Poisson or negative binomial which motivates the ordinal response regression approach.</p></li>
<li><p>Ordinal and logistic regression are based on the same conceptual logistic distribution framework – you just have more boundaries with the ordinal approach.</p></li>
<li><p>The proportional-odds assumption in ordinal regression seems to be supported by the observed run scoring data.</p></li>
<li><p>Comparing Value of States. The ordinal regression coefficient estimates support the belief that the runner on 3rd situation is more valuable (from a run scoring perspective) than the runners on 1st and 2nd situation. The runs expectancy values don’t support this pattern.</p></li>
<li><p>How Can a Team Score 0.5 Runs? I think the runs advantage table is better than runs expectancy since it tells you something about the distribution of runs scored, not just the average.</p></li>
<li><p>Other Applications. I have illustrated the use of ordinal regression models in earlier posts. In this post, I explore the ordinal response that is the outcome in balls in play and in this post, I use an ordinal model to relate expected wOBA with the Statcast barrels definition.</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>