<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jim Albert">
<meta name="dcterms.date" content="2023-04-14">

<title>Simulation in Baseball</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="Simulation_files/libs/clipboard/clipboard.min.js"></script>
<script src="Simulation_files/libs/quarto-html/quarto.js"></script>
<script src="Simulation_files/libs/quarto-html/popper.min.js"></script>
<script src="Simulation_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Simulation_files/libs/quarto-html/anchor.min.js"></script>
<link href="Simulation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Simulation_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Simulation_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Simulation_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Simulation_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="toc-section-number">1</span>  Introduction</a></li>
  <li><a href="#simulating-a-half-inning-of-baseball" id="toc-simulating-a-half-inning-of-baseball" class="nav-link" data-scroll-target="#simulating-a-half-inning-of-baseball"><span class="toc-section-number">2</span>  Simulating a Half-Inning of Baseball</a>
  <ul class="collapse">
  <li><a href="#runner-movements" id="toc-runner-movements" class="nav-link" data-scroll-target="#runner-movements"><span class="toc-section-number">2.1</span>  Runner Movements</a></li>
  <li><a href="#the-probabilities-of-the-six-basic-events" id="toc-the-probabilities-of-the-six-basic-events" class="nav-link" data-scroll-target="#the-probabilities-of-the-six-basic-events"><span class="toc-section-number">2.2</span>  The Probabilities of the Six Basic Events</a></li>
  <li><a href="#the-simulation-function" id="toc-the-simulation-function" class="nav-link" data-scroll-target="#the-simulation-function"><span class="toc-section-number">2.3</span>  The Simulation Function</a></li>
  <li><a href="#how-do-the-simulation-results-compare-with-real-baseball" id="toc-how-do-the-simulation-results-compare-with-real-baseball" class="nav-link" data-scroll-target="#how-do-the-simulation-results-compare-with-real-baseball"><span class="toc-section-number">2.4</span>  How Do the Simulation Results Compare with Real Baseball?</a></li>
  </ul></li>
  <li><a href="#measuring-cluster-luck-in-scoring" id="toc-measuring-cluster-luck-in-scoring" class="nav-link" data-scroll-target="#measuring-cluster-luck-in-scoring"><span class="toc-section-number">3</span>  Measuring Cluster Luck in Scoring</a></li>
  <li><a href="#measuring-situational-hitting" id="toc-measuring-situational-hitting" class="nav-link" data-scroll-target="#measuring-situational-hitting"><span class="toc-section-number">4</span>  Measuring Situational Hitting</a>
  <ul class="collapse">
  <li><a href="#situational-hitting" id="toc-situational-hitting" class="nav-link" data-scroll-target="#situational-hitting"><span class="toc-section-number">4.1</span>  Situational Hitting</a></li>
  <li><a href="#assessing-situational-hitting-by-a-permutation-test" id="toc-assessing-situational-hitting-by-a-permutation-test" class="nav-link" data-scroll-target="#assessing-situational-hitting-by-a-permutation-test"><span class="toc-section-number">4.2</span>  Assessing Situational Hitting by a Permutation Test</a></li>
  <li><a href="#what-do-we-find" id="toc-what-do-we-find" class="nav-link" data-scroll-target="#what-do-we-find"><span class="toc-section-number">4.3</span>  What Do We Find?</a></li>
  <li><a href="#where-to-go-from-here" id="toc-where-to-go-from-here" class="nav-link" data-scroll-target="#where-to-go-from-here"><span class="toc-section-number">4.4</span>  Where to Go From Here?</a></li>
  <li><a href="#r-work" id="toc-r-work" class="nav-link" data-scroll-target="#r-work"><span class="toc-section-number">4.5</span>  R Work?</a></li>
  </ul></li>
  <li><a href="#simulating-a-60-game-season" id="toc-simulating-a-60-game-season" class="nav-link" data-scroll-target="#simulating-a-60-game-season"><span class="toc-section-number">5</span>  Simulating a 60-Game Season</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1"><span class="toc-section-number">5.1</span>  Introduction</a></li>
  <li><a href="#a-model-for-baseball-competition" id="toc-a-model-for-baseball-competition" class="nav-link" data-scroll-target="#a-model-for-baseball-competition"><span class="toc-section-number">5.2</span>  A Model for Baseball Competition</a></li>
  <li><a href="#simulating-a-season" id="toc-simulating-a-season" class="nav-link" data-scroll-target="#simulating-a-season"><span class="toc-section-number">5.3</span>  Simulating a Season</a></li>
  <li><a href="#simulating-many-seasons" id="toc-simulating-many-seasons" class="nav-link" data-scroll-target="#simulating-many-seasons"><span class="toc-section-number">5.4</span>  Simulating Many Seasons</a></li>
  <li><a href="#how-good-are-the-playoff-teams" id="toc-how-good-are-the-playoff-teams" class="nav-link" data-scroll-target="#how-good-are-the-playoff-teams"><span class="toc-section-number">5.5</span>  How Good Are the Playoff Teams?</a></li>
  <li><a href="#what-is-the-chance-that-a-particular-team-ability-gets-in-the-playoffs" id="toc-what-is-the-chance-that-a-particular-team-ability-gets-in-the-playoffs" class="nav-link" data-scroll-target="#what-is-the-chance-that-a-particular-team-ability-gets-in-the-playoffs"><span class="toc-section-number">5.6</span>  What is the Chance that a Particular Team Ability Gets in the Playoffs?</a></li>
  <li><a href="#how-many-games-should-a-team-win" id="toc-how-many-games-should-a-team-win" class="nav-link" data-scroll-target="#how-many-games-should-a-team-win"><span class="toc-section-number">5.7</span>  How Many Games Should a Team Win?</a></li>
  <li><a href="#wrap-up" id="toc-wrap-up" class="nav-link" data-scroll-target="#wrap-up"><span class="toc-section-number">5.8</span>  Wrap-Up</a></li>
  </ul></li>
  <li><a href="#modeldata-simulations" id="toc-modeldata-simulations" class="nav-link" data-scroll-target="#modeldata-simulations"><span class="toc-section-number">6</span>  Model/Data Simulations</a>
  <ul class="collapse">
  <li><a href="#introduction-2" id="toc-introduction-2" class="nav-link" data-scroll-target="#introduction-2"><span class="toc-section-number">6.1</span>  Introduction</a></li>
  <li><a href="#the-algorithm" id="toc-the-algorithm" class="nav-link" data-scroll-target="#the-algorithm"><span class="toc-section-number">6.2</span>  The Algorithm</a></li>
  <li><a href="#example-1-statistic-is-the-sum" id="toc-example-1-statistic-is-the-sum" class="nav-link" data-scroll-target="#example-1-statistic-is-the-sum"><span class="toc-section-number">6.3</span>  Example 1: Statistic is the Sum</a></li>
  <li><a href="#example-2-statistic-is-the-largest-ofer" id="toc-example-2-statistic-is-the-largest-ofer" class="nav-link" data-scroll-target="#example-2-statistic-is-the-largest-ofer"><span class="toc-section-number">6.4</span>  Example 2: Statistic is the Largest Ofer</a></li>
  <li><a href="#using-this-method-in-teaching" id="toc-using-this-method-in-teaching" class="nav-link" data-scroll-target="#using-this-method-in-teaching"><span class="toc-section-number">6.5</span>  Using this Method in Teaching</a></li>
  </ul></li>
  <li><a href="#streaky-mike-trout" id="toc-streaky-mike-trout" class="nav-link" data-scroll-target="#streaky-mike-trout"><span class="toc-section-number">7</span>  Streaky Mike Trout?</a>
  <ul class="collapse">
  <li><a href="#introduction-3" id="toc-introduction-3" class="nav-link" data-scroll-target="#introduction-3"><span class="toc-section-number">7.1</span>  Introduction</a></li>
  <li><a href="#applying-method-to-trout" id="toc-applying-method-to-trout" class="nav-link" data-scroll-target="#applying-method-to-trout"><span class="toc-section-number">7.2</span>  Applying Method to Trout</a></li>
  <li><a href="#concluding-remarks" id="toc-concluding-remarks" class="nav-link" data-scroll-target="#concluding-remarks"><span class="toc-section-number">7.3</span>  Concluding Remarks</a></li>
  <li><a href="#added-note-11-22-16" id="toc-added-note-11-22-16" class="nav-link" data-scroll-target="#added-note-11-22-16"><span class="toc-section-number">7.4</span>  Added note (11-22-16):</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Simulation in Baseball</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jim Albert </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 14, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>This is a collection of blog posts from <em>Exploring Baseball Data with R</em> on the use of simulation methodology in baseball.</p>
<p>Section 2 describes the simulation of a half-inning of a baseball game. The simulation is based on a relatively simple multinomial model but it does a reasonable job in estimating the number of runs scored in a half-inning. Section 3 applies this simulation model to measure the ability of a team to cluster their on-base events in scoring runs. Section 4 illustrates the use of this same method to explore if David Ortiz was indeed a clutch hitter.</p>
<p>Section 5 focuses on the use of simulation to simulate game outcomes in a season. I apply a Bradley-Terry model where the team abilities follow a normal model. This simulation illustrates that you don’t really learn about team abilities based on results from a 60-game season.</p>
<p>Section 6 describes the use of a “model/data simulation” to illustrate Bayesian inference. By simulating parameters and statistics, one can learn about the parameter location (the posterior) based on a given value of the statistic.</p>
<p>Section 7 describes the use of a simulation-based permutation test to understand the consistency pattern of his pattern of hits/outs, home runs/not home runs, and strikeouts/not strikeouts.</p>
</section>
<section id="simulating-a-half-inning-of-baseball" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="simulating-a-half-inning-of-baseball"><span class="header-section-number">2</span> Simulating a Half-Inning of Baseball</h2>
<p>I am working on a method for determining the efficiency of a team in using its on-base events to score runs. Some baseball teams tend to scatter their on-base events through the nine innings and score few runs. (I am thinking of the 2016 Phillies, but maybe their problem is simply not producing many on-base events.) In contrast, other teams seem to be effective in bunching their on-base events to produce runs. In working on this method, I wanted to write a function to simulate the number of runs scored in a half inning given the overall probabilities of the six basic events OUT, SINGLE, DOUBLE, TRIPLE, HOME RUN, and WALK/HBP, and some basic runner advancement rules. Anyway, I thought it was a good topic for a post.</p>
<section id="runner-movements" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="runner-movements"><span class="header-section-number">2.1</span> Runner Movements</h3>
<p>In my simulation, I wanted to use realistic movements of runners on base on base hits. For example, if there is a runner on first, then sometimes a single will advance runners to first and second, and sometimes you’ll have runners on first and third. Using the 2015 Retrosheet data, I found the frequencies of the different outcomes which can be converted to probabilities. For example, when there is a runner on 1st, a single advanced the runner to 2nd 3940 times, and advanced the runner to 3rd 1411, so the probabilities of the final states “runners on 1st and 2nd” and “runners on 1st and third” are approximated to be 3940 / (3940 + 1411) = 0.736 and 1411 / (3940 + 1411) = 0.264. In a similar fashion, I found the runner advancement probabilities for singles and doubles in all runner situations. Here is the runner advancement matrix for a single. (My notation is that “110” means runners on first and second.)</p>
<pre><code>    000   100 010 001   110   101 011   111
000   0 1.000   0   0 0.000 0.000   0 0.000
100   0 0.000   0   0 0.736 0.264   0 0.000
010   0 0.576   0   0 0.000 0.424   0 0.000
001   0 1.000   0   0 0.000 0.000   0 0.000
110   0 0.000   0   0 0.359 0.239   0 0.401
101   0 0.000   0   0 0.766 0.234   0 0.000
011   0 0.518   0   0 0.000 0.482   0 0.000
111   0 0.000   0   0 0.344 0.223   0 0.433</code></pre>
</section>
<section id="the-probabilities-of-the-six-basic-events" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="the-probabilities-of-the-six-basic-events"><span class="header-section-number">2.2</span> The Probabilities of the Six Basic Events</h3>
<p>Also to make my simulation more realistic, I used the frequencies of the six basic events from 2015 data.</p>
<pre><code>   OUT     BB     1B     2B     3B     HR
0.6817 0.0863 0.1543 0.0454 0.0052 0.0270</code></pre>
<p>Note that I’m ignoring other events such as steals, sacrifices, wild pitches and passed balls that help to produce runs, but I’m interested in how well I can estimating run scoring just using this information.</p>
</section>
<section id="the-simulation-function" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="the-simulation-function"><span class="header-section-number">2.3</span> The Simulation Function</h3>
<p>On my gist site, I have two functions – the function <code>runs_setup()</code> defines the runner advancement matrices and a vector that gives the probabilities of the six basic events, and the function <code>simulate_half_inning()</code> does the actual simulation. Here’s the crux of the actual simulation. Using the <code>sample()</code> function, I simulate an event. I simulate the runner advancement – sometimes, the advancement is deterministic (for example, the bases will always be “001” after a triple), but otherwise I simulate the runner advancement using the <code>Prob_Single</code> and <code>Prob_Double</code> matrices. I update the number of outs and runs scored, and then repeat until we have three outs.</p>
<pre><code> while(outs &lt; 3){
   event &lt;- sample(names(setup$prob), size=1, prob=setup$prob)
   if (event=="1B") new_bases &lt;- sample(all_bases, 1,
                              prob=setup$Prob_Single[bases, ])
   if (event=="2B") new_bases &lt;- sample(all_bases, 1,
                              prob=setup$Prob_Double[bases, ])
   if (event=="BB") new_bases &lt;- sample(all_bases, 1,
                              prob=setup$Prob_Walk[bases, ])
   if (event=="3B") new_bases &lt;- "001"
   if (event=="HR") new_bases &lt;- "000"
   if (event=="OUT") new_bases &lt;- bases
   outs &lt;- outs + (event == "OUT")
   runs &lt;- runs - (event == "OUT") +
           runs.transition(bases, new_bases)
   bases &lt;- new_bases
 }</code></pre>
</section>
<section id="how-do-the-simulation-results-compare-with-real-baseball" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="how-do-the-simulation-results-compare-with-real-baseball"><span class="header-section-number">2.4</span> How Do the Simulation Results Compare with Real Baseball?</h3>
<p>I use the <code>runs_setup()</code> function to do the setup, and the <code>replicate()</code> function together with <code>simulate_half_inning()</code> to simulate the runs scored for 10,000 half-innings:</p>
<pre><code>st &lt;- runs_setup()
R &lt;- replicate(10000, simulate_half_inning(st))
round(prop.table(table(R)), 3)
sim.R
0     1     2     3     4     5     6     7     8    10    12
0.762 0.123 0.060 0.033 0.014 0.005 0.002 0.001 0.000 0.000 0.000</code></pre>
<p>In these simulations, there were 0 runs scored in 76.2% of the half-innings, 1 run scored in 12.3% of the half-innings, and so on.</p>
<p>I’m interested in how the simulated results compare to the real run production during the 2015 season. I’ve graphed the proportions of 0, 1, 2, … runs scored (in a half-inning) using the simulated and actual data. Actually, I have plotted the logit probability which is log (prob / (1 - prob)) – this makes it easier to visualize small probabilities.</p>
<p><img src="figures/simulation/simulation1.png" class="img-fluid" style="width:70.0%"></p>
<p>Looking at the graph, it seems that the simple model predicted a higher proportion of 0-run innings and predicted a lower proportion of 1-run innings. That makes sense, since the model is ignoring events like stolen bases and sacrifice runs that produce a single run. It is interesting that the model seems good in predicting the proportion of runs scored for 2 runs and higher.</p>
<p>In my work, one common theme is that simple models tend to be remarkably accurate in predicting the variability in baseball data. This simulation model is certainly wrong (for example, I was ignoring the variability in run scoring between teams), but the model seems useful in understanding the variation in run scoring.</p>
</section>
</section>
<section id="measuring-cluster-luck-in-scoring" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="measuring-cluster-luck-in-scoring"><span class="header-section-number">3</span> Measuring Cluster Luck in Scoring</h2>
<p>In the last post, I devised a simple model for run scoring in a half-inning. Based on the probabilities of the different PA events and runner advancement probabilities, I wrote a function to simulate the number of runs scored, and the patterns using this model seem to resemble real run scoring in baseball.</p>
<p>I want to use my work to address the following problem. Suppose a team scores 10 runs in a game. I would like to measure the so called “cluster luck” of this run scoring. That is, how many of these 10 runs are attributed to the fact that the team was able to cluster their on-base events? (By the way, this problem has been addressed in other ways – in particular, this post uses a measure which compares the actual runs scored with a runs-created formula.)</p>
<p>Here is my approach. As an example, let’s look at the June 12, 2015 game between the Red Sox and the Blue Jays where the Red Sox scored 10 runs. Using Retrosheet play-by-play data, it was straightforward to extract all of the outcomes (in sequence) of the PA’s during this game.</p>
<pre><code>[1] "OUT" "BB"  "2B"  "1B"  "OUT" "HR"  "HR"  "1B"  "1B"  "BB"  "OUT"
[12] "OUT" "1B"  "OUT" "OUT" "OUT" "1B"  "BB"  "HR"  "OUT" "OUT" "OUT"
[23] "OUT" "OUT" "OUT" "OUT" "1B"  "OUT" "OUT" "OUT" "OUT" "OUT" "OUT"
[34] "OUT" "BB"  "OUT" "OUT" "BB"  "1B"  "BB"  "OUT" "OUT" "BB"  "OUT"
[45] "2B"  "OUT"</code></pre>
<p>If one tabulates these outcomes …</p>
<pre><code>events
 1B  2B  BB  HR OUT
  7   2   7   3  27</code></pre>
<p>we see that the Red Sox had 12 hits (7 singles, two doubles, and 3 home runs), 7 walks, and 27 outs for the nine-innings they batted in this game. Looking at the line-score, it seems that the Red Sox’s scoring exhibited some clustering as they scored 8 of their 10 runs in the 1st and 3rd innings.</p>
<p>Suppose there is really no true clustering in the arrangement of the 46 PA outcomes above. That would suggest that all possible arrangements of these symbols is equally likely. (Actually, not all arrangements are possible since we know the last inning must end with an OUT.)</p>
<p>Here’s my method.</p>
<ul>
<li>Using the <code>sample()</code> function in R, I randomly mix up these 46 symbols. Here is one of these random permutations:</li>
</ul>
<pre><code> [1] "BB"  "OUT" "OUT" "1B"  "HR"  "OUT" "OUT" "OUT" "OUT" "1B"  "OUT"
[12] "1B"  "OUT" "OUT" "OUT" "1B"  "HR"  "OUT" "OUT" "OUT" "BB"  "1B"
[23] "1B"  "OUT" "2B"  "1B"  "OUT" "OUT" "HR"  "OUT" "2B"  "OUT" "BB"
[34] "OUT" "OUT" "BB"  "OUT" "OUT" "OUT" "BB"  "OUT" "OUT" "BB"  "OUT"
[45] "BB"  "OUT"</code></pre>
<p>Based on the outs, I can partition the mixed-up PA’s into nine innings.</p>
<ul>
<li><p>Using my run-scoring algorithm (described in the last post) for each inning, I simulate the runs scored for this mixed-up game given this random arrangement of symbols. (I say “simulate”, since there is randomness in the runner advancement in my scoring algorithm.)</p></li>
<li><p>I repeat the last step a large number of times, obtaining a simulated distribution of runs scored in the game if there is no true clustering. This represents the game run scoring that one would predict if these 7 singles, 2 doubles, 7 walks, 3 home runs, and 27 outs just occurred in some random fashion during the game.</p></li>
<li><p>I compare the actual run scoring with this simulated distribution – if the actual runs scored is “large” relative to the simulated distribution, then that would indicate some “cluster luck”.</p></li>
</ul>
<p>(There is a quibble here. Since my run scoring model ignores run-contributing events such as steals, sacrifices, and wild pitches, then it is seems only fair in my comparison to also apply the same run-scoring algorithm to the actual sequence of PA events. So in the graph below, the “simulated” histogram refers to the simulation assuming the “all possible arrangements are equally likely” model, and the “observed” histogram refers to model simulations based on the observed PA sequence.)</p>
<p>I show two histograms below for this particular Red Sox pattern of PA’s. The top one represents the runs scored using the actual sequence of PA outcomes, and the bottom histogram represents what one would predict using random arrangements of the PA symbols.</p>
<p>s</p>
<p>In this case, the results are a bit surprising. Using the actual PA sequence, the Red Sox would score 9-10 runs in this game – the number tends to understate the actual runs scored (10) a little since my run-scoring model ignores stealing, sacrifices, etc. In the random arrangement model, the Red Sox would also score, on average 9 runs, although the simulated runs scored between 5 and 13. For this particular game I would say that the cluster luck effect in run scoring is pretty small.</p>
<p>Although this work represents a first look at this run clustering issue, it looks promising. One should be able to use this method to compare teams in their abilities to cluster on-base events to score runs. Obviously this is an important issue for a baseball manager. For example, the Phillies manager currently plays with the batting order of his hitters. Using this method, can one offer some guidance on an optimal batting order to make most efficient use of the run clustering effect?</p>
</section>
<section id="measuring-situational-hitting" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="measuring-situational-hitting"><span class="header-section-number">4</span> Measuring Situational Hitting</h2>
<section id="situational-hitting" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="situational-hitting"><span class="header-section-number">4.1</span> Situational Hitting</h3>
<p>Last week, I gave a talk about situational effects in baseball and the most interesting or most talked about situation is “clutch”. &nbsp;That is, does a player have the ability to perform better in clutch situations in baseball? &nbsp;I’m not as interested in the answer as I am in the methods that one might use to explore this question.</p>
<p>Anyway, Nate Silver in his baseball analysis days wrote an interesting article in the Baseball Behind the Numbers book that was reprinted in ESPN&nbsp;that explored this issue, focusing on David Ortiz’s 2005 season where he had a number of clutch performances. &nbsp;My intent here is to describe an alternative simulation-based method of detecting clutch ability, or as Nate would say “smart situational hitting.”</p>
</section>
<section id="assessing-situational-hitting-by-a-permutation-test" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="assessing-situational-hitting-by-a-permutation-test"><span class="header-section-number">4.2</span> Assessing Situational Hitting by a Permutation Test</h3>
<p>I illustrate this method for Ortiz’s 2005 season. &nbsp;In this particular season, Ortiz had 713 plate appearances. &nbsp;If we remove some situation-dependent events such as sacrifices, we have 708 plate appearances that consists of walks/hit-by-pitches, singles, doubles, triples, home runs, outs. &nbsp;These 708 PA’s happened during different runners on base and outs situations. &nbsp;The question is – is there a relationship between the PA outcomes and the game situations? &nbsp;That is, is there evidence that Ortiz was able to get his hits in situations that would produce more runs?</p>
<p>Here’s&nbsp;the setup to my method:</p>
<ul>
<li>First I created a spreadsheet listing all of the runner/outs situations (there are 24 of these) and all of the possible PA outcomes (the 6 listed above) – there are 144 = 24 times 6 rows in the table.</li>
<li>For each situation (variable <code>STATE</code>) and <code>PA</code> outcome, I created a new situation variable (called <code>NEW.STATE</code>) based on the outcome. &nbsp;I used simple runner advancement rules here where a single would advance all runners two bases and a double would advance runners three bases. &nbsp;I could be more accurate here using actual runner advancement distributions, but I don’t think these assumptions will have a big impact on the results.</li>
<li>Using the season’s run expectancy table, I found the runs expectancy before and the runs expectancy value after the PA and computed the runs value of the outcome using the usual “RUNS.VALUE = runs after - runs after + runs scored” recipe.Here is a snippet of this table – I add a runs value column to this table using the season runs expectancy matrix.</li>
</ul>
<p><img src="figures/simulation/simulation12.png" class="img-fluid" style="width:70.0%"></p>
<ul>
<li>Using this runs value table, I can compute the total runs value of Ortiz’s 708 PA’s in the 2005 season &nbsp;– I got a value of 68.86 runs. &nbsp;Remember this is not quite the actual runs created since I am ignoring the actual “after” situations and basing this calculation on my runner advancement model.</li>
</ul>
<p>If the situation has nothing to do with the outcome, then the 708 factorial ways of permuting the outcome arrangements are all equally likely. &nbsp;This motivates the following simulation (essentially it is a so-called permutation test).</p>
<ul>
<li>Randomly mix up the sequence of 708 PA outcomes (using the R sample() function).</li>
<li>Use the runner advancement model, compute the runs values of these 708 outcomes.</li>
<li>Repeat this simulation 1000 iterations, collecting the (simulated) season&nbsp;run values.</li>
</ul>
</section>
<section id="what-do-we-find" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="what-do-we-find"><span class="header-section-number">4.3</span> What Do We Find?</h3>
<p>Below I show a histogram of these simulated runs and show Ortiz’s value of 68.86 as a vertical line.</p>
<p><img src="figures/simulation/simulation13.png" class="img-fluid" style="width:70.0%"></p>
<p>So Ortiz was clutch in the sense that he produced more runs than one would expect if the situations were independent of the outcomes. &nbsp;The right-tail probability (p-value) here is about 0.04 which indicates that he was “significantly” clutch for the 2005 season. &nbsp;Nate Silver also concluded that Ortiz was unusually clutch this season.</p>
<p>But the obvious follow-up question is “Was Ortiz consistently clutch in his career?” &nbsp;I went ahead and repeated this work for each of the seasons 2000 through 2016. &nbsp;For each season, I computed two numbers: &nbsp;<span class="math inline">\(R\)</span>, the actual number of runs Ortiz produced, and <span class="math inline">\(M\)</span>, the mean number of runs using the “situation is independent of outcome” model. &nbsp;Below I show the values of <span class="math inline">\(R\)</span> in black and the values of <span class="math inline">\(M\)</span> in red. &nbsp;Generally both the black points and red points show the same pattern, showing Ortiz’s great rise as a hitter up to the 2005 season.</p>
<p><img src="figures/simulation/simulation14.png" class="img-fluid" style="width:70.0%"></p>
<p>The next graph focuses on the clutch issue by plotting <span class="math inline">\(R - M\)</span> against season, where <span class="math inline">\(R - M\)</span> is the number of additional runs Ortiz got by clever situational hitting.</p>
<p><img src="figures/simulation/simulation15.png" class="img-fluid" style="width:70.0%"></p>
<p>We see that Ortiz was most clutch in 2005, getting 13 additional runs, but this was unusual. &nbsp;Note that the values of R - M fluctuate around zero indicating that there is little evidence that Ortiz was consistently clutch through his career.</p>
</section>
<section id="where-to-go-from-here" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="where-to-go-from-here"><span class="header-section-number">4.4</span> Where to Go From Here?</h3>
<p>By the way, last summer I talked about this same general approach in measuring “cluster luck” in scoring runs.</p>
<p>In his article, Nate Silver speculates that good “situational”&nbsp;hitters can adjust their hitting to the situation, namely the hitters with good bat control who rarely walk. &nbsp;(I don’t think David Ortiz fits in this category.) &nbsp;It would be interesting to do a study that more thoroughly &nbsp;explores this conjecture.</p>
</section>
<section id="r-work" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="r-work"><span class="header-section-number">4.5</span> R Work?</h3>
<p>I have a R markdown file that implements this permutation test procedure for David Ortiz and Derek Jeter. &nbsp;(Spoiler alert: &nbsp;There is little evidence that Jeter had clutch hitting ability using this method.) &nbsp;Here I’m&nbsp;using a single data frame that contains 17 seasons of Retrosheet play-by-play data.</p>
</section>
</section>
<section id="simulating-a-60-game-season" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="simulating-a-60-game-season"><span class="header-section-number">5</span> Simulating a 60-Game Season</h2>
<section id="introduction-1" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="introduction-1"><span class="header-section-number">5.1</span> Introduction</h3>
<p>This is one of my popular things to talk about – the nature of baseball competition. We’d like to think that the winner of the World Series is the “best team in baseball. But if you carefully think what this means, you’ll learn that the winner of the World Series is likely not the team with the most talent. Bill James talked about this topic at a meeting at my school in 1992 (here is a post with more detail) and I’ve written about this in different places.</p>
<p>Anyway, this topic is very relevant today since MLB is planning on a 60-game season for the 2020 season which is 63% shorter than the regular 162-game season. So that motivates this post where I speculate using a simulation what a 60-game regular season will look like. I apply a reasonable model called a Bradley-Terry random effects model for representing baseball competition. By running this simulation for 1000 seasons, we can learn about the association of a team’s ability with its performance and learn also how many games it will take for a team to make the playoffs.</p>
</section>
<section id="a-model-for-baseball-competition" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="a-model-for-baseball-competition"><span class="header-section-number">5.2</span> A Model for Baseball Competition</h3>
<p>The Bradley-Terry model provides a popular and helpful way of modeling team competition. Suppose the thirty MLB teams have unknown ability values, call them <span class="math inline">\(A_1, ..., A_{30}\)</span>, that are distributed according to a normal curve with mean 0 and standard deviation <span class="math inline">\(S\)</span>. If team C plays team D, then the probability that C defeats D is given by the probability</p>
<p><span class="math display">\[p_{CD} = \frac{\exp(A_C - A_D)}{1 + \exp(A_C - A_D)}\]</span></p>
<p>The only parameter unknown in this model is <span class="math inline">\(S\)</span> which reflects the level of competition of the MLB teams. If the teams all have the same ability, then <span class="math inline">\(S\)</span> would be equal to 0. We can actually fit this model and estimate the parameter <span class="math inline">\(S\)</span> using game results data from a previous season. For the work here, I am going to assume that <span class="math inline">\(S\)</span> = 0.3 which seems to reflect the level of MLB competition in recent seasons.</p>
</section>
<section id="simulating-a-season" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="simulating-a-season"><span class="header-section-number">5.3</span> Simulating a Season</h3>
<p>Using this Bradley Terry model, it is straightforward to use R to simulate a 2020 baseball season as follows.</p>
<ul>
<li><p>First I simulate 30 random numbers from a normal distribution with mean 0 and standard deviation 0.3 – these numbers will represent the abilities of the 30 teams. Note that team names are matched at random to these abilities, but I suppose we could attach names in a less-random fashion based on current Vegas odds.</p></li>
<li><p>Then I simulate all of the game results in the MLB’s proposed 60-game schedule. Each team plays 10 games against each team in its own division (total of 40 games), and then 4 games against each team in the other league same division (total of 20 games).</p></li>
</ul>
<p>Here’s the final standings for one of the simulated 60-game seasons (again you can ignore the team names since the teams are randomly assigned to the team strengths):</p>
<p><img src="figures/simulation/simulation3.png" class="img-fluid" style="width:50.0%"></p>
<p>These are the type of W/L records that one might see in a 2020 season. Several teams like SEA and BAL in this particular simulation will win close to 40 games. A number of teams will hover between 28-32 wins (11 teams in this particular simulation) which will lead to some drama towards the end of the season fighting for the wild card berths. Look at the AL Central – all teams have between 29 and 33 wins – I suspect we’ll see a division like this in 2020.</p>
</section>
<section id="simulating-many-seasons" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="simulating-many-seasons"><span class="header-section-number">5.4</span> Simulating Many Seasons</h3>
<p>I wrote a R function <code>one.simulation.20()</code> that will simulate a single season of 60 games. The output of this function are the numbers of wins for each team, the division winners and the wild card teams for each league. In addition, we record the team talents (values of <span class="math inline">\(A_1, ..., A_{30}\)</span>) that were used in this simulation.</p>
<p>We repeat this process for 1000 seasons, collecting all of the variables for all seasons. This repeated-season data is helpful for understanding the relationship between a team’s ability and its performance during a season. This simulation results will also help us understand how likely it is for teams of different abilities to get into the playoffs. Last, we’ll use the simulation to see many games a team needs to win to have a good chance of making the playoffs.</p>
</section>
<section id="how-good-are-the-playoff-teams" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="how-good-are-the-playoff-teams"><span class="header-section-number">5.5</span> How Good Are the Playoff Teams?</h3>
<p>Before the season begins, we know that a team’s ability is normally distributed with mean 0 and standard deviation 0.3. What have you learned about a team’s ability if they win their division? What have you learned about the team’s ability if they are one of the wild card teams? These questions are easy to answer from our simulation. We collect the talent values for all of the teams that win a division, and similarly collect the talent values for the wild card teams. Here I display density estimates of the talents for three groups – all teams, the wild-card teams and the division-winning teams.</p>
<p><img src="figures/simulation/simulation4.png" class="img-fluid" style="width:70.0%"></p>
<p>Actually, this graph shows that you don’t really learn much about a team’s ability based on their performance in this 60-game season. Sure, a division-winner tends to have more talent than a wild-card team, but the difference between the “win division” density curve and the “wild card” density curve seems pretty small. Note also that it appears that below-average teams, that is teams with a negative talent value, are included in the teams making the playoffs.</p>
</section>
<section id="what-is-the-chance-that-a-particular-team-ability-gets-in-the-playoffs" class="level3" data-number="5.6">
<h3 data-number="5.6" class="anchored" data-anchor-id="what-is-the-chance-that-a-particular-team-ability-gets-in-the-playoffs"><span class="header-section-number">5.6</span> What is the Chance that a Particular Team Ability Gets in the Playoffs?</h3>
<p>Here we address a related question. Suppose you know a team’s talent value – what is the chance that the team with this talent will make the playoffs, either as a division-winner or a wild-card team? Here the outcome of a team’s performance is ordinal – either it doesn’t make the playoffs, it is a wild-card team, or it is a division-winner. Using an ordinal regression model, I estimate the probabilities of the three outcomes as a function of its talent using our simulated data. Below I show the estimated probability of (1) winning division, (2) wild-card, and (3) playoff (either winning division or wild card) as a function of the team talent.</p>
<p><img src="figures/simulation/simulation5.png" class="img-fluid" style="width:70.0%">x</p>
<p>Here are some interesting takeaways from this graph:</p>
<ul>
<li><p>An average team, that is a team with a talent value of 0, has a 25% chance of making the playoffs.</p></li>
<li><p>The chance of being a wild card team is maximized for a team with talent value of 0.25.</p></li>
<li><p>A “top 10%” team has a talent value of 0.38. This team has approximately a 75% chance of making the playoffs.</p></li>
</ul>
</section>
<section id="how-many-games-should-a-team-win" class="level3" data-number="5.7">
<h3 data-number="5.7" class="anchored" data-anchor-id="how-many-games-should-a-team-win"><span class="header-section-number">5.7</span> How Many Games Should a Team Win?</h3>
<p>Here is a question that many managers are currently thinking about. How many games do they have to win in a 60-game season to get into the playoffs? Again, this is easy to answer from our 1000 simulated seasons. We find the proportion of teams that (1) win their division, (2) are wild cards, and (3) make playoffs for each of the win totals of 25 through 45. Here’s the graph – some things we learn:</p>
<p><img src="figures/simulation/simulation6.png" class="img-fluid" style="width:70.0%"></p>
<ul>
<li><p>A team finishing with a 30-30 record only has about a 12% chance of making the playoffs.</p></li>
<li><p>But a 35-25 team will likely (with probability 86%) make the playoffs either as a division winner (43%) or a wild card (43%). In fact, the chance of being a wild card team is maximized by winning 35 games.</p></li>
<li><p>Winning a few more games beyond 35 really has a dramatic effect on the probability of making the playoffs – with 37 wins, the probability of making the playoffs is almost 100%</p></li>
</ul>
</section>
<section id="wrap-up" class="level3" data-number="5.8">
<h3 data-number="5.8" class="anchored" data-anchor-id="wrap-up"><span class="header-section-number">5.8</span> Wrap-Up</h3>
<ul>
<li><p>Again, if you want to read more about the Bradley-Terry model, look at my older post.</p></li>
<li><p>I could have improved the Bradley-Terry model by adding a term to account for home-advantage, but I don’t think that would have had much effect on the findings from the simulation.</p></li>
<li><p>I have written a Markdown file available on my Github Gist site that does all of this R work. This Markdown file includes the function <code>one.simulation.20()</code> which implements one 2020 season simulation and the function <code>print_standings()</code> which displays the division standings of the simulated results as shown above. The simulation function is similar to the function described in detail in Chapter 9 of <em>Analyzing Baseball with R</em> – in that chapter, I was simulating the 1968 season.</p></li>
<li><p>I have only talked about simulating the 2020 regular season. Another round of uncertainty is added with the baseball playoffs. All of these playoff series are relatively short (especially the game between the two wild card teams in each league) and so the outcomes are pretty unpredictable. I thought it would be best here to focus on the regular season since we’ve never seen a 60-game season in MLB baseball history.</p></li>
</ul>
</section>
</section>
<section id="modeldata-simulations" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="modeldata-simulations"><span class="header-section-number">6</span> Model/Data Simulations</h2>
<section id="introduction-2" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="introduction-2"><span class="header-section-number">6.1</span> Introduction</h3>
<p>One of the innovative aspects of my <em>Teaching Statistics Using Baseball</em> text is its use of Bayesian thinking to introduce statistical inference. I thought it would be instructive to illustrate a simulation-based way of performing Bayesian inference for a hitting probability. I call this “model/data simulation” – I coauthored a paper in the American Statistician back in 2001 that describes this method in more detail.</p>
</section>
<section id="the-algorithm" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="the-algorithm"><span class="header-section-number">6.2</span> The Algorithm</h3>
<section id="construct-a-prior" class="level4" data-number="6.2.1">
<h4 data-number="6.2.1" class="anchored" data-anchor-id="construct-a-prior"><span class="header-section-number">6.2.1</span> Construct a Prior</h4>
<p>We are interested in learning about <span class="math inline">\(P\)</span>, the probability a particular batter gets a hit. Suppose we think that values of <span class="math inline">\(P\)</span> of .15, .16, …, .39, .4 are all possible and our prior assigns each value the same probability. (The choice of uniform prior can be modified if one believes that particular values of <span class="math inline">\(P\)</span> are more or less likely.)</p>
</section>
<section id="decide-on-a-statistic" class="level4" data-number="6.2.2">
<h4 data-number="6.2.2" class="anchored" data-anchor-id="decide-on-a-statistic"><span class="header-section-number">6.2.2</span> Decide on a Statistic</h4>
<p>We are going to observe the batting outcomes (hit or out) for, say 500 at-bats – we can represent the outcomes as the sequence</p>
<p>0, 1, 0, 0, 1, 1, 0, 0, 0, …</p>
<p>where 1 (0) denotes a hit (out). We will compute a Statistic based on these 500 outcomes – possible Statistics are (1) the number of hits, or (2) the largest “ofer” (that is, the largest gap between consecutive base hits).</p>
</section>
<section id="simulate" class="level4" data-number="6.2.3">
<h4 data-number="6.2.3" class="anchored" data-anchor-id="simulate"><span class="header-section-number">6.2.3</span> Simulate</h4>
<p>Okay, here is how one implements the algorithm. First one simulates a value of <span class="math inline">\(P\)</span> from my prior, call it <span class="math inline">\(P_0\)</span>. Then one simulates batting outcomes assuming <span class="math inline">\(P = P_0\)</span> and computes the value of the statistic <span class="math inline">\(S\)</span>. One repeats this a large number of times, obtaining many ordered pairs <span class="math inline">\((P, S)\)</span>.</p>
</section>
<section id="inference" class="level4" data-number="6.2.4">
<h4 data-number="6.2.4" class="anchored" data-anchor-id="inference"><span class="header-section-number">6.2.4</span> Inference</h4>
<p>To implement Bayes’ rule, suppose that we observe <span class="math inline">\(S = S_{obs}\)</span>. Then we look at the simulated values of <span class="math inline">\(P\)</span> only for the pairs where <span class="math inline">\(S = S_{obs}\)</span>. This sample represents a simulated sample from the posterior distribution of P conditional on <span class="math inline">\(S = S_{obs}\)</span>. We perform various inferences by summarizing this posterior sample.</p>
</section>
<section id="r-functions" class="level4" data-number="6.2.5">
<h4 data-number="6.2.5" class="anchored" data-anchor-id="r-functions"><span class="header-section-number">6.2.5</span> R Functions</h4>
<p>I’ve written two R functions <code>model_data_simulation()</code> and <code>inference_plot()</code> (available on my github gist site) that implements this method. The first function does the model/data simulation and the second function implements the Bayesian inference once we observe <span class="math inline">\(S = S_{obs}\)</span>. These functions can be read into the workspace by use of the <code>source_gist()</code> function.</p>
<pre><code>library(devtools)
source_gist("2a78aaf69a0e54fe1a35fbedeb662e62",
            filename="model_data_simulation.R")</code></pre>
</section>
</section>
<section id="example-1-statistic-is-the-sum" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="example-1-statistic-is-the-sum"><span class="header-section-number">6.3</span> Example 1: Statistic is the Sum</h3>
<p>Suppose we wish to learn about <span class="math inline">\(P\)</span> based on the sum of the binary outcomes, that is, the number of hits. In the R script, we first define a vector <code>P_vector</code> containing the possible values of <span class="math inline">\(P\)</span> between 0.15 and 0.40. Then we use the <code>model_data_simulation()</code> function with arguments <code>P_vector</code> , <code>N</code> (the number of at-bats), and <code>mystat</code> , the choice of statistic (here <code>sum()</code> ). The output is a plot of the simulated draws of <span class="math inline">\(P\)</span> and <span class="math inline">\(S\)</span>. As one might anticipate, there is a positive association between the value of <span class="math inline">\(P\)</span> and the number of hits in 500 at-bats</p>
<pre><code>P_vector &lt;- seq(.15, .40, by=.01)
S1 &lt;- model_data_simulation(P_vector,
                            N=500,
                            mystat=sum)</code></pre>
<p><img src="figures/simulation/simulation7.png" class="img-fluid" style="width:50.0%"></p>
<p>Suppose we observe the batter get 150 hits in the 500 at-bats. We use inference_plot with arguments <code>S1</code> (the simulated draws of <span class="math inline">\(P\)</span> and <span class="math inline">\(S\)</span> from the model/data simulation) and 150 (the observed value of the statistic). The output is a density plot of the simulated values of <span class="math inline">\(P\)</span> conditional on <span class="math inline">\(S = 150.\)</span> We show the location of a 50% interval estimate – here the probability <span class="math inline">\(P\)</span> is in the interval (.290, .310) is 0.50.</p>
<p><img src="figures/simulation/simulation8.png" class="img-fluid" style="width:50.0%"></p>
<pre><code>inference_plot(S1, 150)</code></pre>
</section>
<section id="example-2-statistic-is-the-largest-ofer" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="example-2-statistic-is-the-largest-ofer"><span class="header-section-number">6.4</span> Example 2: Statistic is the Largest Ofer</h3>
<p>To illustrate the use of a different statistic, suppose we focus on the largest “ofer” value – that is, the length of the longest streak of 0’s in the sequence. First I write a function <code>max_ofer()</code> that computes the largest ofer (note that I’m using a function from my <code>BayesTestStreak</code> package). Then I rerun <code>model_data_simulation()</code> where the statistics function is <code>max_ofer</code> . Here note there is a negative association between <span class="math inline">\(P\)</span> and the longest ofer – weak hitters tend to have larger ofers.</p>
<pre><code>max_ofer &lt;- function(y){
  require(BayesTestStreak)
  max(find.spacings(y)$y)
}
S2 &lt;- model_data_simulation(P_vector,
                           N=500,
                           mystat=max_ofer)</code></pre>
<p><img src="figures/simulation/simulation9.png" class="img-fluid" style="width:50.0%"></p>
<p>Suppose you observe a hitter whose maximum ofer is 30. We run inference_plot using the statistics value of 30. We see we are 50% sure that P is between 0.160 and 0.200 – the batter is relatively weak.</p>
<pre><code>inference_plot(S2, 30)</code></pre>
<p><img src="figures/simulation/simulation10.png" class="img-fluid" style="width:50.0%"></p>
</section>
<section id="using-this-method-in-teaching" class="level3" data-number="6.5">
<h3 data-number="6.5" class="anchored" data-anchor-id="using-this-method-in-teaching"><span class="header-section-number">6.5</span> Using this Method in Teaching</h3>
<p>I like this method of introducing inference for several reasons:</p>
<ul>
<li><p>It helps the student understand the distinction between the parameter and the statistic. It is flexible – one can play with different choices of statistic <span class="math inline">\(S\)</span>.</p></li>
<li><p>Inference is easy to implement – one performs inference by data analysis on a simulated sample, and one can make straight-forward interpretations of interval estimates. (One does not have to consider samples that you did not observe.)</p></li>
</ul>
</section>
</section>
<section id="streaky-mike-trout" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="streaky-mike-trout"><span class="header-section-number">7</span> Streaky Mike Trout?</h2>
<section id="introduction-3" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="introduction-3"><span class="header-section-number">7.1</span> Introduction</h3>
<p>As you probably know, Mike Trout was chosen to be the American League MVP in 2016. &nbsp;Trout has had a remarkable five full seasons in the big leagues – for two seasons he was chosen MVP and the other three seasons he finished runner-up in the MVP voting. &nbsp;(I wish Trout played for a east-coast team, so I would have more opportunities to see him play. &nbsp;Mike Trout was a Phillies fan growing up.)</p>
<p>Obvious, Trout has had great season totals in WAR, home runs, etc. &nbsp;But we’ll explore Trout’s hitting from a different perspective — how streaky has Trout been in his pattern of hitting in the 2012 through 2016 seasons?</p>
<p>I’ll give you some background on my work on streakiness. &nbsp;(Here’s a link to a Chance article on streakiness in home run hitting.)</p>
<ol type="1">
<li><p>Suppose you look at player’s sequence of official at-bats and record each AB as hit (1) or an out (0).</p></li>
<li><p>Record the values of the spacings, the number of outs between each pair of consecutive hits. &nbsp;Spacing values close to 0, or large spacings values indicate some streakiness in the 0/1 sequence.</p></li>
<li><p>Of course, we’ll observe some unusual spacings values, but the relevant question is: &nbsp;are these values different from what one would observe if Trout was truly consistent? (Truly consistent means that Trout’s probability of success remains constant throughout the season.)</p></li>
<li><p>I have proposed various measures of streakiness, but one simple measure is the sum of squares of the spacing values – if this is large this indicates some streakiness.</p></li>
<li><p>One can test a hypothesis of consistency by a permutation test – here is how you do this.</p></li>
</ol>
<ul>
<li>Randomly permute the sequence of 0’s and 1’s.</li>
<li>Compute the sum of squared spacings, call this S.</li>
<li>Repeat 1 and 2 many times – one gets a distribution of the value of S if we had a consistent model.</li>
<li>Find the p-value = the proportion of values of S that are least as large as the observed value of S from Trout’s data.</li>
</ul>
</section>
<section id="applying-method-to-trout" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="applying-method-to-trout"><span class="header-section-number">7.2</span> Applying Method to Trout</h3>
<p>For each of Trout’s seasons (2012 through 2016), I conducted this test of consistency of his hit/out data – a small p-value indicates some evidence for “significant” streakiness.</p>
<p>But this streaky measure can depend on what you consider a success. &nbsp;So I repeated this for</p>
<ol type="a">
<li><p>home run data – either Trout gets a HR (1) or not a HR (0)</p></li>
<li><p>strikeout data – either Trout strikes out (1) or doesn’t strike out (0)</p></li>
</ol>
<p>So I am doing this test of streakiness a total of 15 times – for each season for each type of data (hit/out, HR or not, SO or not). &nbsp;Here is a graph summarizing the p-values I found (I have colored the points blue for interesting values where the p-value is small which indicates some streakiness).</p>
<p><img src="figures/simulation/simulation11.png" class="img-fluid" style="width:70.0%"></p>
<p>What do we see?</p>
<ul>
<li>For Hit/Out data, Trout has been remarkably consistent in his pattern of hitting. &nbsp;All of the p-values are in the .5-1 values. &nbsp;(A value close to 1 indicates an unusual pattern more consistent than one would anticipate if one were flipping a coin with a constant chance of success.)</li>
<li>For HR data, Trout has been remarkably consistent – the spacings between home runs have been consistent, especially for 2012, 2014, 2016. &nbsp;There is some evidence for streakiness in 2015. &nbsp;In further observation, I see that Trout had a “0 for 95” homeless streak in 2015.</li>
<li>For SO data, Trout has exhibited some streakiness in 2012 and 2016. &nbsp;Looking further at his 2016 data, I see a number of large spacings (11, 14, 10, 14, 14, 15, 17, 16). &nbsp;This is actually good – this means that he had a number of stretches where he did not have a strikeout. &nbsp;I haven’t looked at this carefully, but this seems remarkable for a power hitter.</li>
</ul>
</section>
<section id="concluding-remarks" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="concluding-remarks"><span class="header-section-number">7.3</span> Concluding Remarks</h3>
<p>In my research, I have explored streakiness in baseball history, and I have explored remarkable consistency in historical batting performance. &nbsp;(For example, Henry Aaron had a very&nbsp;consistent pattern of hitting home runs in his career.) &nbsp;I think a player’s hitting ability can be explained partly by his pattern of streaks and slumps. &nbsp;I don’t know a lot about Trout’s approach to hitting, but his manager should be happy that he does not appear to exhibit streaks of poor performance.</p>
</section>
<section id="added-note-11-22-16" class="level3" data-number="7.4">
<h3 data-number="7.4" class="anchored" data-anchor-id="added-note-11-22-16"><span class="header-section-number">7.4</span> Added note (11-22-16):</h3>
<p>I have added some R code on my gist site which (1) reads in the 2015 Retrosheet play-by-play data, (2) extracts Trouts sequence of successes and failures using H, HR, or SO as the definition of success, and (3) implements functions from the <code>BayesTestStreak</code> package to find the spacings and do a permutation test of randomness.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>