<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Beta Example • TeachBayes</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><meta property="og:title" content="Beta Example">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">TeachBayes</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">1.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/beta_example.html">Beta Example</a>
    </li>
    <li>
      <a href="../articles/finite_sampling.html">Sampling from a Box of Two Types of Colored Balls</a>
    </li>
    <li>
      <a href="../articles/spinner_example.html">Spinner Example</a>
    </li>
    <li>
      <a href="../articles/teachbayes_intro.html">TeachBayes Package</a>
    </li>
    <li>
      <a href="../articles/two_proportions.html">Two_Proportions</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Beta Example</h1>
            
      
      
      <div class="hidden name"><code>beta_example.Rmd</code></div>

    </div>

    
    
<div id="selecting-a-beta-curve" class="section level3">
<h3 class="hasAnchor">
<a href="#selecting-a-beta-curve" class="anchor"></a>Selecting a Beta Curve</h3>
<p>Here’s an example of choosing a beta curve to represent my opinions about a basketball player’s free-throw shooting proportion <span class="math inline">\(p\)</span>. Here are my initial thoughts:</p>
<ol style="list-style-type: decimal">
<li><p>My “best guess” at her shooting proportion is <span class="math inline">\(p = .7\)</span> – that is, it is equally likely that <span class="math inline">\(p\)</span> is smaller than .7, or that <span class="math inline">\(p\)</span> is larger than .7.</p></li>
<li><p>I am pretty confident (with probability .9) that her shooting proportion is smaller than .85.</p></li>
</ol>
<p>In other words, my prior median is .7 and my prior 90th percentile is .85.</p>
<p>The function beta.select will find the shape parameters of the beta curve that match these prior statements. I specify each quantile with a list (x is the value and p is the probability corresponding to the quantile).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(TeachBayes)
quantile1 &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">x =</span> .<span class="dv">7</span>, <span class="dt">p =</span> .<span class="dv">5</span>)
quantile2 &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">x =</span> .<span class="dv">85</span>, <span class="dt">p =</span> .<span class="dv">9</span>)
(ab &lt;-<span class="st"> </span><span class="kw">beta.select</span>(quantile1, quantile2))</code></pre></div>
<pre><code>## [1] 8.13 3.67</code></pre>
<p>So the beta curve with shape parameters 8.13 and 3.67 match my prior information.</p>
<p>Note: There is a Shiny app in the TeachBayes package to facilitate the selection of a beta curve. One uses sliders to input the prior median and prior 90th percentile and the app will show the beta curve that matches this information.</p>
<p>One runs this Shiny app by typing</p>
<p>ChooseBeta()</p>
</div>
<div id="checking-my-beta-curve" class="section level3">
<h3 class="hasAnchor">
<a href="#checking-my-beta-curve" class="anchor"></a>Checking My Beta Curve</h3>
<p>To see if this is really a good representation of my prior beliefs, it is helpful to construct several graphs.</p>
<div id="a-90-probability-interval" class="section level4">
<h4 class="hasAnchor">
<a href="#a-90-probability-interval" class="anchor"></a>A 90% probability interval</h4>
<p>I can construct the interval that will contain the middle 90% of the beta curve area.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/beta_interval.html">beta_interval</a></span>(.<span class="dv">9</span>, ab)</code></pre></div>
<p><img src="../../../../R,%20LANGUAGES/R%20PACKAGES/TeachBayes/vignettes/Figs/unnamed-chunk-2-1.png" width="576"></p>
</div>
<div id="compute-beta-probabilities" class="section level4">
<h4 class="hasAnchor">
<a href="#compute-beta-probabilities" class="anchor"></a>Compute beta probabilities</h4>
<p>Or I can compute several beta probabilities of interest.</p>
<p>Here is the probability that p is smaller than .75</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/beta_area.html">beta_area</a></span>(<span class="dv">0</span>, .<span class="dv">75</span>, ab)</code></pre></div>
<p><img src="../Figs/unnamed-chunk-3-1.png" width="576"></p>
</div>
<div id="simulate-a-beta-curve" class="section level4">
<h4 class="hasAnchor">
<a href="#simulate-a-beta-curve" class="anchor"></a>Simulate a beta curve</h4>
<p>An alternative way to represent a beta curve is to simulate a large number of values from the distribution and summarize the simulated output.</p>
<p>Here I simulate 1000 values from my beta prior and construct a histogram of the simulated draws and put a density estimate on top.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="kw"><a href="../reference/beta_data.html">beta_data</a></span>(ab)
<span class="kw">ggplot</span>(<span class="kw">data.frame</span>(<span class="dt">p=</span>p), <span class="kw">aes</span>(<span class="dt">x=</span>p)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y =</span> ..density..), 
                 <span class="dt">fill=</span><span class="st">"orange"</span>, <span class="dt">color=</span><span class="st">"black"</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_density</span>()</code></pre></div>
<p><img src="../../../../R,%20LANGUAGES/R%20PACKAGES/TeachBayes/vignettes/Figs/unnamed-chunk-4-1.png" width="576"></p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by .</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
